### ISSUE TITLE
Docker run and detach

### ISSUE THREAD

**Issue by perpective2410** [apocas/dockerode#106]
Hi,

I am trying to docker.run an image in detached mode. In docker command I am using:

```
docker run --detach=true  --name api -t registry:5000/api:latest
```

I can then see in "STATUS" column (docker ps -a on the host) that the container is Up and running.

Trying to do the same thing with the API

```
docker.run("registry:5000/api:latest",null , null, 
    {   
        detach: true,
        name: "api"
    }, 
    function (err, data, container) {
            console.log("callback!")
    }
);
```

When I check with docker ps -a the container is up and running but It never goes in the callback even though detach = true.

I tried to add the option Tty: false to the list of options above
It goes in the callback but the status of the container is "Exited (0) 4 seconds ago "

Any idea to keep my container up and running in detach mode with the API ?

Thanks

**Comment by BelkeriSai** [comment]
> Check the examples, like: https://github.com/apocas/dockerode/blob/master/examples/exec_running_container.js

How can we return the Container ID if the whole code in the above example was part of a function and that function is called to Spin up a container?

If not the Container Id, Then at least some status code would do.

Please help.
