### ISSUE TITLE
exec stdout and stdin not working

### ISSUE THREAD

**Issue by guy-codefresh** [apocas/dockerode#117]
I'm trying to use your library in order to work with docker using nodejs

on the container level all is working well, I can work with the stream of the container and interact with it.
But when I'm trying to work with the container.exec and interact with the stdin/out it's not working.

The container is running ubuntu 14.04

please advise

example:
       var options = {
            "AttachStdin":true,
            "AttachStdout":true,
            "AttachStderr":true,
            "Tty":false,
            Cmd: ["/bin/bash"]
        };
        container.exec(options, function(err, exec) {           
            exec.start({
               stdin: true
            }, function(err, stream) {               
                stream.on('data', function(chunk) {
                    var buf = new Buffer(chunk);
                    var message = buf.toString('utf8');
                    console.log(message);
                });
            });
        });

**Comment by apocas** [comment]
Here is someone with an working example :)
https://github.com/apocas/dockerode/issues/122
