### ISSUE TITLE
permissions problem creating a container

### ISSUE THREAD

**Issue by jmls** [apocas/dockerode#118]
I have a host running docker. There is a container running, and I want this container to create another container on the host.

In my running container, I have this code :
 
``` javascript
var docker = new Docker({socketPath: '/tmp/docker.sock'});

docker.createContainer({Image: 'ubuntu', 
                         Cmd: ['/bin/bash'], 
                         name: 'ubuntu-test'}, function (err, container) { ... }
```

I am trying to run this code from a node process in a docker container

/tmp/docker.sock is passed through the -v option
    
    -v /var/run/docker.sock:/tmp/docker.sock

however, I am getting an error passed to my function

    { [Error: read EACCES] code: 'EACCES', errno: 'EACCES', syscall: 'read' }

what am I missing ? 

thanks

**Comment by jmls** [comment]
as usual, you spend all day on this. You post a question / raise an issue and 10 minutes later the solution appears ..

I needed to start my docker instance with the  --privileged flag

sorry for the waste of bandwidth

**Comment by apocas** [comment]
No problem :)

Yup thats it, also don't forget you may specify that during container creation.
Check this out: https://github.com/apocas/dockerode/issues/14
