### ISSUE TITLE
docker.pull for private docker-hub repos 

### ISSUE THREAD

**Issue by mcbain** [apocas/dockerode#120]
I've been trying to do a simply pull with dockerode from a private repo at docker-hub. 

I'm using the pullimage function from the other issue, with works perfectly for public repos. 
For private ones only `(STDERR) failed to pull image: HTTP code: 404` is shown.

Any idea?

        function pullImage(tag, cb, onProgress) {
	                     var auth = {
				username: "mjnetworks",
				password: "xxxxxxxxxx",
				email: "mail@mj-networks-gmbh.de",
				serveraddress: "https://index.docker.io/v1",
				auth: ""
			};

			var opts = {
				authconfig: new Buffer(EJSON.stringify(auth)).toString('base64')
			};

			docker.pull(tag, opts, function (err, cmdOutStream) {
				if (err)
					return cb(err, []);

				var parser = JSONStream.parse(),
					output = [];

				function onStreamEvent(evt) {
					output.push(evt);

					if (evt.error)
						return onStreamError(evt.error);

					onProgress && onProgress(evt);
				}

				function onStreamError(err) {
					parser.removeListener('root', onStreamEvent);
					parser.removeListener('error', onStreamError);
					parser.removeListener('end', onStreamEnd);
					cb(err, output);
				}

				function onStreamEnd() {
					cb(null, output);
				}

				parser.on('root', onStreamEvent);
				parser.on('error', onStreamError);
				parser.on('end', onStreamEnd);

				cmdOutStream.pipe(parser);
			});
		}

		pullImage(image, function onCompleted(err, output) {
				if (err)
					return console.error('failed to pull image:', err);

				console.log('done!');
			},
			function onProgress(evt) {
				console.log('pulling progress:', evt);
			});

**Comment by mcbain** [comment]
OK, the 'authconfig' is expected to be the plain object....

if(options.authconfig) {
    optionsf.headers['X-Registry-Auth'] = new Buffer(JSON.stringify(options.authconfig)).toString('base64');
  }

**Comment by ArtworkAD** [comment]
@mcbain whats your final solution? I am also trying to authenticate with docker.

    var opts = {
        authconfig: new Buffer(EJSON.stringify(auth)).toString('base64')
    };

what do I have to change here?

**Comment by mcbain** [comment]
Just Pass the auth object, the base64 encoding and stringify is already done internally.

**Comment by apocas** [comment]
Exactly, docker-modem already base64 encodes the auth object for you.
https://github.com/apocas/docker-modem/blob/master/lib/modem.js#L112

So just give it an auth object, something like this:
{
  username: "username",
  password: "password",
  auth: "",
  email: "your@email.email",
  serveraddress: "https://index.docker.io/v1"
}

**Comment by apocas** [comment]
https://github.com/apocas/dockerode#pull-from-private-repos
