### ISSUE TITLE
Consider adding streaming JSON to certain endpoints

### ISSUE THREAD

**Issue by vincentwoo** [apocas/dockerode#121]
The docker remote APIs for building an image or streaming events from `/events` are sort of weird. For instance, the stream returned from `build` looks like.

    {"stream": "Step 1..."}
    {"stream": "..."}
    {"error": "Error...", "errorDetail": {"code": 123, "message": "Error..."}}

Would it be possible/desirable to get dockerode to emit objects instead? As it stands I'd need to employ my own streaming JSON parser to be able to accurately see what's going on the inside of my build process.

**Comment by apocas** [comment]
This is being handled indirectly at https://github.com/apocas/dockerode/issues/107 :)
