### ISSUE TITLE
Docker exec -it equivalent

### ISSUE THREAD

**Issue by kelonye** [apocas/dockerode#122]
I can't use docker attach because it binds to the primary process but I'm able to run `docker exec -it` on container that is for example running a webserver in foreground. I see Container#exec returns a non-writable stream.

**Comment by apocas** [comment]
Bit lost here :)

Container#exec calls https://docs.docker.com/reference/api/docker_remote_api_v1.17/#exec-create and then returns an exec object https://github.com/apocas/dockerode/blob/master/lib/exec.js.

Then it start you can get the stream as is described in https://docs.docker.com/reference/api/docker_remote_api_v1.17/#exec-start (you cant deatach at this point if you need/want to)

**Comment by kelonye** [comment]
OK, this my issue https://gist.github.com/kelonye/635b5f227c56452f8b82#file-gistfile1-js-L51

**Comment by kelonye** [comment]
Aha!

```
exec.start( {
  stdin: true,
  ...
});
```
