### ISSUE TITLE
how to authenticate with Docker hub in order to pull the private repo

### ISSUE THREAD

**Issue by ymote** [apocas/dockerode#123]
Hi There,

I am wondering how to handle the Docker hub authentication in order to pull the private docker image? I don't see it in the document but only the authentication for the private registry. Thanks.

ymote

**Comment by apocas** [comment]
This will probably help you :)
https://github.com/apocas/dockerode/issues/120

**Comment by ymote** [comment]
Thanks. Might be a good idea to include it in the readme :-)

**Comment by apocas** [comment]
Wanna throw an example file in the examples folder with this? :)

**Comment by c3h3** [comment]
I guess ... 
the problem might be coming from docker-medom
https://github.com/apocas/docker-modem/blob/master/lib/modem.js#L112

https://docs.docker.com/reference/api/docker_remote_api/
docker registry need 
```
> xx.toString("base64")
'eyJ1c2VybmFtZSI6ICJzdHJpbmciLCAicGFzc3dvcmQiOiAic3RyaW5nIiwgImVtYWlsIjogInN0cmluZyIsICJzZXJ2ZXJhZGRyZXNzIiA6ICJzdHJpbmciLCAiYXV0aCI6ICIifQ=='
> xx.toString()
'{"username": "string", "password": "string", "email": "string", "serveraddress" : "string", "auth": ""}'
```

If we send the object as options.authconfig ... 

We will get ...
```
> yy = {"username": "string", "password": "string", "email": "string", "serveraddress" : "string", "auth": ""}
{ username: 'string',
  password: 'string',
  email: 'string',
  serveraddress: 'string',
  auth: '' }
> new Buffer(JSON.stringify(yy)).toString("base64")
'eyJ1c2VybmFtZSI6InN0cmluZyIsInBhc3N3b3JkIjoic3RyaW5nIiwiZW1haWwiOiJzdHJpbmciLCJzZXJ2ZXJhZGRyZXNzIjoic3RyaW5nIiwiYXV0aCI6IiJ9'
> JSON.stringify(yy)
'{"username":"string","password":"string","email":"string","serveraddress":"string","auth":""}'
> 
```

**Comment by apocas** [comment]
What problem @c3h3 ? :)

Read https://github.com/apocas/dockerode/issues/120
It's a matter of auth object format and documentation lacking about this, I will put something on the readme.md about this later.

**Comment by ArtworkAD** [comment]
:+1:  would like to see this in the documentation.

**Comment by apocas** [comment]
https://github.com/apocas/dockerode#pull-from-private-repos
