### ISSUE TITLE
RUN with named container?

### ISSUE THREAD

**Issue by ArtworkAD** [apocas/dockerode#125]
dockerode can create a container with a name. But how about the run command?

**Comment by ArtworkAD** [comment]
I was confused. Inside shell I had my image and just had to **docker run** it. However using the remote api the workflow seems to be different. First pull image, then create container then run it. When creating the container we can set the name like said in the documentation.

This helped me: https://github.com/apocas/dockerode/issues/39

**Comment by christianhuening** [comment]
Actually a name option would be great on the run command. It's also documented as a query parameter in the Docker Remote API 1.20. It would provide everything I need, given that I can specify everything else in the createOptions parameter of the run function. 

Or is there any reason, why naming is not possible via run?

cheers and thanks
Christian
