### ISSUE TITLE
create container sends env and port options incorrectly

### ISSUE THREAD

**Issue by asquare** [apocas/dockerode#130]
Trying to create a container with an exposed port and an env var -

  docker.createContainer({
    Image: 'hello:0.0.1',
    Cmd: ['node', 'app.js'],
    ExposedPorts: {'80/tcp':{}}
    Env: {'PORT':8080}
  }, function(err, container) { ...

when run with DEBUG=modem, I see the following on the console -

modem Sending: { path: '/containers/create?Image=e4455111414d&Cmd=node&Cmd=app.js&ExposedPorts=&Env=',
...

Note that Cmd is repeated and ExposedPorts and Env are empty. Also the Docker Remote API says that these should be sent as JSON in the body, are they being sent as query parameters?

**Comment by apocas** [comment]
Docker as a wacky format for env variables, unfortunately nothing we can do from our side.

docker.createContainer({
    Tty: true,
    Image: imageName, 
    Env: [
        'PORT=8080'
    ]
}, function (err, container) {
    // etc.
});

**Comment by asquare** [comment]
Thanks - that worked. Might want to add that to one of your examples.

**Comment by williamboman** [comment]
:+1: on adding this to docs :)

**Comment by agrawalapoorv** [comment]
How can we tag the image will commiting (dockerode) ?

**Comment by rmg** [comment]
@agrawalapoorv this issue appears to be about creating containers, which are not tagged..

For tagging an image, it looks like all of the methods of creating an image accept `t` and `repo` parameters, so you should be able to pass `{t: 'tag', repo: 'myrepo'}` as the options.

**Comment by agrawalapoorv** [comment]
Ok thanks alot...
