### ISSUE TITLE
Don't delete authconfig property

### ISSUE THREAD

**Issue by schickling** [apocas/dockerode#133]
I've spent quite some time that the passed in `auth` object for `docker.pull` gets changed. In specific [here](https://github.com/apocas/dockerode/blob/master/lib/docker.js#L356) the `authconfig` property gets deleted. I guess the best way would be to either not delete it or clone the passed in `opts` object to avoid situations like this.

**Comment by apocas** [comment]
Yeah authconfig it's messy in pull, to say the least, it will be refactored on next version.

Will ping later

**Comment by apocas** [comment]
Just refactored docker.pull
Give it a try from the master branch.

Will ping as soon as it is published.

**Comment by apocas** [comment]
Published on v2.1.3
