### ISSUE TITLE
Provide lxc-conf parameters in createContainer method

### ISSUE THREAD

**Issue by ScorpioKing** [apocas/dockerode#134]
We wish to provide static ip to the container, while creating it.

**Comment by apocas** [comment]
Then just specify them in the docker.createContainer parameters.

As said in the documentation parameters are directly sent to docker and follow the official documentation, which in this case is at: https://docs.docker.com/reference/api/docker_remote_api_v1.18/#create-a-container

**Comment by ScorpioKing** [comment]
Thank you. It worked for me.
