### ISSUE TITLE
how to create and write a file into container after creating and starting it ?

### ISSUE THREAD

**Issue by ScorpioKing** [apocas/dockerode#138]
Hello,
I want to create and write a file inside a container after creating and starting it. Can i do it by using this module? How can i do it?

**Comment by apocas** [comment]
This module exposes Docker's Remote API https://docs.docker.com/reference/api/docker_remote_api_v1.18/ so everything of have available in documented there, plus some more stuff that the module does for you.

You have many ways of accomplishing this, creating the file dynamically via an exec, mounting an external volume and creating the file there, ...

**Comment by ScorpioKing** [comment]
Thanks for the reply. Mounting an external volume worked for me.
