### ISSUE TITLE
Cannot set Memory or Cpuset of Containers

### ISSUE THREAD

**Issue by techjacker** [apocas/dockerode#140]
I want to limit the resources of my containers but neither the ```Memory``` nor ```Cpuset``` have any affect when added to ```startOptions``` or ```createOptions``` when using ```container.createContainer``` or ```container.run```.

Have you had any success setting container resources?

**Comment by TeckniX** [comment]
Although it should be straight-forward, something isn't working quite right.
You can look at this example for inspiration:
`https://github.com/apocas/dockerode/blob/master/examples/external_volume.js`

Essentially all options are passed to the docker-modem dial method, which in-turn takes these options and creates a JSON string from them `data = JSON.stringify(opts);` - This data is then passed to the request so that it matches the format declared by the remote API:
`https://docs.docker.com/reference/api/docker_remote_api_v1.18/#create-a-container`

Now if you've followed the proper approach, how are you checking the memory limit? cgroup is what enforces the memory on your container, so running something like `free -m` wont work.

This is how I confirmed mine had the proper limit:
```bash
docker ps -a
# Outputs list of docker containers with their container id - grab the id eg: f03a017b174f
cd /sys/fs/cgroup/memory/docker/ && ls
# A folder that start with the container_id you obtained above should be here
cat f03a017b174ff1022e0f46bc1b307658c2d96ffef1dd97e7c1929a4ca61ab80f/memory.limit_in_bytes
```

The above should output whatever memory limit you have set in bytes; in mine I had set the memory to 100MB, the `cat` operation returned `99999744`

**Comment by techjacker** [comment]
Thanks very much for your help.

I was checking using node.js's `os.totalmem()` command which seems to suffer from the same problem as `free`.

Testing using your cat method and with the docker cli yields the correct result, eg:
`docker inspect --format="{{ .HostConfig.Memory }}" <container_id>`

I've tried googling for this bug but haven't seen anyone else mention it. I'm using the latest node.js stable version 0.10.38.

**Comment by TeckniX** [comment]
Glad you were able to confirm your settings; The bug may just be a change in the API/configs that haven't been caught. 
For example the CPU/Memory settings in the API are mentioned to be sent during a 'create' command, yet dockerode sends it during the start command.

**Comment by techjacker** [comment]
Yes I thought that is was strange that it is an option for `start` rather than `create` as it's not like this with the docker CLI.

I'll look out for updates to the API and this lib.

Thanks again for your help.

**Comment by apocas** [comment]
Hi guys,

Dockerode doe not enforce any option, so you may use it on create or start options, but you obviously have to comply with Remote API documentation or else it won't work.

The documentation says it should be specified on the create endpoint, so you should specify it int the create method options. :)

**Comment by TeckniX** [comment]
@apocas How do you explain that the remote API doesn't allow any Json Parameters to be passed during the 'start' yet Dockerode allows it?

I've tried setting the options on create, as recommended by the API, but haven't been successful in seeing those settings retained during startup.

**Comment by apocas** [comment]
Dockerode does not have to allow anything, it's just using HTTP protocol to talk with Docker.
So you may sent whatever parameters you want, then Docker may accept them or not :)

If you check the inner workings of dockerode and more exactly docker-modem (which dockerode uses for communication) you will see that it's very loose coupled and stateless.

**Comment by TeckniX** [comment]
@apocas I did check the docker-modem a bit, didn't really capture how the params are sent to an api 'start' call, when the api doesn't accept those? Do you call a create before the start?

**Comment by TeckniX** [comment]
I'm an idiot - your start is really a call to docker run, not the actual 'start' api, correct?

**Comment by apocas** [comment]
No no, actually there's no "run" on the Remote API.
Dockerode's "run" is just like the Docker's cli run, it's an orchestration of "create", "start" and "attach" endpoints.

Just check the code: https://github.com/apocas/dockerode/blob/master/lib/docker.js#L374

Dockerode's "start" is API's start like everything else.

Basically think of Dockerode just like Docker's CLI but programatically :)

**Comment by TeckniX** [comment]
Right - I'm looking at the 'container.js'. https://github.com/apocas/dockerode/blob/master/lib/container.js#L156

Here we're making a call to the `/start` path of the remote API, correct?
This in-turn gets passed down to the modem dial prototype:
https://github.com/apocas/docker-modem/blob/master/lib/modem.js#L70

Which then takes these 'start options' and creates a JSON string which is added to the headers:
https://github.com/apocas/docker-modem/blob/master/lib/modem.js#L128

At this point it gets a bit hairy for me to follow, but the data that was stringified gets written to the http request:
https://github.com/apocas/docker-modem/blob/master/lib/modem.js#L198

Yet the 'start' remote API doesn't specify any JSON params that can be sent. Do you see where I'm coming from?

ps: sorry for the back and forth - I'm still in my infancy of docker. :8ball:

**Comment by apocas** [comment]
Sorry but I don't understand where's the problem.

If in the current version of Docker there are now start options, then don't specify any start options in Dockerode... 

containerxpto.start(function() {
//....
});

Like so https://github.com/apocas/dockerode/blob/master/test/container.js#L50

Check the tests.

**Comment by julien-sarazin** [comment]
Hi, 

I'm facing the same issue. I tried different ways to set the limitations, works well with the CLI, same with the standard Remote API, but it does not work with dockerode. I must have missed something.   

I've created a repository that describe my problem.
Would you please take a look to this repository: https://github.com/julien-sarazin/docker-playground.git
And tell me where i'm missing something.

Thanks a lot, for your library and your help!

**Comment by julien-sarazin** [comment]
Updated my example which is now working. My Error came from the options where the "Binds" options wasn't nested inside the "HostConfig" key; making everything acting weirdly.
