### ISSUE TITLE
URL encoded json breaks on API version 1.19

### ISSUE THREAD

**Issue by PerBoussard** [apocas/dockerode#149]
Is dockerode known to, or supposed to work with docker 1.7.0 and/or API version 1.19? I have problems that seem to be related (at least correlated, superficially) with URL encoded JSON. It makes me suspect that the JSON is not carried in the body, and API's up to 1.18 have been forgiving and accepted this. I have a case with a volume mapping that breaks with a 500 complaint that the server can't parse the JSON as go data. When I use the dockerode I get the following from the docker log:
```
INFO[0013] POST /images/create?fromImage=someuser%2Fsomeimage&tag=latest 
INFO[0015] POST /containers/create?Hostname=&User=&AttachStdin=false&AttachStdout=true&AttachStderr=true&Tty=true&OpenStdin=false&StdinOnce=false&Env=&Cmd=&Image=someuser%2Fhidden%3Alatest&Volumes=&VolumesFrom=&Binds=%2Fhome%2Fmyuser%2Fsome%2Fpath%3A%2Fexported-dir%3Aro 
ERRO[0015] Handler for POST /containers/create returned error: json: cannot unmarshal string into Go value of type []string 
ERRO[0015] HTTP Error                                    err=json: cannot unmarshal string into Go value of type []string statusCode=500
INFO[0309] GET /v1.19/version                           
```

while doing -the same thing- from the cli, I get
```
INFO[0563] POST /v1.19/containers/create                
INFO[0564] POST /v1.19/containers/bc705b29f1295c7868cbc3a379febb6b866db72182e292ea25847e0221186aaf/attach?stderr=1&stdin=1&stdout=1&stream=1 
INFO[0564] POST /v1.19/containers/bc705b29f1295c7868cbc3a379febb6b866db72182e292ea25847e0221186aaf/start 
```

**Comment by apocas** [comment]
This was fixed in https://github.com/apocas/dockerode/pull/147

You are probably doing the same mistake but on your implementation check if you have the option VolumesFrom with a string instead of an array.
