### ISSUE TITLE
Image.push should handle auth config like everything else as an option?

### ISSUE THREAD

**Issue by ekristen** [apocas/dockerode#158]
I think image.push should handle auth just like everything else as an option? Thoughts?

**Comment by apocas** [comment]
It's in master now:  https://github.com/apocas/dockerode/commit/11d196a5e80f0e5bcec45b82c274db9946b33618

Will be published on v2.2.2

For now we will keep supporting separated auth as well just like we did with createImage, but in the next major bump (v3.x) messy auth arguments will be dropped :)

**Comment by ekristen** [comment]
+1 thanks! 

BTW, just in case you see any one complaining. Docker 1.7.0 introduced a bug that doesn't allow private registry authentication to work properly during build to pull the base image.
