### ISSUE TITLE
different image get path in v1.19

### ISSUE THREAD

**Issue by anandkumarpatel** [apocas/dockerode#160]
previous way to get image tar
```
Get a tarball containing all images and tags in a repository
GET /images/(name)/get
```
new way
```
Get a tarball containing all images.
GET /images/get
```

**Comment by rmg** [comment]
@anandkumarpatel do you have any links with background on this?

Both endpoints appear in the docs, but I don't see any references to either of them being the preferred method for exporting an image as a tarball.

 - [/images/(name)/get](https://docs.docker.com/reference/api/docker_remote_api_v1.19/#get-a-tarball-containing-all-images-in-a-repository)
 - [/images/get](https://docs.docker.com/reference/api/docker_remote_api_v1.19/#get-a-tarball-containing-all-images)

There is certainly some overlap, but I don't think one is a replacement for the other.

**Comment by apocas** [comment]
Wow this is messy.
Let's wait and see where this goes.

They are basically the same and even call the same method.

**Comment by anandkumarpatel** [comment]
ahh, I see. I was wondering how `GET /images/(name)/get` got a specific tag. 
with `GET /images/get?names=myname%2Fmyapp%3Alatest&names=busybox`
you can type the tag as `image:tag` but with the `GET /images/(name)/get`  you have to give the image id of the tagged image. 
going to close this issue.
