### ISSUE TITLE
build from github url

### ISSUE THREAD

**Issue by jgallen23** [apocas/dockerode#163]
the docker cli lets you build from a github url.  Like: `docker build https://github.com/user/repo.git`.  Is there any way to do that in dockerode?  Or do I need to manually clone and then build the Dockerfile?

**Comment by rmg** [comment]
@jgallen23 it looks like you just need to pass a `{remote: url}` option, based on the API docs: https://docs.docker.com/reference/api/docker_remote_api_v1.19/#build-image-from-a-dockerfile

**Comment by jgallen23** [comment]
@rmg thanks, worked perfectly!
