### ISSUE TITLE
Dockerode Returning the Image Id with docker.run() 

### ISSUE THREAD

**Issue by agrawalapoorv** [apocas/dockerode#164]
I am creating the docker container , starting the container and then committing it.
How can I use the previous image Id and commit the changes on it.

Can we user the Labels and if How I can do it.

Code:

docker.run('441f9d16e520', ['bash', '-c', 'npm install nodejs -y;npm install fs -y;'], [process.stdout, process.stderr], {Tty:false, Name:'Myapplication'},
function (err, data, container) {
  if(err)
  {console.log(err);}
  console.log ('value for the data is ', data);
  console.log('continerrrr', container);
}).on('container', function (container) {
  container.defaultOptions.start.Binds = ["/tmp:/tmp:rw"];
  container.commit({comment:'commit the container'},function(err,data1){
  container.inspect(function (err1, data2)
    {
      var imageid=data1.Image;
});
    if(err  )
      {
        console.log(err1);
      }
  });
  console.log('second', container);
  return container;
});

**Comment by rmg** [comment]
If you are trying to modify the original image, you can't. Part of how docker works is that images are immutable. That is why when you commit a container you get a new image.

**Comment by agrawalapoorv** [comment]
Okay, thanks rmg. So how can I take the commit image id and use it to make the changes in it and again commit it.

Thanks in Advance.

**Comment by rmg** [comment]
Sorry, I somehow missed that you are using `docker.run()` instead of `docker.createContainer()` -> `container.start()`/`container.exec()` -> `container.commit()`.

**Comment by agrawalapoorv** [comment]
Thank rmg, is it good practice to use docker.run or should we go with the "docker.createContainer() -> container.start()/container.exec() -> container.commit()."

Also can you please let me know how can we get the image id that is commited.

Thanks in advance.

**Comment by rmg** [comment]
`Container#commit` ([src](https://github.com/apocas/dockerode/blob/7a5cb1e2642d8212e6bf4327ad000554ec9a5bdd/lib/container.js#L253-L278)) passes an `Image` instance to the callback, which you can then inspect or get the id of using `.Id`.

Here's an example implementation that might do what you are trying to do: https://github.com/strongloop/strong-docker-build/blob/f85be148aedd18558d3cdd1ced9c5ab6d5df1bc6/lib/image.js#L10-L54

**Comment by agrawalapoorv** [comment]
How can I set the Repository name for the commited image ?

**Comment by rmg** [comment]
@agrawalapoorv have you read through the [Docker Remote API docs](https://docs.docker.com/reference/api/docker_remote_api_v1.19/)? Dockerode is just a wrapper for it and it generally uses the same names, arguments, and return values.

For tagging an image you use:
 - `Image#tag` in [dockerode](https://github.com/apocas/dockerode/blob/7a5cb1e2642d8212e6bf4327ad000554ec9a5bdd/lib/image.js#L106-L130)
 - `POST /images/(name)/tag` using the [Docker remote API](https://docs.docker.com/reference/api/docker_remote_api_v1.19/#tag-an-image-into-a-repository).
