### ISSUE TITLE
Memory leak and thousands of processes spawned

### ISSUE THREAD

**Issue by jshkurti** [apocas/dockerode#166]
This code leaks : 
```js
var async  = require('async');
var Docker = require('dockerode');
var docker = new Docker({socketPath: '/var/run/docker.sock'});

function listContainers() {

  docker.listContainers(function(err, containers) {
    async.each(containers, function(container, next) {
      docker.getContainer(container.Id).stats(function(err, stream) {
        if (err) next (err);
        stream.once('data', function(data) {
          //data = JSON.parse(data.toString());                                                                                                    
          next();
        });
      });
    }, function(err) {
      global.gc();
      console.log((process.memoryUsage().rss / (1024*1024)).toFixed(2) + 'MB');
      setTimeout(listContainers, 100);
    });
  });

}
listContainers();
```
`node --expose-gc app.js`

and thousands of **/usr/bin/docker daemon** appear in htop and stay there even when I kill the script.

![comment2](https://cloud.githubusercontent.com/assets/7647602/9221655/3decb91c-40ec-11e5-9eab-7c5675c97353.png)

I have only one container running which by the way becomes pretty much unresponsive after a few seconds.

Any thoughts on this ? :)

**Comment by jshkurti** [comment]
Nevermind it was my bad.

**Comment by rmg** [comment]
@jshkurti sounds to me like you've found a bug in the docker daemon itself. What version of docker? Have you checked for open issues on docker/docker yet?

**Comment by jshkurti** [comment]
```
$ docker -v
Docker version 1.8.0, build 0d03096
````

**Comment by rmg** [comment]
I did a quick look and there appears to be [a few open issues](https://github.com/docker/docker/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+leak) related to memory and resource leaks in docker itself.

Considering the problem doesn't go away when you kill your node app also pretty strongly suggests it's a docker bug that your use of dockerode is just exposing (resource cleanup when clients disconnect).

To try reproducing it without dockerode, I believe this would be the shell equivalent to what your script is doing:
```
$ docker ps -aq | xargs docker stats
```

**Comment by rmg** [comment]
Oh, also, in your script you are using `stream.once('data' ..`. The `stats` endpoint is a continuous stream of data, so you'll need to do `.on()` instead of `.once()`, otherwise the data will accumulate in a buffer until the buffer is full - which would look like a memory leak.

**Comment by jshkurti** [comment]
Does the stream object have other events than 'data' ? I tried 'end' 'exit' 'close' 'quit' 'disconnect', then exited my docker container but no luck.
I need to know when my container exits.

**Comment by apocas** [comment]
In docker in order to properly wait for a container you should use remote api's wait endpoint, which dockerode implements. 

https://github.com/apocas/dockerode/blob/master/lib/container.js#L411

Example: https://github.com/apocas/dockerode/blob/master/lib/docker.js#L410

**Comment by jshkurti** [comment]
Thanks for the advice. Is there a smiliar way to know when a new container is started ?

**Comment by apocas** [comment]
container.start's callback is fired when the container is started.

Example: https://github.com/apocas/dockerode/blob/master/lib/docker.js#L408

**Comment by apocas** [comment]
Will close this one for now :)
