### ISSUE TITLE
buildImage fails with no error

### ISSUE THREAD

**Issue by christianhuening** [apocas/dockerode#169]
Hi,
I am using dockerode for quite a while now. And everything was fine. All of a sudden my code for creating images doesn't work anymore. Here's my code:
```javascript
var docker = new Docker({host: 'http://<EyesOnly>', port: 5555});
(...)
    // Create tar file containing contents for image
    var tarStream = tar.pack(temp_working_dir);

    // call docker and create image
    docker.buildImage(tarStream, {
        t: req.body.modelname+':latest'
    }, function(error, output) {
        if(error) return res.json(500, err);
        output.pipe(process.stdout, {end: true});
        output.on('end',function(){
          return res.status(200).json('ImageCreated');
        });
    });
```

Is there anything fundamentally flawed in there? 

Up to recently the output from the stream was printed into my console. The Docker Daemon runs Docker 1.7.1 and overall connection works fine. For intance a call to listImages with dockerode works without problems. I can even see that the docke daemon gets the call to build the image and start the untar processes. 

Any ideas would be greatly appreciated! :)

Cheers,
Christian

**Comment by christianhuening** [comment]
Well it seems there is another weird issue. Also this seems to be somewhat related to an error in tar-fs. so I guess this can be closed.

**Comment by apocas** [comment]
:+1:
