### ISSUE TITLE
Add support for promises

### ISSUE THREAD

**Issue by lorenz** [apocas/dockerode#171]
I'd appreciate it if dockerode would support promises as promisification is difficult because of all the prototypes involved.

**Comment by apocas** [comment]
Have you looked into a few modules that already "promisify" dockerode?
Ex: https://www.npmjs.com/package/dockerode-promise

Also: https://github.com/apocas/dockerode/pull/108

**Comment by apocas** [comment]
Just pushed to the repo a promise based interface, check it out :)

**Comment by kjvalencik** [comment]
@apocas This is a breaking change for users that were already promisifying with Bluebird since there is a conflict on the `Async` suffix.

**Comment by apocas** [comment]
runAsync is an internal function I will rename it without consequences,
fixing this.

**Comment by apocas** [comment]
Published.

@ThomWright fixed.
