### ISSUE TITLE
Fails running container on docker 1.8

### ISSUE THREAD

**Issue by fiveisprime** [apocas/dockerode#172]
Fails with the following error on docker 1.8.2 when attempting to run a
container.

    Error: HTTP code is 500 which indicates error: server error - json: cannot unmarshal string into Go value of type int64

I'm guessing that this is a simple fix of passing a Number rather than String, but
I'm not sure where/what or this would be a PR. :+1:

**Comment by rmg** [comment]
Is this the same as #170?

**Comment by fiveisprime** [comment]
It was actually a different issue, but totally my fault. Sorry about that!
