### ISSUE TITLE
Closing stats stream on a container

### ISSUE THREAD

**Issue by blazedd** [apocas/dockerode#179]
When listening to the stats of a single particular container via a stream it's somewhat troublesome to close the stream. The initial request won't return any reference so you're limited to what the stream provides. 

``` javascript
var container = docker.getContainer(id);
container.stats({stream:true}, function(err, stream){
      // to close the stream you need to use a nested method from inside the stream itself
      stream.req.socket.end();
});
```

A nice helper method attached to this to simply make this more accessible would be really nice :)

```
stream.end()
```

**Comment by Seikho** [comment]
These are just [https://nodejs.org/api/stream.html](NodeJS streams).
You can use the undocumented `stream.destroy()` function.
