### ISSUE TITLE
How to just get content from output stream on buildImage

### ISSUE THREAD

**Issue by christianhuening** [apocas/dockerode#180]
Hi,

I am using docker.buildImage and I'd like to use the string content from the output stream. 

Here's my code:
```javascript
docker.buildImage(tarPackageName, {
            t: imageName+':latest'
          }, function(error, output) {

            if(error) return res.json(500,error);

            output.on('data', function(data){
              console.log(data.toString());
            });

            output.on('end',function(){
              res.status(200).json('ImageCreated');
            });
});
```

However the string content from the stream looks like this:
```
{"stream":" ---\u003e Using cache\n"} 
```
Is there any way to just use the content of the "stream" field (e.g.: "Using cache\n")? 
I already tried to call data.stream.toString(). 
I have to admit that I am new to JS Streams. I read the docs, but maybe I am getting something wrong here?

Cheers,
Christian

**Comment by rmg** [comment]
Take a look at the [helper functions](https://github.com/apocas/dockerode#helper-functions). I think one of them should work for what you want to do.

**Comment by christianhuening** [comment]
Thanks! I tried the onProgress callback and tried to use the "event", All I saw printed was "[object Object]". What kind of object is "event" in onProgress?

**Comment by rmg** [comment]
You probably want something like this:

```js
docker.buildImage(tarPackageName, {t: imageName+':latest'}, function(error, output) {
  if(error) return res.json(500,error);
  docker.modem.followProgress(output, function onFinished(err, output) {
    if(error) return res.json(500,error);
    console.log(output); // output is an Array
    res.status(200).json('ImageCreated');
  });
});
```

**Comment by christianhuening** [comment]
Will look into it! Thanks a lot!

**Comment by apocas** [comment]
Can we close this one? :)
