### ISSUE TITLE
pfx key

### ISSUE THREAD

**Issue by jaymedavis** [apocas/dockerode#187]
I've seen some related issues to this, but wasn't sure if it should be a different issue. Instead of passing the ca.pem/cert.pem/key.pem, is it possible to pass a pfx similar to the request library?

Thanks for the library, it rocks.

**Comment by rmg** [comment]
dockerode passes the options straight in to [docker-modem](https://github.com/apocas/docker-modem/blob/master/lib/modem.js). It looks like it isn't supported at the moment but it shouldn't take much to add support for it.

**Comment by jaymedavis** [comment]
thanks - i'll post/take a look over there!
