### ISSUE TITLE
run and detach

### ISSUE THREAD

**Issue by silverbux** [apocas/dockerode#188]
hi guys, what's the equivalent of this command?
```
docker run -itd ubuntu /bin/bash
```
basically i just want to create a container and leave it running, im not sure if its just on my end but every time i create a container it simply stop.

**Comment by rmg** [comment]
`docker run` =~ create, start, attach
`docker run -d` =~ create, start

(Typing on a tablet, hopefully that is clear enough)

**Comment by silverbux** [comment]
cool thanks
