### ISSUE TITLE
Container.start callback invoked before container finished starting

### ISSUE THREAD

**Issue by electricmonk** [apocas/dockerode#191]
When I start a container, the container's execution may have failed and the container may have exited with a non-zero code. For instance, I might start a server that expects a DB connection, but no DB container is alive. In this case, I'd like to pin-point this failure and fail gracefully. 

I'm trying to achieve that by calling `inspect` in the `start` callback function. However, when I start a container, the callback is invoked immediately, so that when `inspect` is called, the `State` is still running. A solution would be to set a short timeout, but that solution is _really_ nasty. 

The same call, using the CLI, behaves as I expect.

Here's a failing test and a passing test using the CLI:
```js

    it("should return only after container startup has completed", function(done) {

      docker.createContainer({
        Image: 'ubuntu',
        Cmd: ['/bin/bash', '-c', 'exit 42'],
        AttachStdout: true,
        AttachStderr: true
      }, function(err, container) {
        if (err) done(err);

        container.start(function() {
          container.inspect(function(err, inspection) {
            if (err) {
              done(err)
            } else {
              expect(inspection.State.Running).to.be.false;
              expect(inspection.State.ExitCode).to.equal(42, "expected exit code to be 42");
              done();
            }
          });
        })
      });
    });

    it("same example as above, using cli", function(done) {
      var exec = require('child_process').exec;
      var child = exec('docker run ubuntu:latest /bin/bash -c "exit 42"');
      child.on('exit', function(code) {
        expect(code).to.equal(42);
        done();
      })
    });
```

**Comment by gsikorski** [comment]
I think I have experienced the same issue, but did not get into details. In my case, some of the containers were left in state "destroyed" and could not be removed. I assume this was because of this issue...

**Comment by rmg** [comment]
I've used `container.attach()` for this type of monitoring. You might be able to use it without actually attaching any streams/descriptors.

**Comment by apocas** [comment]
You are comparing to very different things, which is start and run. There is not such thing as `run` in the Docker  RAPI, `run` is an orchestration of multiple things in cli and dockerode
Check dockerode's `run` source code. https://github.com/apocas/dockerode/blob/master/lib/docker.js#L490

`start`'s callback is called when Docker's Remote API responds to the start request, theoretically it respond after the container started. (it may die after or not this is not relevant to start)

You also have `wait`'s callback which is called after the container stops/dies/...

Using both you can accomplish the use case you described.
You may also try to use dockerode's `run`.

**Comment by electricmonk** [comment]
Well, actually, if I use the two separate `create` and `start` commands from the CLI, I get the same behavior. So it's not just the difference between `start` and `run`.
Not sure `wait` will help me, since I need to be able to fail (a test, for instance) if a container failed to start. It's just that the definition of a "failed" startup is fuzzy.

I can try @rmg's solution but I still claim there's a bug here - Dockerode's violating the principle of least surprise.

Not sure Run helps me, since I don't want to block until the container has stopped - remember, we're talking about a server here.

**Comment by apocas** [comment]
To be honest and if I comprehended what you described correctly, I don't see how can you get that behavior without changing something on Docker.

Never tried @rmg's solution, but from what I know from Docker's source, it may work. But I agree with you that it is nasty'ish :)

**Comment by rmg** [comment]
I think `wait` is a much better option and probably the best match here.

I forgot about it because in my usage I'm actually monitoring long running processes with `attach` and this reminded me of how I detect crashes.

**Comment by rmg** [comment]
The definition for failed to start refers to the container, not the process. The api docs don't specify any status code for "started but exited right away", similar to the `fork()` system call. The only error that would be returned is if there was an error allocating resources to fulfill your request.

**Comment by electricmonk** [comment]
@rmg but how would `wait` behave if I the container I just started is a daemon?
Also, re exit codes, my passing test above proves that calling CLI's `run` (and for that matter, `start`) _does_ return the exit code returned by the container's command.

**Comment by rmg** [comment]
@electricmonk the docker CLI uses wait: https://github.com/docker/docker/blob/master/api/client/run.go#L271
