### ISSUE TITLE
Error: write EPIPE

### ISSUE THREAD

**Issue by apocas** [apocas/dockerode#193]
Some endpoints may not work correctly (intermittently) in some versions of Node (>= 4.1.2).

This is due to: https://github.com/nodejs/node/issues/3803#issuecomment-158253328

Affects Unix socket based connections, direct TCP should not be affected.

**Comment by DaneEveritt** [comment]
Looks like this is being tracked in nodejs/node#3947

**Comment by apocas** [comment]
Node v5.3.0 seems to fix it, can't reproduce it anymore with our test suite.

**Comment by etano** [comment]
I get this error occasionally. Is there a way to catch it and retry?
