### ISSUE TITLE
passing label filters to listContainers

### ISSUE THREAD

**Issue by briceburg** [apocas/dockerode#196]
Passing label key=value filters to listContainers appears to have no effect. I've tried many permutaions, listed below. Each returns the most recent list of containers, regardless of label.

```js
// example
var listOpts = {
    "limit": 12,
    "filters": [{label: {"deploybot-skel": ["AAA"]}}]
  };

docker.listContainers(listOpts, function(err, data){
    if(err) {
      return res.status(500).apiResponse('error fetching recent deployments', err.message);
    }
    res.apiResponse('recent deployments', helpers.makeContainerList(data));
  });
```

permutations w/ same result
``` 
var listOpts = {
    "limit": 12,
    "filters": [{label: {"deploybot-skel": ["AAA"]}}]
  };

var listOpts = {
    "limit": 12,
    "filters": [{label: {"deploybot-skel": "AAA"}}]
  };

var listOpts = {
    "limit": 12,
    "filters": [{label: "deploybot-skel='AAA'"}]
  };


var listOpts = {
    "limit": 12,
    "filters": {label: "deploybot-skel='AAA'"}
  };

// .. and many more
```

command line works:
```sh
$ docker ps -n=12 --filter="label=deploybot-skel=AAA"
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS
```

am I missing the syntax on this one?

Many thanks!

~ Brice

**Comment by briceburg** [comment]
following up:  i enabled debugging on the docker modem and see that `filters` was being passed as an empty object. it's being stripped out. as a workaround, this works:

```js
  var listOpts = {
    "limit": 12,
    "filters": "{\"label\": [\"deploybot\"]}"
  };
```

I used the information from http://stackoverflow.com/questions/28054203/docker-remote-api-filter-exited to piece together the expected input.

will try to submit a PR ASAP.

thanks!

**Comment by apocas** [comment]
Yup unfortunately, there's not much we can do from this side.
Docker expect this to arrive as a string. This affects almost the entire Remote API, not regarding this endoint or dockerode.

dockerode could accept JSON/Object and then magically convert it to string before sending it, but then we could easily break compatibility in future changes and even between endpoints. (there are endpoints with different behaviors)

The idea here is not to mess with the data being sent and received as much as we can, this way we maximize the compatible use cases and future Docker changes.

**Comment by briceburg** [comment]
roger that -- it's a bit unfortunate that querystring is removing the "filters" parameter value. this happens on line 98 of docker-modem: https://github.com/apocas/docker-modem/blob/master/lib/modem.js#L98

I wasn't able to experiment further -- but do see that dockerode uses querystring from npm versus node's querystring [ https://nodejs.org/api/querystring.html ], are they the same?

**Comment by apocas** [comment]
There was a reason for that I can't remember now :/ (and probably nowadays we could use the core one)

But please investigate further! removing code is always a good thing :)
Dropping this module and using querystring from core, is definitely a wanted thing and a good PR :)

**Comment by apocas** [comment]
Published.
https://github.com/apocas/dockerode/pull/204
https://github.com/apocas/docker-modem/pull/59
https://github.com/apocas/docker-modem/pull/58
