### ISSUE TITLE
Unable to pull images from private repository after updating to v2.2.4

### ISSUE THREAD

**Issue by sydcanem** [apocas/dockerode#199]
Hi, seems like there's an issue with versions 2.2.4 and 2.2.6. I downgraded dockerode to 2.2.3 and pulling from private repos seems to work again.

**Comment by ravenscar** [comment]
+1 here

For us we have basic auth on the private repo and I think that for some reason the credentials from the host (where the docker engine is running) aren't being used.

I believe that previously I have seen dockerode give an error similar to this when I had a missing ~/.docker/config.json

from the process using dockerode:

`Error: image auth/get-token:latest not found`

from the repository logs:

    xxx.xxx.xxx.xxx - - [07/Dec/2015:21:55:08 +0000] "GET /v2/ HTTP/1.0" 401 114 "" "docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.13.0-46-generic os/linux arch/amd64"
    xxx.xxx.xxx.xxx - - [07/Dec/2015:21:55:08 +0000] "GET /v1/repositories/auth/get-token/images HTTP/1.0" 404 19 "" "docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.13.0-46-generic os/linux arch/amd64"

After downgrading to v2.2.3 everything works fine.

**Comment by ravenscar** [comment]
After investigating this I think I have found the issue, it seems to be a bug with the way `Docker.prototype.pull` has been changed.

[This commit](https://github.com/apocas/dockerode/commit/6120f57c63515a75e2261e6b6eb7d7a39798749d) changed the behaviour of `Docker.prototype.pull` such that an auth parameter was added (after the callback too, very nasty!!)

This was *probably* unnecessary as you could already set the auth in `opts.authconfig`, so I don't think there was a need for an explicit `auth` parameter.

`Docker.prototype.pull` now sends the auth as the first parameter when calling `Docker.prototype.createImage` irrespective of whether the caller to `Docker.prototype.pull` set it. So there will always be three parameters in `Docker.prototype.pull`'s call to `Docker.prototype.createImage`. 

This breaks the logic within `Docker.prototype.createImage` which assumes that if you have sent the auth parameter explicitly then you probably want to use it.

I don't think this is a problem with `Docker.prototype.createImage` but instead [the commit](https://github.com/apocas/dockerode/commit/6120f57c63515a75e2261e6b6eb7d7a39798749d) should be rolled back as it has broken the functionality for everyone using `opts.authconfig` during pull, and wasn't needed in the first place.

**Comment by apocas** [comment]
Yup you are right, this was introduced in https://github.com/apocas/dockerode/pull/189

Auth is a bit messy, since it was something that grew with dockerode and docker.
This change consequence was totally missed.

Right now I can't just rollback since there may be people already using this "new" schema, I will add a small validation in order to make it work both ways.

More importantly, everything regarding auth will be locked until next major release where it will be heavily refactored.

**Comment by apocas** [comment]
Published v2.2.7
