### ISSUE TITLE
buildImage() without opts arg always fail with TypeError

### ISSUE THREAD

**Issue by dbaba** [apocas/dockerode#201]
I've got TypeError when I call `buildImage()` function with `file` and `callback` args.
In the function, `null` is assigned to the variable (see `(A)`) if a given argument `opts` is a function.
Then, the code tries to access `opts.registryconfig` and `opts.authconfig` though `opts` is `null` (see `(B)` and `(C)`), and finally `TypeError` is thrown.
So need to prepend a condition to evaluate `opts`, e.g. `if(opts && opts.registryconfig) {`

```javascript
Docker.prototype.buildImage = function(file, opts, callback) {
  if (!callback && typeof opts === 'function') {
    callback = opts;
    opts = null; ... (A)
  }

(snip)

  if(opts.registryconfig) { ... (B)
    (snip)
  }

  //undocumented?
  if(opts.authconfig) { ... (C)
    (snip)
  }
(snip)
```

**Comment by rmg** [comment]
Looks like it should be set to `{}` instead of `null`. Might be a good first PR if anyone is looking to contribute :-)

**Comment by apocas** [comment]
@rmg right on the money :)

**Comment by apocas** [comment]
Since I'm prepping a new release and no one grabbed this one, I'm going to grab it myself :)

**Comment by dbaba** [comment]
Thanks. I tried to provide a PR but I got stuck with trouble shooting for a weird issue where npm test never ended on vagrant 1.7.4 + OS X 10.10.5.

**Comment by apocas** [comment]
Interesting that just happened to me too, but I didn't had time to debug it and just ran the test suite on another box.
