### ISSUE TITLE
Feature Request: Add 'docker inspect' results to container start events

### ISSUE THREAD

**Issue by megastef** [apocas/dockerode#202]
In many cases it would be useful to have the complete container information / 'docker inspect' results as data in the container 'start' event:
1. check TTY to parse logs correctly - In my special case it could help to fix https://github.com/mcollina/docker-loghose/issues/4 
2. List of environment variables to know containers setup 
3. Ports exposed (to proxy, route, use ...)

**Comment by rmg** [comment]
I've tended to view this module as a simple wrapper for the Docker remote API.. Perhaps there should be a another module/package that wraps this one to provide a higher level API that does useful things like this?

**Comment by apocas** [comment]
When I created `dockerode` the idea was exactly what @rmg just described.

`dockerode` main focus is to give core functionality bridging `docker` and `nodejs`, this way it opens the possibility to a whole ecosystem of other modules building and abstracting on top of it :)

Giving you an example, this is why `dockerode` doesn't parse the data in streams, it just translates the `docker` protocol and delivers that data where you specify. This way everyone could build whatever they want without restrictions.

Additionally `docker` is changing a lot and very fast, so it would be way better to keep this high level abstraction in a module diferent which would leverage `dockerode`.
