### ISSUE TITLE
Container start options

### ISSUE THREAD

**Issue by FrenchBen** [apocas/dockerode#206]
Why does the `container.prototype.start` allow options, when the API docs do not?
What is the magic?
https://github.com/apocas/dockerode/blob/master/lib/container.js#L159
vs
https://docs.docker.com/engine/reference/api/docker_remote_api_v1.21/#start-a-container

**Comment by apocas** [comment]
Start "used" to accept options :)

The Docker RAPI Docs link you provided also answers this question:
"Note: For backwards compatibility, this endpoint accepts a HostConfig as JSON-encoded request body. See create a container for details."

Once this is really dropped, we will also drop it :)

**Comment by FrenchBen** [comment]
I saw that, but it seems that some of the options passed really end up not working or breaking things. It may be better to remove it all together and prevent confusion.

I saw that you updated the docs to not show start options :+1: ; the next logical step is to remove it all together :D
