### ISSUE TITLE
Stop/remove container on node process exit

### ISSUE THREAD

**Issue by mattfysh** [apocas/dockerode#214]
Is it possible to have a container created and started from dockerode be removed once the same node process is stopped? I'm using signal-exit to call `container.remove({force: true}, ...)` and I can see docker-modem sending the API request, however the daemon continues to run the container after the node process exits. this only happens during SIGTERM when all listeners must execute sync'ly, the remove function works fine otherwise

**Comment by breedx2** [comment]
:+1: would be nice to have this as a built-in.

**Comment by christophetd** [comment]
+1, I am struggling to implement this. 

I am writing a node library maintaining a set of running docker containers, and I need a way to stop them when the script is exited: how to do that since it's not possible to run asynchronous code in an exit handler?

**Comment by apocas** [comment]
Yeah `beforeExit` may help, although I think it does not fire in all conditions.

It may be over killing for your use case, but you can also play with `child_process.fork`, having a "janitor" process cleaning everything up after.
