### ISSUE TITLE
docker.run stdout stream

### ISSUE THREAD

**Issue by Foxprodev** [apocas/dockerode#215]
Hello!
I am using method docker.run from your package.
I've used stream like 

```
  var stdout = new stream.Writable({
      write: function(chunk, encoding, next) {
        console.log(chunk.toString());
        next()
      }
    });
```

It writes only once, process.stdout works properly.
Can u help me with my custom stream implementation?

**Comment by apocas** [comment]
https://github.com/apocas/dockerode/issues/401
