### ISSUE TITLE
Is 'docker volume create' supported?

### ISSUE THREAD

**Issue by greyarch** [apocas/dockerode#216]
Is the functionality described here: 

https://docs.docker.com/engine/reference/commandline/volume_create/

(and other volume related features) supported? If so, how? I cannot seem to find anything about that.

**Comment by apocas** [comment]
You should look into RAPI docs and not CLI.
https://docs.docker.com/engine/reference/api/docker_remote_api_v1.21/#create-a-volume

https://github.com/apocas/dockerode/blob/master/lib/docker.js#L294 - create
https://github.com/apocas/dockerode/blob/master/lib/volume.js - volume

**Comment by apocas** [comment]
also: https://github.com/apocas/dockerode/blob/master/test/docker.js#L331

**Comment by greyarch** [comment]
Ah, I see. Thanks a lot for the swift answers.
