### ISSUE TITLE
typescript support

### ISSUE THREAD

**Issue by Finkes** [apocas/dockerode#217]
Are there any plans to support typescript by providing a .d.ts file? This would be pretty awesome

**Comment by apocas** [comment]
I'm not the biggest fan of intermediate languages (at all), so don't expect it anytime soon at least coming from me :)

But if it is something that is completely optional and maintenance free, I don't see why we couldn't include it.

**Comment by apocas** [comment]
Closing this one for now.
Will reopen it if needed or feedback received :)

**Comment by xxxtonixxx** [comment]
I think it would be a great idea! 👍

**Comment by Seikho** [comment]
FYI I published `@types/dockerode` a while ago. It is missing some features, so contributions are more than welcome.

**Comment by xxxtonixxx** [comment]
Thanks @Seikho for your reply! 😄

**Comment by Rush** [comment]
@types/dockerode seems to be very inconsistent when it comes to the types. I don't think they are very usable. 

```ts
    pull(repoTag: string, options: {}, callback: Callback<any>, auth?: {}): Dockerode.Image;
    pull(repoTag: string, options?: {}): Promise<any>;
```
So how can pull return a Dockerode.Image synchronously and then promise pull returns `Promise<any>` ?
