### ISSUE TITLE
docker run in privileged mode possible?

### ISSUE THREAD

**Issue by iam-peekay** [apocas/dockerode#219]
I am running a kvm based emulator inside my docker container, which requires that I run the image with the --privileged flag. Is it possible to do this with your API module? I tried putting it in CMD argument:

```javascript
docker.run('iampeekay/myImage:v1', ["--privileged", "other commands....."], process.stdout, function (err, data, container) {
  if (err) {
    console.log(err.stack);
  } else {
    console.log(data.StatusCode);
  }
});
```
but it doesn't seem to work.

**Comment by apocas** [comment]
Privileged flag, when using Docker's Remote API (which dockerode uses), should be used on container start and not creation.

You may read more details here: https://github.com/apocas/dockerode/issues/14

Since you are using `run` https://github.com/apocas/dockerode#equivalent-of-docker-run-in-dockerode it should be something like this:
```javascript
docker.run('iampeekay/myImage:v1', ["other commands....."], process.stdout, {}, {Privileged: true}, function (err, data, container) {
  if (err) {
    console.log(err.stack);
  } else {
    console.log(data.StatusCode);
  }
});
```

**Comment by iam-peekay** [comment]
@apocas perfect, thank you!

**Comment by iam-peekay** [comment]
Perhaps you could document the format of the options object? For Insrance,
if I want to expose ports explicitly (ie. -p 8000:5000) when using
Docker.run, how would I do that? Is it another key/value in the options
object? If so, what's the format that you accept?

Thank you.

On Wednesday, February 17, 2016, Pedro Dias <notifications@github.com>
wrote:

> Privileged flag, when using Docker's Remote API (which dockerode uses),
> should be used on container start and not creation.
>
> You may read more details here: #14
> <https://github.com/apocas/dockerode/issues/14>
>
> Since you are using run
> https://github.com/apocas/dockerode#equivalent-of-docker-run-in-dockerode
> it should be something like this:
>
> docker.run('iampeekay/myImage:v1', ["other commands....."], process.stdout, {}, {Privileged: true}, function (err, data, container) {
>   if (err) {
>     console.log(err.stack);
>   } else {
>     console.log(data.StatusCode);
>   }
> });
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apocas/dockerode/issues/219#issuecomment-185514539>.
>


-- 
Preethi Kasireddy
201-895-9299
Twitter <https://twitter.com/iam_preethi>
LinkedIn <https://www.linkedin.com/pub/preethi-kasireddy/28/835/413>
Github <https://github.com/iam-peekay>
Facebook <https://www.facebook.com/preethikasireddy>

**Comment by apocas** [comment]
Forget about "-p" and run, that's CLI usage, you should be looking into API usage (which CLI also consumes). When using dockerode you are basically in a lower layer, think if you were implementing docker's CLI (it is exactly what you are doing).

Dockerode does not mess with the arguments being sent to docker, being this said you should always consult the official docs at https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/

After reading the docs you know if the option you want should be specified at container start or creation. **(docker cli's run and dockerode's run, are an orchestration of create, start and attach from the core API)**

The only thing you must remember from dockerode is the run function parameter order https://github.com/apocas/dockerode#equivalent-of-docker-run-in-dockerode which is:
docker.run(image, parameters, streams, createOptions, startOptions, callback);

**Comment by iam-peekay** [comment]
@apocas thank you.

**Comment by iam-peekay** [comment]
@apocas I tried to do the below following the Remote API docs, but the port bindings do not work. Am I doing something wrong?

```javascript
docker.createContainer({Image: 'iampeekay/myImage:v1', Cmd: [], HostConfig: { PortBindings: { "8000/tcp": [{ "HostPort": "8000" }] }}, name: 'androidEmu'}, function (err, container) {
    container.start({Privileged: true}, function(err, data) {
    if (err) {
      console.log(err.stack);
    } else {
      console.log('started');
    }
  });
});

```

The container starts and is running. However, when i inspect, the port bindings say null:
![image](https://cloud.githubusercontent.com/assets/5421194/13205233/69a6d148-d898-11e5-9440-ee70f475adbc.png)

**Comment by iam-peekay** [comment]
@apocas I figured out how to get it to work. It works if you put in the the container.start method: 

```javascript
docker.createContainer({Image: 'iampeekay/myImage:v1', Cmd: [], name: 'androidEmu'}, function (err, container) {
    container.start({Privileged: true, PortBindings: { "8000/tcp": [{ "HostPort": "8000" }] }}, function(err, data) {
    if (err) {
      console.log(err.stack);
    } else {
      console.log('started');
    }
  });
});
```
![image](https://cloud.githubusercontent.com/assets/5421194/13224343/ecf5d798-d93c-11e5-976f-4242e4ee2aa6.png)

**Comment by anselmobattisti** [comment]
It's an old thread BUT if you be here maybe i can help you!

Now you can't pass string with start method

now you need to pass everything in the createContainer

`
    let createParameters = {}
                createParameters.Image = device.connectionType
                createParameters.Cmd = [device.connectionParameters]
            
                // if there is a physicalPath then add it to Devices options
                // it will mapp the local device inside the container
                if (device.physicalPath) {
                    createParameters.Devices = [{
                      PathOnHost: device.physicalPath,
                      PathInContainer: device.physicalPath,
                      CgroupPermissions: "rwm" 
                    }]
                }
                docker.api()
                    .then((api) => {
                        api.createContainer(createParameters).then(function(container) {
                            container.start()
                            .then((data) => {
                                device.dockerId = data.id
                                device.save()
                                return res.status(201).json(data)
                            })  
            
`
