### ISSUE TITLE
Cannot locate specified Dockerfile: Dockerfile

### ISSUE THREAD

**Issue by wesleygauntt** [apocas/dockerode#220]
Hey all,

Having some trouble when attempting to create an image via docker.buildImage. I have a local .tar file with the following files inside of it (with no subdirectories): Dockerfile, app.js, package.json. Using the following code, I receive an error:

{ [Error: HTTP code is 500 which indicates error: server error - Cannot locate specified Dockerfile: Dockerfile ] reason: 'server error', statusCode: 500, json: null }

``` js
  var tar = tarfile.tar.gz //simplified variable for example
  var docker = new Docker({host: dockerSettings.host, port: dockerSettings.port});
  docker.buildImage(tar, {t: 'test'}, function (err, response){
     if(err)
       console.log('Error building image: ', err);
     return response;
   });
```

Is there a nuance that I've missed in setting up this process? The above code is not using streams, could this potentially be an issue? Might be a quick fix here -- any help is appreciated!

**Comment by pdkovacs** [comment]
Just a blind shot: user permission?

**Comment by apocas** [comment]
Does this test run on your scenario?
https://github.com/apocas/dockerode/blob/master/test/docker.js#L42

If it runs, check the example .tar file.

**Comment by davidskowronski** [comment]
The Dockerfile is case sensitive.  make sure it is not DockerFile or something similar.

**Comment by FlasterDB-Management** [comment]
Same problem also docs are not clear
