### ISSUE TITLE
question regarding responsibility for forming authConfig fields

### ISSUE THREAD

**Issue by dweinstein** [apocas/dockerode#224]
authconfig fields need to be normalized to a specific format, https://docs.docker.com/engine/reference/api/docker_remote_api/#authentication e.g., for use with private registries. To properly mirror what the normal docker client does, we need to make sure authconfig follows that convention.

AFAICT dockerode nor docker-modem currently normalize the authConfig that the client would normally get from `~/.docker/config.json`.

FWIW I wrote a little module to normalize the fields here https://github.com/dweinstein/dockerode-authconfig for another project that uses dockerode. 

If you deem it in the scope of this project, these are the two actionable ideas I have for enhancements:
- update docs of this project to encourage proper construction of the `authconfig` before being passed to dockerode, i.e., link to the link I shared about the format.
- choose to use the dockerode-authconfig module on the input data in dockerode or docker-modem

let me know your thoughts.

**Comment by apocas** [comment]
Old issue, if needed it will be reopened.
