### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by alantrrs** [apocas/dockerode#228]
Noticed there's no CI system to automatically run the tests, it would be very helpful. I can help setting up [CircleCI](https://circleci.com/) if you'd like. Otherwise travis-ci is good too.

**Comment by apocas** [comment]
Yeah I have my own CI.
I was too lazy to setup a fancy CI service in here :)

If it is something maintenance free, feel free to do it, I will happily accept a PR for it :)

**Comment by DinisCruz** [comment]
What about using travisCI?

**Comment by DinisCruz** [comment]
for reference here is .travis.yml file that works

https://github.com/DinisCruz/BSIMM-Graphs-QA/blob/master/.travis.yml

**Comment by franz-josef-kaiser** [comment]
@DinisCruz _28 days later_ … because that movie

**Comment by alantrrs** [comment]
Got started here: https://github.com/alantrrs/dockerode/commit/2e495c8ea8729a57c0f4305874d527d3bdd0aeb4

Need to fix a couple of issues that I think are specific to CircleCI:  
https://circleci.com/gh/alantrrs/dockerode/2

**Comment by apocas** [comment]
https://github.com/apocas/dockerode/blob/master/.travis.yml
