### ISSUE TITLE
Having issues pushing images to GCR

### ISSUE THREAD

**Issue by jkurz** [apocas/dockerode#232]
I have followed the authentication guide here. using a json key file https://cloud.google.com/container-registry/docs/auth

I am getting failures if I pass this into the authconfig object as the password, like desired. Have you ever been able to push to a GCR registry successfully before with authentication?

**Comment by jkurz** [comment]
nevermind I was not passing in the username correctly. Thanks.

**Comment by NolanChan** [comment]
For anyone still having issues with this, you need to stringify your JSON for the password FYI
