### ISSUE TITLE
How do a --link ?

### ISSUE THREAD

**Issue by nlamblin** [apocas/dockerode#233]
Hi,

I need to do a link when I run my container but I don't find how do that. Can you help me please ?

Here is the piece of code in question:

```
'Link': {
   'mongo_db':'mongo'
},
```

**Comment by rawgni** [comment]
`docker.run('ubuntu', ['bash', '-c', 'uname -a'], [process.stdout, process.stderr], {Tty:false}, function (err, data, container) {
  //...
}).on('container', function (container) {
  container.defaultOptions.start.Binds = ["/mongo_db:/mongo:rw"];
});`

**Comment by apocas** [comment]
Links are specified during container creation: https://docs.docker.com/engine/reference/api/docker_remote_api_v1.23/#create-a-container

If you are using docker.run just specify it in creation options object. Or implement your own container lifecycle.
