### ISSUE TITLE
--net with 'Create container' command

### ISSUE THREAD

**Issue by nlamblin** [apocas/dockerode#239]
Hello,

I can't find how to do the "--net" command during a container creation with docker.createContainer(...).

Can you help me please ?
Thank you.

**Comment by yousefamar** [comment]
I don't think `--net` is at create; it's either at run, or more specifically, at start. What you probably want to do is pass `NetworkMode: 'name-of-network'` to options.

**Comment by jpstrikesback** [comment]
Placing this here for posterity. Im not sure if it was ordering the networkmode & links to the top of hostconfig or moving them out of hostconfig that has made it work (I'll figure that out when I get some sleep) but I was able to start a container on my own --net after creating with this config:



``` javascript
let config = {
  'AttachStdin': false,
  'AttachStdout': false,
  'AttachStderr': false,
  'ExposedPorts': {
      '80/tcp': {}
  },
  'Tty': true,
  'OpenStdin': false,
  'StdinOnce': false,
  'Cmd': [
      'npm',
      'start'
  ],
  'Image': image,
  'Volumes': {
    '/var/run/docker.sock': {}
  },
  'WorkingDir': '/usr/src/app',
  'Entrypoint': null,
  'OnBuild': null,
  'Labels': labels,
  'NetworkMode': 'my_net',
  'Binds': [
    '/var/run/docker.sock:/var/run/docker.sock'
  ],
  'Links': ['db:db'],
  'HostConfig': {
    'NetworkMode': 'my_net',
    'Links': ['db:db'],
    'RestartPolicy': { 'Name': 'unless-stopped' },
    'Binds': [
      '/var/run/docker.sock:/var/run/docker.sock'
    ]
  }
}

```

**Comment by jason-kane** [comment]
It must have been a great nap.  I just ran into the same situation; for the benefit of future searches the secret sauce was to bump NetworkMode up next to HostConfig instead of inside it.  The sequence doesn't appear to matter.
