### ISSUE TITLE
Better document Dockerode constructor arguments, by reference to results of 'inspect'

### ISSUE THREAD

**Issue by cefn** [apocas/dockerode#241]
Trying to use dockerode to connect to a docker-machine instance. Without more precise documentation, I can't figure out which of the available keys, certificates and authorities, map to the 'host', 'port', 'cert', 'key' and 'ca' properties of the constructor options object. I may have to resort to trying all possible combinations, unless there's some documentation I've missed.

The machine I'm trying to access is running on docker-machine on OS X and it can be inspected by...

```
var dockermachine = require("dockermachine");
var defaultInspectionPromise = dockermachine.inspect("default");
defaultInspectionPromise.then(function(inspection){ console.log(JSON.stringify(inspection, null , '\t')) })
```

This evaluates to...

```
{
	"ConfigVersion": 3,
	"Driver": {
		"IPAddress": "192.168.99.100",
		"MachineName": "default",
		"SSHUser": "docker",
		"SSHPort": 61744,
		"SSHKeyPath": "/Users/cefn/.docker/machine/machines/default/id_rsa",
		"StorePath": "/Users/cefn/.docker/machine",
		"SwarmMaster": false,
		"SwarmHost": "tcp://0.0.0.0:3376",
		"SwarmDiscovery": "",
		"VBoxManager": {},
		"CPU": 1,
		"Memory": 1024,
		"DiskSize": 20000,
		"Boot2DockerURL": "",
		"Boot2DockerImportVM": "",
		"HostDNSResolver": false,
		"HostOnlyCIDR": "192.168.99.1/24",
		"HostOnlyNicType": "82540EM",
		"HostOnlyPromiscMode": "deny",
		"NoShare": false,
		"DNSProxy": false,
		"NoVTXCheck": false
	},
	"DriverName": "virtualbox",
	"HostOptions": {
		"Driver": "",
		"Memory": 0,
		"Disk": 0,
		"EngineOptions": {
			"ArbitraryFlags": [],
			"Dns": null,
			"GraphDir": "",
			"Env": [],
			"Ipv6": false,
			"InsecureRegistry": [],
			"Labels": [],
			"LogLevel": "",
			"StorageDriver": "",
			"SelinuxEnabled": false,
			"TlsVerify": true,
			"RegistryMirror": [],
			"InstallURL": "https://get.docker.com"
		},
		"SwarmOptions": {
			"IsSwarm": false,
			"Address": "",
			"Discovery": "",
			"Master": false,
			"Host": "tcp://0.0.0.0:3376",
			"Image": "swarm:latest",
			"Strategy": "spread",
			"Heartbeat": 0,
			"Overcommit": 0,
			"ArbitraryFlags": [],
			"Env": null
		},
		"AuthOptions": {
			"CertDir": "/Users/cefn/.docker/machine/certs",
			"CaCertPath": "/Users/cefn/.docker/machine/certs/ca.pem",
			"CaPrivateKeyPath": "/Users/cefn/.docker/machine/certs/ca-key.pem",
			"CaCertRemotePath": "",
			"ServerCertPath": "/Users/cefn/.docker/machine/machines/default/server.pem",
			"ServerKeyPath": "/Users/cefn/.docker/machine/machines/default/server-key.pem",
			"ClientKeyPath": "/Users/cefn/.docker/machine/certs/key.pem",
			"ServerCertRemotePath": "",
			"ServerKeyRemotePath": "",
			"ClientCertPath": "/Users/cefn/.docker/machine/certs/cert.pem",
			"ServerCertSANs": [],
			"StorePath": "/Users/cefn/.docker/machine/machines/default"
		}
	},
	"Name": "default"
}
```

Can anyone identify which arguments in the above, correspond with the example invocation documented at https://www.npmjs.com/package/dockerode like...

```
var docker5 = new Docker({
  host: '192.168.1.10',
  port: process.env.DOCKER_PORT || 2375,
  ca: fs.readFileSync('ca.pem'),
  cert: fs.readFileSync('cert.pem'),
  key: fs.readFileSync('key.pem')
});
```

Can this be documented by reference to the results object from an inspection?

**Comment by apocas** [comment]
Something along these lines:

var docker5 = new Docker({
  host: '127.0.0.1',
  port: 3376,
  ca: fs.readFileSync('/Users/cefn/.docker/machine/certs/ca.pem'),
  cert: fs.readFileSync('/Users/cefn/.docker/machine/certs/cert.pem),
  key: fs.readFileSync('/Users/cefn/.docker/machine/certs/key.pem')
});

**Comment by cefn** [comment]
Understood. From checking data returned from ```docker-machine env default``` I established the following successful way to connect...

var fs = require("fs"),
    dockermachine = require("dockermachine"),
    dockerode = require("dockerode");

var dockerPromise = dockermachine.inspect("default")
    .then(function(info){ //connects to the docker host
        return new dockerode({
            host:info.Driver.IPAddress,
            port:2376,
            ca:fs.readFileSync(info.HostOptions.AuthOptions.CaCertPath),
            cert:fs.readFileSync(info.HostOptions.AuthOptions.ClientCertPath),
            key:fs.readFileSync(info.HostOptions.AuthOptions.ClientKeyPath),
        });
    })
    .then(function(docker){
        //do dockerode operations here
    });

However, I'm a bit mystified how I'm supposed to programmatically acquire the value 2376, given it's not in the inspect results at all.
