### ISSUE TITLE
Name a container with docker.run 

### ISSUE THREAD

**Issue by ilbonte** [apocas/dockerode#242]
Is possible to name a container with the command docker.run (https://github.com/apocas/dockerode/blob/a71aad984aa5dcc81dce2dc440ce78b5776aa9a0/lib/docker.js#L513)? Maybe with the createOptions or startOptions?

**Comment by apocas** [comment]
Just specify it in createOptions.

https://github.com/apocas/dockerode/blob/master/test/docker.js#L403
https://docs.docker.com/engine/reference/api/docker_remote_api_v1.23/#create-a-container
