### ISSUE TITLE
Equivalent to command line docker run

### ISSUE THREAD

**Issue by cefn** [apocas/dockerode#248]
I've been using an invocation like this from the command line to prove that Docker could do what I hoped - spin up a node application isolated in its own container, forwarding ports...

```docker run -it -p 3000:3000 -p 1883:1883 -e DBHOST=$(ifconfig $(route -n get $(docker-machine ip default) | grep interface: | awk '{print $2}') | grep inet | awk '{print $2}') -v /Users/cefn/Documents/code/imagination/git/ifi/impl/releases/keynote/0.1.0:/opt/ifi ifihost bash -c "nodejs /opt/ifi/lib/ifi/app.js"```

...and it works.

This creates a temporary docker container for the execution of a single command, which is tidied up after the command completes execution. Is there any equivalent in the dockerode world? I'm struggling to map the (working) ```docker run``` command to its dockerode equivalent so that I can get a node-based supervisor to provision and unprovision new instances within containers.

I was following this kind of route, but I fear there's a mismatch between what I'm trying to do, and the API I found myself steered towards in the documentation as a substitute for command line ```docker run``` (createContainer)...

```
    var volumes = {};
    volumes["/Users/cefn/Documents/code/imagination/git/ifi/impl/releases/keynote/0.1.0"]="/opt/ifi";

    var publish = {};
    publish["127.0.0.1:3000"] = "3000";

      var opts = {
          Image:"ifihost",
          Cmd:"bash -c 'nodejs /opt/ifi/lib/ifi/app.js'",
          Tty:true,
          Volumes:volumes,
          Publish:publish,
          Rm:true,
          Env:{DBHOST:dbHost}
      };

      return new Promise(function(resolve, reject){
          docker.createContainer(opts, function(err, result){
              if(err) reject(err);
              else resolve(result);
          });
      })
```

I think perhaps I need to separate the container creation from the execution of a command, and hence switch to using create+start in the place of ```run```. However, then I'm puzzled how to re-introduce the proper tidyup after execution completes, where previously this was atomic.

How do the different parts of my original run invocation map to the different parts of the invocations possible through dockerode? What is the recommended way of attacking this problem?

**Comment by apocas** [comment]
Basically you should check https://docs.docker.com/engine/reference/api/docker_remote_api_v1.23/ and see which options you are using apply to container creation and which apply to start.

Then you have two options in order to do this with dockerode, implement you own container lifecycle (create, start, [attach], wait) or just use dockerode's run.
https://github.com/apocas/dockerode#equivalent-of-docker-run-in-dockerode

In https://github.com/apocas/dockerode/blob/master/test/container.js you have multiple examples of container lifecycles.
