### ISSUE TITLE
Sending command to attach

### ISSUE THREAD

**Issue by Xierip** [apocas/dockerode#249]
Hi, if i attach in my console container using [docker attach name] i can send some command to my minecraft server, but how i can send some command using your api?

i trying some:

    container.attach({stdout: true, stream: true}, function (err, stream) {
        stream.write("say Broadcast on chat testing"); // i try write, send and others
    })

is any way to send command to attach? (my start command: docker run -ti -d -p 23333:25565 --name test -v /srv/test:/data xierip/gp-dc)

i using nodejs :)

**Comment by apocas** [comment]
If I understood it right, what you want is to attach with stdin enabled.
Check this example; https://github.com/apocas/dockerode/blob/master/test/container.js#L218

You should also explore container.exec

**Comment by Xierip** [comment]
@apocas  i got problem, i can send command without "{"stream":true,"stdin":true,"stdout":true,"stderr":true}"

`>{"stream":true,"stdin":true,"stdout":true,"stderr":true}say some xd
[17:01:45 INFO]: Unknown command. Type "/help" for help.
>{"stream":true,"stdin":true,"stdout":true,"stderr":true}say some xd
[17:02:40 INFO]: Unknown command. Type "/help" for help.
>{"stream":true,"stdin":true,"stdout":true,"stderr":true}say some xd
[17:03:01 INFO]: Unknown command. Type "/help" for help.
>{"stream":true,"stdin":true,"stdout":true,"stderr":true}say some xd
[17:03:12 INFO]: Unknown command. Type "/help" for help.
>{"stream":true,"stdin":true}say some xd
[17:03:42 INFO]: Unknown command. Type "/help" for help.
>{"stream":true,"stdin":true,"stdout":false,"stderr":true}say some xd
[17:04:43 INFO]: Unknown command. Type "/help" for help.
>{"stream":true,"stdin":true,"stdout":true,"stderr":true}say some xd
[17:05:00 INFO]: Unknown command. Type "/help" for help.` - console

`    var xieServer = new XieServer(1, true);
    xieServer.container.attach({
        stream: true,
        stdin: true,
        stdout: true,
        stderr: true
    }, function handler(err, stream) {

        stream.write("say some xd" + '\n\x04');

    });` - code

**Comment by FabiKl** [comment]
did you found a solution?

**Comment by Xierip** [comment]
> did you found a solution?

nope

**Comment by NoOneHardy** [comment]
Has anybody found a solution yet?
