### ISSUE TITLE
Using dockerode with self-signed certificate chains

### ISSUE THREAD

**Issue by steirico** [apocas/dockerode#251]
This is an information that should be added to the getting started section in the README. It cost me hours to get it working - so I'm happy to share my experience:

This is how to instantiate dockerode with a self-signed certificate chain:
```javascript
docker = new Docker({
	protocol: 'https',
	host: my-docker-host.com, // host name must match the cert's common name
	port: 2376,
	ca: [
		fs.readFileSync('ca.pem'),
		fs.readFileSync('intermediateCA.pem')
	],
	cert: fs.readFileSync('cert.pem'),
	key: fs.readFileSync('key.pem')
});
```
This might also be related to issue #154 

Hopefully this will be helpful for others, too.

**Comment by apocas** [comment]
Hostname must always match the cert's common name, it's a thing related with docker of even dockerode, even if it was a simple web server it must match :)

**Comment by steirico** [comment]
Well, my real issue was not related to the common name. That's obvious and can be found in every SSL/TLS-related howto.

My real problem with the self-signed certificate chain was that the ```ca``` property has to be specified as an array of each and every CA and intermediate CA:
```javascript
	ca: [  // specify the certificate chain as array of the CA and all intermediate CAs
		fs.readFileSync('ca.pem'),
		fs.readFileSync('intermediateCA.pem')
	]
```
Such information can be found anywhere in the net. Furthermore, the common procedure to concatenate the CA and the intermediate CAs into a single file doesn't work here.

I've finally found necessary information in a side note in the node.js docs: https://nodejs.org/api/tls.html#tls_tls_connect_options_callback
