### ISSUE TITLE
Does dockerode support streaming events?

### ISSUE THREAD

**Issue by likema** [apocas/dockerode#254]
I found that  Docker API upports streaming event

https://docs.docker.com/engine/reference/api/docker_remote_api_v1.19/#monitor-docker-s-events

What aoubt dockerode?

**Comment by beverts312** [comment]
Yes dockerode supports streaming events.

Here is an example that logs events:
```
docker.getEvents({}, function (err, data) {
    if(err){
	    console.log(err.message);
    } else {
	    data.on('data', function (chunk) {
		    console.log(JSON.parse(chunk.toString('utf8')));
		});
    } 
});
```

**Comment by likema** [comment]
Thanks. I find that [docker-events](https://github.com/deoxxa/docker-events) base on dockerode make streaming events easily.
