### ISSUE TITLE
Mapping Ports through Dockerode.

### ISSUE THREAD

**Issue by cefn** [apocas/dockerode#257]
I am able to launch containers and map their ports from the CLI. However, the same thing seems impossible through the Remote API.

I must be missing something about how Dockerode passes arguments on to the Remote API. Any suggestions?

I have tried every combination I can think of, and have followed configurations which are reported to work, referring to...

* https://medium.com/@kevanahlquist/docker-remote-api-port-bindings-example-b55bc5194e20#.t9hlxlpsg
* http://stackoverflow.com/questions/20428302/binding-a-port-to-a-host-interface-using-the-rest-api/20429133
* https://groups.google.com/forum/#!searchin/docker-user/port$20redirection/docker-user/aHbNFACcTfs/nLY-oUihEAIJ
* https://github.com/docker/docker/issues/3039

However, I am unable to connect over TCP to my service when launched via dockerode, which IS addressable when launched via docker CLI run.

The CLI version is...

```bash
docker run -it -p 3000:3000 -p 1883:1883 -e DBHOST=$(ifconfig $(route -n get $(docker-machine ip default) | grep interface: | awk '{print $2}') | grep inet | awk '{print $2}') -v /Users/cefn/Documents/code/imagination/git/ifi/impl/releases/keynote/0.1.0:/opt/ifi ifihost bash -c "nodejs /opt/ifi/lib/ifi/app.js"
```

The Remote API version via dockerode, (which reports 'Promise Success' indicating it has launched, and spits out the same service logging to the console as the CLI version), is...

```javascript
var _ = require("lodash"),
    fs = require("fs"),
    os = require("os"),
    dockermachine = require("dockermachine"),
    dockerode = require("dockerode");

var selfIp = _.chain(os.networkInterfaces()).values().flatten().filter(function(val){ return (val.family == 'IPv4' && val.internal == false); }).map("address").first().value();

//var dbHost = selfIp;
var dbHost = "192.168.99.1";

var createOptions = {
    Image:"ifihost",
    Tty:true,
    ExposedPorts: {
        "3000/tcp:": {},
        "1883/tcp:": {}
    },
    Env:[
        "DBHOST=" + dbHost,
    ],
    Cmd:[
        "/bin/bash", "-c", "nodejs /opt/ifi/lib/ifi/app.js"
    ],
    HostConfig:{
        Binds: ["/Users/cefn/Documents/code/imagination/git/ifi/impl/releases/keynote/0.1.0:/opt/ifi"],
    },
};

var startOptions = {
    PortBindings: {
        "3000/tcp": [{
            "HostIP":"0.0.0.0",
            "HostPort": "3000"
        }],
        "1883/tcp": [{
            "HostIP":"0.0.0.0",
            "HostPort": "1883"
        }],
    },
};

var dockerPromise = dockermachine.inspect("default")
    .then(function(info){ //connects to the docker host
        var docker = new dockerode({
            host:info.Driver.IPAddress,
            port:2376,
            ca:fs.readFileSync(info.HostOptions.AuthOptions.CaCertPath),
            cert:fs.readFileSync(info.HostOptions.AuthOptions.ClientCertPath),
            key:fs.readFileSync(info.HostOptions.AuthOptions.ClientKeyPath),
        });
        return docker;
    })
    .then(function(docker){

        //brings up a new docker guest
        var creationPromise = new Promise(function(resolve, reject){
            docker.createContainer(createOptions, function(err, result){
                if(err) reject(err);
                else resolve(docker.getContainer(result.id));
            });
        });

        var streamPromise = creationPromise.then(function(container){
            container.attach({stream: true, stdout: true, stderr: true}, function (err, stream) {
                stream.pipe(process.stdout);
            });
        });

        var executionPromise = creationPromise.then(function(container){
            return new Promise(function(resolve, reject){
                container.start(startOptions, function(err, data){
                    if(err) reject(err);
                    else resolve(data);
                });
            });
        });

        return executionPromise;

    })
    .then(function(result){
        console.log("Promise Success");
    })
    .catch(function(err){
        console.log("Promise Failure");
    });
```

I have looked at the detail of the [Go schema spec for the Remote API](https://godoc.org/github.com/docker/engine-api) and I should even be able to pass PortBindings through on container create in the HostConfig value I believe, but this doesn't work either, so I've resorted to separating the create config and the start config as indicated in the various issues linked above.

In each case, when I try to connect to the dockerode-launched version it reports like this...

```bash
$ mosquitto_sub -h 192.168.99.100 -t '#' -v
Error: Connection refused
```

...where the container launched using docker CLI run allows mosquitto to connect properly with exactly the same invocation (mosquitto implicitly uses port 1883 as default MQTT port).

**Comment by cefn** [comment]
Any suggestions how the ```-p 1883:1883``` differs from the Dockerode equivalent PortBindings and ExposedPorts invocation above to try and open the same ports? 

The CLI version works, the Dockerode version doesn't, with the same Docker host (Docker Machine on OS X). 

A simplified test case demonstrating the same problem is also now provided at...
https://github.com/docker/docker/issues/23432

**Comment by cefn** [comment]
@apocas is the simplified test case at https://github.com/docker/docker/issues/23432 adequate to examine this question? 

Any idea where else I can look for an answer?

This is currently a blocker to any progress on the project, unless I resort to wrapping BASH calls from Node calling run from an imaginary 'command line' which looks like it might be the only way to do this simple task. 

However, I am more concerned that without knowing how and where to get these arguments right, that I will be unable to achieve anything with dockerode or the Docker Remote API in the future, which will mean future blockers.

**Comment by ekkis** [comment]
cefn, the docs suck and it has taken me a long time to figure out what works.  if I'm not wrong the `.start()` method no longer takes options... they were deprecated some time ago, so I pass the information in the options to create the container like this:  `.createContainer({HostConfig: {PortBindings: {'7474/tcp': [{ HostPort: '7474' }]}}})` and that seems to work for me.  incidentally, it seems you're running boot2docker, which uses VirtualBox to run the host.  I'd recommend you upgrade to the new native client (Docker-for-Mac, in my case).  it's much better and you no longer have to fetch the IP address of the host machine but rather use `localhost` for your clients to connect to.  one other thing, if you use Bluebird, you can do things like: `var createContainer = Bluebird.promisify(docker.createContainer, {context: docker});` and then use it like this: `createContainer(...).then(function(o) { // o is your container; })` which is much nicer

**Comment by cefn** [comment]
Cruelly there was a colon the wrong side of the inverted commas in the ExposedPorts property map...

See https://github.com/docker/docker/issues/23432#issuecomment-228842172

Thanks for the Bluebird tips. I tried to promisify before seeing your example and gave up, so now I have clear guidance to try again.

Also thanks for the Docker-for-Mac suggestion. I am considering using docker-machine everywhere so that there is a consistency between testing on development machines, final deployment, and even potential for expansion to the cloud without having to refactor any code (the compute- and memory-intensive bit is inside a docker machine, so the node front end can service multiple hosts distributed anywhere without doing extra work assuming I treat all hosts as remote from the get go.

Brilliant help on lots of fronts, even if my original bug was a stupid but hard-to-spot copy-paste error.
