### ISSUE TITLE
unable to connect to local socket

### ISSUE THREAD

**Issue by Markcial** [apocas/dockerode#260]
I am currently trying to write a client that queries the socket locally but it ends querying localhost instead the socket, did i miss something? i have tried the settings for the local socket but i got no luck, thanks.

**Comment by apocas** [comment]
Probably something is wrong in your dockerode's initialization options, could you please paste them?

**Comment by Markcial** [comment]
I have been fiddling a little bit around, and seems to be that the webpack module loaders mess around with dockerode, i isolated the sample with node and it worked fine. I will dig a little bit more so i can broaden the insights, but seems to be something with the babel loader and webpack.

FYI the setup is a babel transpiled es6 via webpack to a electron application. When i tried the dockerode client it tried to do requests via http instead of via the unix socket, but seems to be that is getting a fallback to the http request because the socket connection is forbidden in some way, (maybe the child_process?)

I will dig a little bit more and report it back, thanks for your quick reply.

**Comment by Markcial** [comment]
Sorry for the late response, i ended unable to find why it uses the localhost instead of the local socket, it might be because the filesystem is not available in electron, i used the remote library bundled in the electron api and it all worked fine, i am sorry to bother you with an issue that have been caused mainly by my own misunderstanding of the electron architecture.

My apologies and thanks for this cool library i managed to get an application to visualize containers and networks with ease once i solved that configuration perk.

keep on that good work!!

**Comment by codexp** [comment]
@Markcial how did you solve that?
I have the same problem and I can't make it work.

**Comment by Markcial** [comment]
sorry for the late response, difficult dates.

The thing i remember is that the dockerode library only works on the "backend" part of electron. That means that if you try to call it on the renderer side it will be unable to get to the docker daemon.

So be careful to be using it via ipc calls and not on the same end where you put the client side javascript files.
