### ISSUE TITLE
Dockerode creates parse error

### ISSUE THREAD

**Issue by aft2d** [apocas/dockerode#262]
Um running the following code, the get a list of the running containers:

```
var dockerode = require("dockerode");
var dockerode = new dockerode({host: '192.168.99.100', port: 2376})

dockerode.listContainers(function (err, containers) {
    if(!err) {
        containers.forEach(function (containerInfo) {
            console.log(containerInfo);
        });
    } else {
        console.log(err);
    }
});
```

Every time i execute the code, i get the following error:
`{ [Error: Parse Error] bytesParsed: 0, code: 'HPE_INVALID_CONSTANT' }`

Im running docker v1.11.2 with API version 1.23 on macOS. 
The docker-machine is reachable and also any other features work as they should.
Is this a bug or a feature? :D

**Comment by emilkje** [comment]
Did you resolve this issue? I've encountered the same problem on Windows 10.

**Comment by pcsusantha** [comment]
I resolve the same issue via providing proper certs for my docker machine, Please refer this link for detail.
https://github.com/apocas/dockerode/issues/100#issuecomment-59598714 good loop
