### ISSUE TITLE
--name?

### ISSUE THREAD

**Issue by ekkis** [apocas/dockerode#264]
the `.run()` method in this module is not very much like the docker run command.  I have a command like this:

`docker run -d -p 7474:7474 --name AppStore --env NEO4J_NO_AUTH=true --volume ~/db:/data neo4j:2.3
`

how do I express that in this module?

**Comment by apocas** [comment]
https://github.com/apocas/dockerode/issues/103

Just specify the name in the createOptions of run, since Docker's RAPI accepts name in container creation.
