### ISSUE TITLE
Environment variables - how to pass

### ISSUE THREAD

**Issue by ekkis** [apocas/dockerode#266]
I guess I really just don't get how this stuff is supposed to work.  the docs really don't help.  the code below is spewing:

> { [Error: (HTTP code 500) server error - json: cannot unmarshal object into Go value of type string ]
>   reason: 'server error',
>   statusCode: 500,
>   json: { message: 'json: cannot unmarshal object into Go value of type string' } }
> 

what am I doing wrong?

```
var Docker = require('dockbrode');
var d = new Docker();
d.createContainer({
    name: 'AppStore',
    Image: 'neo4j:2.3', 
    Env: [{NEO4J_NO_AUTH: true}],
}, function(err, container) {
    if (err) return console.log(err);
    container.start({}, function(err, data) {
        container.wait(function(err, data) {
            if (err) return console.log(err);
            console.log(data);
        }); 
    }); 
});
```

**Comment by apocas** [comment]
https://github.com/apocas/dockerode/issues/130
