### ISSUE TITLE
Restart container very slow

### ISSUE THREAD

**Issue by copywrite** [apocas/dockerode#268]
Hi Dias

Recently i'm using dockerode with thunkify.

The container.restart()  api behaviors a little weird.

On most containers it returns instantly.

On one container it always hungs until timeout.

When I break the restart action into 3 steps:
1. stop container
2. wait container
3. start container

Then everything goes fine.

Hope you could give me some advices.

Thanks

**Comment by apocas** [comment]
I have seen this behavior before but never found what was happening, at the time I did the same workaround :)
You have the same behavior in the CLI right?

**Comment by copywrite** [comment]
In the CLI everything works smoothly.

What's more, The container.exec API cannot work under thunkify, looks like there is some problem with the new Exec(...) in container.js line 290

**Comment by EugeneKostrikov** [comment]
Spent half a day trying to find the problem in my code. Getting same issue, workaround helps. Thanks!

**Comment by iMoses** [comment]
I'm experiencing a similar issue, only with the list containers method.
In most cases it returns instantly, once in a while (couldn't pin down when exactly, it's inconsistent) it just hangs until timeout.
Unfortunately the workaround here won't work in my case.
Does anyone have an idea what can be causing such issues or what can be done to fix it?
This is very puzzling for me...

**Comment by copywrite** [comment]
@iMoses how many containers are there in your docker host？

**Comment by iMoses** [comment]
@copywrite Just one. My process is building an image, then verifying that a container with the same name doesn't exists (that's when I list the containers), then I start the container.
The containers are defined to remove themselves on stop, so basically there's always between 0-1 containers running on my hosts.

**Comment by apocas** [comment]
Nowadays you can just use the `t` parameter in container.restart to specify a timeout, if that timeout is reached it will kill the container.

https://docs.docker.com/engine/api/v1.33/#operation/ContainerRestart
https://github.com/docker/cli/blob/master/cli/command/container/restart.go
