### ISSUE TITLE
Support for docker deploy / DAB

### ISSUE THREAD

**Issue by Toflar** [apocas/dockerode#270]
Hi Pedro,

First things first: Thank you for this great library, I really enjoy using it!
This here is rather just a question because I'm interested in your opinion.

I'm trying out the new 1.12 features and I wanted to deploy a service from my `.dab` file. I checked the Docker Remote API and then found that there is no API endpoint for that. The `$ docker deploy` command is handling multiple api calls to create or update the networks and then create or update the services. You can finde more info in the [respective command](https://github.com/docker/docker/blob/master/api/client/stack/deploy.go) written in Go.

To be honest, I would prefer Docker to have its own endpoint supporting the whole contents of a `.dab` file. Otherwise every library in all the different programming languages has to reimplement (and maintain) the stuff they add or remove from the `.dab` file.
Do you by chance know if there's some discussion going on regarding this or if they do not plan to provide such an endpoint, do you think `dockerode` should support that or does `dockerode` only provide the same API endpoints as the Docker Remote API without any helpers?

**Comment by apocas** [comment]
Humm if `deploy` is an orchestration of multiple endpoints, theoretically we can implement it.
Just like dockerode's `run`

**Comment by Toflar** [comment]
Sounds cool!

**Comment by faddat** [comment]
Just one of many reasons why I feel that currently it makes far more sense to stick with swarm instead of implementing swarm kit in your pages.  Now, as for this module, yes I also can't wait for a full implementation of swarm kit, and the orchestration described sounds great.  

Thanks for this module, really.  It is the bees knees.

**Comment by dinana** [comment]
I just found this too and it is indeed great, thanks for all the effort. If we can get Docker stack support and deployment from YAML files it would be a great addition to from the 1.13 release of docker.

Is there a plan for the rest of the 1.13 new features as well? (df, prune, etc..)
