### ISSUE TITLE
Streaming into file always leaves weird characters

### ISSUE THREAD

**Issue by etano** [apocas/dockerode#271]
Could someone please explain why when I stream directly into a file, there are always insertions of funny characters. For example, I do the following:

```
    // Create container
    var run_work_dir = '/input';
    var container = yield create_container({
        Image: executable.path,
        Cmd: [run_work_dir+'/'+path.basename(in_file)],
        Volumes: {run_work_dir: {}}
    });

    // Create stream from container to out_file
    console.log('attaching stream...');
    var stream = yield container.attachAsync({
        stream: true,
        stdout: true,
        stderr: false
    });
    stream.setEncoding('ascii');
    var out_stream = fs.createWriteStream(out_file);
    stream.pipe(out_stream);
```

and the out_file always has:

```
    ^A^@^@^@^@^@^Kh
```

in the front

**Comment by apocas** [comment]
My guess is those weird characters are the Docker stream control bytes.

Remove the setEncoding  and use stream demuxing. Something like this:
`
    // Create container
    var run_work_dir = '/input';
    var container = yield create_container({
        Image: executable.path,
        Cmd: [run_work_dir+'/'+path.basename(in_file)],
        Volumes: {run_work_dir: {}}
    });

    // Create stream from container to out_file
    console.log('attaching stream...');
    var stream = yield container.attachAsync({
        stream: true,
        stdout: true,
        stderr: false
    });
    var out_stream = fs.createWriteStream(out_file);
    container.modem.demuxStream(stream, out_stream, out_stream);
`

This should work. If not set the `stderr: false` to `true` and pingback :)

**Comment by kilianc** [comment]
@apocas having the same problem, but using `demuxStream` doesn't seem to help.
In my case I ma doing:

```js
  const containerLogsStream = (yield (done) => container.logs({
    follow: true,
    stdout: true,
    stderr: true
  }, done))

  container.modem.demuxStream(containerLogsStream, logFileStream, logFileStream)
  containerLogsStream.pipe(split()).on('data', (line) => debug(`> ${line.slice(8)}`))
```

**Comment by kilianc** [comment]
```js
exports.getContainerLogsStream = function * getContainerLogsStream (container) {
  const containerLogsStream = yield (done) => container.logs({
    follow: true,
    stdout: true,
    stderr: true
  }, done)

  const mergedContainerLogsStream = through2()
  container.modem.demuxStream(containerLogsStream, mergedContainerLogsStream, mergedContainerLogsStream)

  return mergedContainerLogsStream
}
```

This is how I solved :) I hope it helps you @etano
