### ISSUE TITLE
New Docker v. 1.12.0 deprecated HostConfig

### ISSUE THREAD

**Issue by chipironcin** [apocas/dockerode#273]
Docker updated today (8 hours ago) its tool to v.1.12.0.
Now I am getting the following error with Dockerode

    The process failed: err=Error: (HTTP code 400) unexpected
    - starting container with HostConfig was deprecated since v1.10 and removed in v1.12  
    StatusCode=undefined

Dockerode should deprecate it too to support latest Docker version.

**Comment by andresmgot** [comment]
+1

**Comment by apocas** [comment]
v2.3.0 published :)

**Comment by cokron** [comment]
+1

**Comment by apocas** [comment]
There's no HostConfig enforced in dockerode, tests run in 1.12.x.
Check: https://github.com/apocas/dockerode/issues/279

**Comment by nuest** [comment]
@apocas I ran into the same issue today, probably out of ignorance.

I used https://github.com/apocas/dockerode/wiki/Example-JSON as an orientation, but that example seems outdated.

It would be great if you could extend test, examples or documentation with more information about what and how to put things into either start options or create options.

Based on https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#start-a-container and https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#create-a-container, the start options are not used by the docker runtime API.

**Comment by nuest** [comment]
@apocas Do you have time to take a look at this? I am desperate to find a working configuration of mounting a host directory into a container when using `docker.run`. My current code is at https://github.com/o2r-project/o2r-muncher/blob/master/lib/uploader-steps.js#L182
