### ISSUE TITLE
listServices and listTasks should accept opts

### ISSUE THREAD

**Issue by ypjin** [apocas/dockerode#274]
Thanks for catching up docker 1.12 features so quickly! We're trying to use this module in a project and it works well. Just one comment:
According to docker remote API 1.24 defintions, /services and /tasks APIs accept query parameters (https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/list-services, https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/list-tasks). So the listServices and listTasks functions should accept opts object to support it. 

Best regards,

**Comment by apocas** [comment]
Just published v2.3.0 where this is fixed :)

**Comment by ypjin** [comment]
Great to have 2.3.0! Nice job!
