### ISSUE TITLE
Can't start container (support docker@1.12)

### ISSUE THREAD

**Issue by ypanyukov** [apocas/dockerode#276]
Starting container with HostConfig was deprecated since v1.10 and removed in v1.12

**Comment by apocas** [comment]
You shouldn't specify hostconfig options if you are using v1.12 :)
dockerode does not enforce this.

**Comment by ypanyukov** [comment]
Yes, you are right. Thanks. How I can attach volume/directory now then?

**Comment by ypanyukov** [comment]
Thank you a lot! My fault
