### ISSUE TITLE
Unable to start container

### ISSUE THREAD

**Issue by oliversalzburg** [apocas/dockerode#278]
When attempting to start the container, I get the error

> starting container with HostConfig was deprecated since v1.10 and removed in v1.12

Which refers to https://docs.docker.com/engine/deprecated/#/hostconfig-at-api-container-start. dockerode seems to use this endpoint at https://github.com/apocas/dockerode/blob/master/lib/container.js#L190

**Comment by oliversalzburg** [comment]
I'm getting the feeling that the cause of the issue is actually in https://github.com/Strider-CD/strider-docker-runner :P

**Comment by apocas** [comment]
Indeed :)
https://github.com/apocas/dockerode/issues/276

**Comment by freefood89** [comment]
for those who are stuck.. you need both PortBindings and ExposedPorts

```javascript
docker.createContainer({
	Image: 'test',
	Cmd: [],
	Tty: false,
	Env: [
		"foo=bar"
	],
	ExposedPorts: {
		'5000/tcp': {}
	},
	HostConfig: {
		PortBindings: {
			'5000/tcp': [{HostPort: "5000"}]
		}
	}
}, (err, container) => {
    do stuff
});
```

**Comment by RobertLowe** [comment]
@freefood89 you are my hero 👍
