### ISSUE TITLE
`.run` is using obsolete API. Error: (HTTP code 400) unexpected - starting container with HostConfig was deprecated since v1.10 and removed in v1.12

### ISSUE THREAD

**Issue by lope** [apocas/dockerode#279]
I did a search and found the issue reported in a different github project
https://github.com/hyperledger/fabric/issues/2044
fixed here:
https://github.com/hyperledger/fabric/pull/2263

Apparently hostconfig must be specified during create, not run.

I've tested .create, it works.

**Comment by apocas** [comment]
dockerode does not enforce this :)
https://github.com/apocas/dockerode/blob/master/lib/docker.js#L642
But there are many users using startoptions in dockerode's run.

Also check run's tests, they are passing in v1.12.
https://github.com/apocas/dockerode/blob/master/test/docker.js#L254

**Comment by lope** [comment]
Hi @apocas thanks for the reply and clarifying :+1: 

I'm happy that I have reported this issue so that if someone else experiences it, they can find the solution quickly :)

**Comment by reinvantveer** [comment]
:+1:
