### ISSUE TITLE
PortBindings problem

### ISSUE THREAD

**Issue by RicoswLive** [apocas/dockerode#282]
Hello dockerode and dockerode Community,
my problem is that I can't bind any ports I don't know why it's not working.
I have already searched for this problem I have tested it but it doesn't work for me.
This is the code that I use:
```javascript
app.post(basePath + ':serverId/create/:image', function (req, res) {
  var image = req.params.image;

  var dockerConfig = {
    Image: image,
    name: 'cloudme-test2',
    ExposedPorts: {
      "25565/tcp": {},
    },
    Cmd:[
      "/bin/bash", "-c", "echo Working"
    ],
    PortBindings: {
      "25565/tcp": [{
        "HostPort": "25565"
      }],
    }
  };
  //TODO CHECK IF PORT IS ALREADY USED
  docker.createContainer(dockerConfig, function (err, container) {
    if(err) {
      res.send(JSON.parse('{"sucess": false, "error": "' + err +'"}'));
      return;
    }
    var createServer = new ServerSchema({
      "id": req.params.serverId,
      "ip": config.host,
      "hostPort": 25565,
      "containerPort": 25565,
      "status": getStatus(container.id),
      "image": req.params.image,
      "containerId": container.id
    });
    createServer.save();



    res.send(JSON.parse('{"sucess": true, "ip": "' + config.host +'", "port": "' + port +'", "image": "' + req.params.image +'"}'));
  });

  /*var createServer = new ServerSchema({
    "id": req.params.serverId,
    "ip": config.host,
    "hostPort": port,
    "containerPort": 25565,
    "status": "OFFLINE",
    "image": req.params.image,
    "containerId": containerId
  });
  createServer.save();



  res.send(JSON.parse('{"sucess": true, "ip": "' + config.host +'", "port": "' + port +'", "image": "' + req.params.image +'"}'));*/
});
```

```
root@ricovm:~# docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
03a1d2755056        ubuntu              "/bin/bash -c 'echo W"   49 minutes ago      Created                                 cloudme-test2
```

I don't have any idea why it not working.

Docker Version:
```
root@ricovm:~# docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64
```

**Comment by witwave** [comment]
you should start the container after you create the container.

**Comment by RicoswLive** [comment]
THANKS!!!

**Comment by Houtheyfa** [comment]
var Docker = require('dockerode');

var docker = new Docker({
  socketPath: '/var/run/docker.sock'
});

// mysql container
var client_id = 'CL01';

var mysql = {
    Image: 'mysql',
    name: client_id + "_mysql",
    Env: [
      "MYSQL_ROOT_PASSWORD=toor"  
    ],
    AttachStdin: true,
    AttachStdout: true,
    AttachStderr: true,
    OpenStdin: true,
    StdinOnce: false,
    Tty: true,
    RestartPolicy: {
        Name: 'always',
        MaximumRetryCount: 0
        },
    Labels: {
        "Owner_id": 'CL451',
        "Owner_name": 'Doufa'
    },
    Volumes: {
        '/var/lib/mysql': {}
    }
};

var phpmyadmin = {
    Image: 'phpmyadmin/phpmyadmin',
    name: client_id + '_phpmyadmin',
    ExposedPorts: { "80/tcp": {}},
    PortBindings: {"80/tcp": [{"HostPort": "8080", "HostIp":"0.0.0.0"}]},
    HostConfig: {
         Links: ["/"+client_id+"_mysql:/"+client_id+"_db"]
    },
    RestartPolicy: {
        Name: 'always',
        MaximumRetryCount: 0
        },
    Labels: {
        "Owner_id": 'CL451',
        "Owner_name": 'Doufa'
    }
};
    

docker.createContainer(mysql, function(err, con){
        con.start({},
            function(err,data){
            if(!err)
                console.log( con + ':\t' + data );
            // run phpmyadmin
            docker.createContainer(phpmyadmin, function(err, con){
                con.start(  {},
                    function(err,data){
                        if(err) console.error(err);
                    else console.log(con.toString()+':\t'+data);
                    });
                });    
        });
});

![selection_009](https://cloud.githubusercontent.com/assets/17686749/17839287/1d7693e0-67e4-11e6-8101-ec1fd05f457c.png)


i am facing the same problem too. the port binding is not working.

**Comment by Seikho** [comment]
@Houtheyfa, Your `PortBindings` and `RestartPolicy` should be inside the `HostConfig` property:

```js
var phpmyadmin = {
    Image: 'phpmyadmin/phpmyadmin',
    name: client_id + '_phpmyadmin',
    ExposedPorts: { "80/tcp": {} },
    HostConfig: {
        PortBindings: { "80/tcp": [{ "HostPort": "8080", "HostIp": "0.0.0.0" }] },
        Links: ["/" + client_id + "_mysql:/" + client_id + "_db"],
        RestartPolicy: {
            Name: 'always',
            MaximumRetryCount: 0
        },
    },
    Labels: {
        "Owner_id": 'CL451',
        "Owner_name": 'Doufa'
    }
};
```

**Comment by Houtheyfa** [comment]
aah i didn't pay attention to it. thanks a lot @Seikho :+1:
