### ISSUE TITLE
Unable to create a  container when specifying Host-config  parameters 

### ISSUE THREAD

**Issue by Houtheyfa** [apocas/dockerode#286]
i would like to link tow containers, when i specify the HostConfig Links parameter; the container won't be created and when i remove that line it works.
i've tested it with the other HostConfig parameters and none worked. only if i leave it empty. " HostConfig : {} " 

anyone can help me with this ?!

**Comment by Seikho** [comment]
Can you provide the config object you're trying to use?

**Comment by Houtheyfa** [comment]
var Docker = require('dockerode');

var docker = new Docker({
  socketPath: '/var/run/docker.sock'
});

// mysql container
docker.createContainer({
    Image: 'mysql',
    Names: "mysq",
    Cmd: ['bash'],
    AttachStdin: true,
    AttachStdout: true,
    AttachStderr:true,
    OpenStdin: true,
    StdinOnce: false,
    Tty: true,
    RestartPolicy: {
        Name: 'always',
        MaximumRetryCount: 0
        },
    Labels: {
        "Owner_id": 'CL451',
        "Owner_name": 'Doufa'
    },
    Volumes: {
        '/stuff': {}
    },
    WorkingDir: '/stuff'
}, function(err, con){
        con.start(function(err,data){
            if(err)
                console.error(err);
        });
});

 docker.createContainer({
    Image: 'phpmyadmin/phpmyadmin',
    Name: 'phpmyadmin',
    Cmd: ['bash'],
    AttachStdin: true,
    AttachStdout: true,
    AttachStderr:true,
    OpenStdin: true,
    StdinOnce: false,
    Tty: true,
    **HostConfig: {
         Links: ["mysql:db"]
    },**
    RestartPolicy: {
        Name: 'always',
        MaximumRetryCount: 0
        },
    Labels: {
        "Owner_id": 'CL451',
        "Owner_name": 'Doufa'
    }
}, function(err, con){
       con.start(
        function(err,data){
            if(err)
                console.error(err);
            else
                console.log(con);
       });
});

**Comment by Houtheyfa** [comment]
probably the issue was with the dockerode  i have had. i just removed it and reinstall it & it worked.
