### ISSUE TITLE
How to connect a network interface from within a running container by using /var/run/docker.sock

### ISSUE THREAD

**Issue by stylixboom** [apocas/dockerode#288]
I'm not sure how can I use dockerode to connect a network interface from within the running container.

Since, there is no document about this.
However, currently, I do it like this (follow what exist in the network.js under the test dir).

```
var Docker = require('dockerode');
var docker = new Docker({ socketPath: '/var/run/docker.sock' });

var container = docker.getContainer(con_id);
var network = docker.getNetwork(net_id);

// container.inspect() and network.inspect() work fine, and show me correct information.
```

Then I run network.connect() which shows me the following error

**Problem**
```
network.connect({
    Container: container
}, function (err, data) {
    console.log(data);
});

{ Error: (HTTP code 500) server error - json: cannot unmarshal object into Go value of type string
    at /param_daemon/client/node_modules/docker-modem/lib/modem.js:229:17
    at getCause (/param_daemon/client/node_modules/docker-modem/lib/modem.js:259:7)
    at Modem.buildPayload (/param_daemon/client/node_modules/docker-modem/lib/modem.js:228:5)
    at IncomingMessage.<anonymous> (/param_daemon/client/node_modules/docker-modem/lib/modem.js:204:14)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  reason: 'server error',
  statusCode: 500,
  json: { message: 'json: cannot unmarshal object into Go value of type string' } }
```

**Question**
Usually, I can connect a network interface from both
Docker CLI
```
$docker network connect net_id con_id
```
and Docker remote API
```
curl -s -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"Container":con_id}' 'http://host_ip:2375/networks/net_id/connect'
```
But I'm not sure how can I do it correctly with `dockerode`.

**Comment by stylixboom** [comment]
So, I found this following code work fine, with container.id, instead of just using a container.

**Solution**
```
network.connect({
    Container: container.id
}, function (err, data) {
    console.log(data);
});
```

**Comment by stylixboom** [comment]
BTW, just to mention here.

It seemed the above code works with Docker 1.12.1 (final)(August 18).

When I run it with **Docker 1.12.1-rc2**, another problem appears

```
{ Error: (HTTP code 500) server error - Updating join info failed: could not find endpoint b083cb5c2be1d9ba879c3348ffe5ae1a14f9ec0dc61a5740a132409f89f: []
    at /param_daemon/client/node_modules/docker-modem/lib/modem.js:229:17
    at getCause (/param_daemon/client/node_modules/docker-modem/lib/modem.js:259:7)
    at Modem.buildPayload (/param_daemon/client/node_modules/docker-modem/lib/modem.js:228:5)
    at IncomingMessage.<anonymous> (/param_daemon/client/node_modules/docker-modem/lib/modem.js:204:
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  reason: 'server error',
  statusCode: 500,
  json: { message: 'Updating join info failed: could not find endpoint b083cb5e0d42c2be1d9ba879c3348e1a14f9ec0dc61a5740a132409f89f: []' } }
```

Not sure if it's related to `dockerode`.

**Comment by Seikho** [comment]
Option objects are pretty much the same as what you see in the [Docker Remote API](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/). It may be worth adding a note to the readme to refer to the Remote API for more detailed documentation or include the TypeScript type definitions I've started creating for this library.

**Comment by stylixboom** [comment]
Actually, I don't know why following the test/network.js just not work, since the object I passed to the option should be the same as the line I followed: https://github.com/apocas/dockerode/blob/master/test/networks.js#L73

BTW, since the dockerode is quite friendly to Node.js users, I agreed on improving the documents/Readme not only on the container part, but also the others.

Cheers!

**Comment by Seikho** [comment]
It's a pretty ridiculsouly large API surface and the options for each function are quite frequently orders of magnitude larger. Perhaps listing the functions for end points and simply linking to the relevant sections in the Remote API would suffice.
@apocas would you be open to a PR that added this info the readme?

**Comment by apocas** [comment]
It doesn't make any sense to re-document the endpoints, since they are already documented at Docker's official documentation, https://docs.docker.com/engine/reference/api/docker_remote_api/
This information is described at https://github.com/apocas/dockerode/blob/master/README.md#usage

Being this said we could add direct links for each identity (containers, images, etc), but be aware that the documentation site (and urls) have changed multiple times in the past, additionally there's only links to specific versions.
