### ISSUE TITLE
Cant run images from a registry

### ISSUE THREAD

**Issue by chavezom** [apocas/dockerode#293]
When I try to run imagesfrom a resgistry, example hub.docker.company.net/chavomar/docker-bup:0.0.1, I receive an error saying that it cant find chavomar/docker-bup. Seems that it ignores the registry.

**Comment by LongLiveCHIEF** [comment]
is your docker daemon configured to add the `hub.docker.company.net` registry?

**Comment by chavezom** [comment]
Thanks for your reply @LongLiveCHIEF. Docker commands are able to run images from hub.docker.company.net. The issue I have is just when I try to run them from Dockerode. I searched the api for a method like docker login, but coudnt find one. Do you know if I have to setup something with the Api to configure the registry? 

My docker engine runs images from the registry succesfully.

**Comment by Seikho** [comment]
When you `pull` an image, you can [provide credentials](https://github.com/apocas/dockerode/blob/master/lib/docker.js#L614).
Is this what you're looking for?

**Comment by apocas** [comment]
Complete example:
https://github.com/apocas/dockerode#pull-from-private-repos
