### ISSUE TITLE
Copy file inside a container and keep it running

### ISSUE THREAD

**Issue by teone** [apocas/dockerode#294]
Hi,
I'm trying to dynamically create a container and start it. My actual code is:

```
docker.createContainer({Image: 'ubuntu', Cmd: ['/bin/bash'], name: 'ubuntu-test'}, function (err, container) {
    if (err) {
      return done(err);
    }

    container.start(function (err, data) {
      if (err) {
        return done(err);
      }
      return done(null, data);
    });
  });
```

I can see that the container is created, but it exit immediately:

```
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                     PORTS               NAMES
28cc42f72fe5        ubuntu              "/bin/ls /var"      2 minutes ago       Exited (0) 2 minutes ago                       ubuntu-test
```

How can I add some files (from the host machine) inside the container? I tried with `container.copy` and using `Bind` but they are both deprecated in `docker 1.12`

How can I keep it running? Will be enough to start a process in there?

To give some context I'd like to spin up a new container an run a `node` process in there that will listen for some kind of `pub/sub` events (probably rabbitMQ)

Any help/pointer to sample docs is appreciated!
Meanwhile thanks for the tool!

**Comment by teone** [comment]
After a bit of fighting this is the solution I've found:
```
docker.run('node', ['bash', '-c', 'cd /sync; npm install; npm start'], [process.stdout, process.stderr], {
    name: 'ubuntu-test',
    Volumes: {
      '/sync': {}
    },
    "HostConfig": {
       "Binds": [syncFolder + ':/sync']
    }
  },
  function (err, data, container) {
    // Called when container stop
  })
  .on('container', function (container) {
    // Container is UP
  });
```

**Comment by openStove** [comment]
Thanks for sharing, I'm missing a "cp" command to... would be nice

**Comment by teone** [comment]
@openStove yes, copying would be nice, sharing folders doesn't necessarily works in all cases

**Comment by apocas** [comment]
Isn't putArchive what you want? :)

https://github.com/apocas/dockerode/blob/master/lib/container.js#L573
https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/extract-an-archive-of-files-or-folders-to-a-directory-in-a-container

**Comment by brianjmiller** [comment]
The source code link isn't to the correct spot anymore (not surprising), if you need this look for `container.putArchive(file, options)` in the Dockerode readme. Also noted that `copy` used to exist, still does (at the time of writing) in the code, but issues a deprecation warning if used.
