### ISSUE TITLE
unable to start container after setting external volume driver (convoy)

### ISSUE THREAD

**Issue by Houtheyfa** [apocas/dockerode#295]
i'm usign convoy as volume plugin, starting containers with convoy volumes works perfectly in CLI . 
but i can't get it to work with dockerode. 
here is  the js code: 

var node = {
  Image: 'node',
  name: client_id + '_node',
  Env:[
      'process.env.PORT= 3000',
      "NODE_ENV=production"
    ],
  ExposedPorts: { "3000/tcp": {}},
  HostConfig: {

```
  RestartPolicy: {
      Name: 'always',
      MaximumRetryCount: 0
      },
    VolumeDriver: "convoy",     // here is !
    Binds: [ "doufa:/nodeapp" ], // doufa is a convoy volume name

  Workingdir: '/nodeapp',
  Cmd:[ "npm","start"],
  Volumes: {
      '/nodeapp': {},
  }
```

};

docker.createContainer(node, function(err, con){
        con.start(
            function(err,data){
            if(!err) {
                console.log("[node-id]: "+JSON.stringify(con.id));
              }
            }
          )});
when i run this code i get the following error : 
![selection_003](https://cloud.githubusercontent.com/assets/17686749/18145691/33ef29c4-6fc4-11e6-9305-197b488b018b.png)

anyone can help me with this ?

**Comment by apocas** [comment]
If there's no container there must be an error during container creation.
Print the `err` from createContainer to know what failed.

**Comment by Houtheyfa** [comment]
![selection_004](https://cloud.githubusercontent.com/assets/17686749/18146062/b47c8338-6fc5-11e6-8ff5-f774cfb4df11.png)
it fails when  trying to own the mounted volume ....
i tried running the code as root but still fails ....
