### ISSUE TITLE
How can I efficiently get the ID of a container by its name?

### ISSUE THREAD

**Issue by knight42** [apocas/dockerode#297]
At present, I list all containers first and then filter out the one with the right name.

**Comment by knight42** [comment]
Got it. Sorry for the noise.

**Comment by renz45** [comment]
Would have been nice to see the solution.. ;) Just for reference this was my solution:

```javascript
getContainerByName(name) {
    // filter by name
    var opts = {
      "limit": 1,
      "filters": `{"name": ["${name}"]}`
    }
    
    return new Promise((resolve, reject)=>{
      this.dockerode.listContainers(opts, function(err, containers) {
        if(err) {
          reject(err)
        } else{
          resolve(containers && containers[0])
        }
      });
    })
  }
```

The passing the name value as an array tripped me up, so don't forget those.

**Comment by davidkhala** [comment]
@knight42 So, would you like to share your solution? I can still not find any hints in documents

**Comment by knight42** [comment]
@davidkhala Simply `docker.getContainer(containerName)` should work.

**Comment by davidkhala** [comment]
@knight42 Thanks, and I found that getContainer return only a memory-object without checking its existence. I use `Container.stats()` to do that and test OK. Or any other recommend?

**Comment by sarkistlt** [comment]
@knight42 does it works the same way with `getService`?
