### ISSUE TITLE
How about promisfying the APIs?

### ISSUE THREAD

**Issue by knight42** [apocas/dockerode#300]

**Comment by Seikho** [comment]
Duplicate of #171 
As recommended in #171, https://www.npmjs.com/package/dockerode-promise

**Comment by knight42** [comment]
Got it. I think this can be noted somewhere. Thanks anyway!

**Comment by apocas** [comment]
Just pushed to the repo a promise based interface, check it out :)

**Comment by knight42** [comment]
@apocas Great work! Thank you!

Em... In some cases, I prefer another promise library instead of the native one, e.g. bluebird. Could you enable users to plug in their favourite promise library?

I think that can be achieved like this:

Users pass their promise library to Docker:
```js
const docker = new Docker({
  socketPath: '...',
  Promise: require('bluebird')
})
```

then the constructer can save it in the `Modem` instance

```js
Docker() {
...
  this.modem.Promise = opts.Promise || global.Promise
...
}
```

After that, just replace `return new Promise()` with `return new this.modem.Promise()`.

**Comment by apocas** [comment]
Humm, interesting :)

Yes this is a good idea.

**Comment by apocas** [comment]
Done :)
Thanks for the feedback!

**Comment by knight42** [comment]
@apocas Great! I can't wait for its publication to NPM!
