### ISSUE TITLE
Problem building images

### ISSUE THREAD

**Issue by blankenshipz** [apocas/dockerode#301]
I'm having an issue creating an image given a `Dockerfile`, here's what I'm seeing:

Setup: 

``` Dockerfile
# Dockerfile.error
FROM alpine:latest
```

``` javascript
// test.js
var Docker = require('dockerode');

var docker = new Docker({
  socketPath: '/var/run/docker.sock'
});

docker.buildImage('./Dockerfile.error', {t: 'error'}, function(err, stream) {
  console.log(err);
});
```

``` BASH
docker --version
> Docker version 1.12.1, build 6f9534c, experimental
```

Output:

```
{ [Error: (HTTP code 500) server error - {"message":"unexpected EOF"}
 ] reason: 'server error', statusCode: 500, json: null }
```

Any thoughts as to what could be causing my issue?

**Comment by apocas** [comment]
buildImage works with a tar file with a specific format, are you supplying this?

Check the example and documentation at:
https://github.com/apocas/dockerode/blob/master/examples/build/run.js
https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/build-image-from-a-dockerfile

**Comment by Fahrradflucht** [comment]
I would like to generate the Dockerfile in my app dynamically (like with a mustache template).
Can I just pass it a stream generated with [node-tar](https://github.com/npm/node-tar) or do I have to write this out to a file and pass it the path?

**Comment by apocas** [comment]
dockerode now can do this for you  :)

Check:
https://github.com/apocas/dockerode/blob/master/examples/build/build_img_files.js
https://github.com/apocas/dockerode#building-an-image
