### ISSUE TITLE
Support customized headers

### ISSUE THREAD

**Issue by edwardproxy** [apocas/dockerode#302]
We are using docker engine swarm mode and one scenario is:
On one swarm worker, our service, which is running inside a docker container, will make some remote api calls to swarm manager leader. Now we want to enable the TLS for docker daemon on the manager leaders.
To make those remote api calls, we use dockerode module, and what we want to do is to set the headers(Host: <common name>), then make the remote call by IP, not the common name, so we don't have to set it in /etc/hosts to tell what IP the common name will be resolved to.
Is it a reasonable change to support customized headers? e.g.

https://github.com/apocas/dockerode

``` javascript
var docker = new Docker({
  protocol: 'https',
  host: '192.168.1.10',
  headers:{Host: 'my-common-name'}, // we need it!!!
  port: process.env.DOCKER_PORT || 2375,
  ca: fs.readFileSync('ca.pem'),
  cert: fs.readFileSync('cert.pem'),
  key: fs.readFileSync('key.pem')
});
```

It seems docker-modem does support headers per every "dial", but dockerode doesn't pass in any extra options when making calls. 

This is the issue I filed to docker-modem:
https://github.com/apocas/docker-modem/issues/67

**Comment by ypjin** [comment]
Yeah, it sounds reasonable to allow setting additional headers.

**Comment by apocas** [comment]
Yes I think it may be reasonable and possible without polluting/over engineering usage.

**Comment by punkpeye** [comment]
Is this supposed to add headers to every request?

I am asking because I am seeing request fails b/c of missing headers I've added.
