### ISSUE TITLE
Dockerod create instead of run

### ISSUE THREAD

**Issue by Wats0ns** [apocas/dockerode#304]
Hi everyone,
So I have this very simple code:
 ``  docker.run('mouli', ['python', 'mouli.py'], function (err, data, container) {
      console.log('done');
  });
``

but when I do a `docker ps`, it seems that the container was created and not runned:

`1a0297000245        mouli                         "python mouli.py"        7 minutes ago       Created                                            adoring_fermat
`, which is weird because when I do a `docker run mouli python mouli.py`, everything happens well...

My conf:
- Node v6.6.0
- Docker version 1.11.2, build b9f10c9

Thanks for your support

**Comment by JarrodAMcEvers** [comment]
Are there any logs for your container?

**Comment by Wats0ns** [comment]
Nope, but the bug fix itself, I'm not able to reproduce it ...

**Comment by kilianc** [comment]
Is `err` `null` ?

**Comment by apocas** [comment]
Going to close this one then :)
