### ISSUE TITLE
Passing authconfig in the constructor

### ISSUE THREAD

**Issue by kartsims** [apocas/dockerode#306]
It would be nice to pass on to the constructor an `authConfig` object. It seems that docker-modem already handles it but it can't even be set on a per request basis.

I may be doing something wrong here so if I didn't do right, please let me know !

What I'd like to do :

```
var docker = new Docker({
  protocol: 'https',
  host: '196.168.xx.xx',
  authconfig: {
    username: 'myusername',
    password: 'mypassword',
    email: 'my@email.com',
    serveraddress: '196.168.xx.xx',
    auth: ''
  }
})
```

**Comment by apocas** [comment]
Dockerode supports auth per request/function (when available) this way you can use different credentials for each functionality.

There are a few examples on the readme.
