### ISSUE TITLE
How to use `credsStore`

### ISSUE THREAD

**Issue by kilianc** [apocas/dockerode#307]
I am currently using [`amazon-ecr-credential-helper`](https://github.com/awslabs/amazon-ecr-credential-helper) that requires to have `{ credsStore: 'ecr-login' }` in your `.docker/config.json`.

If I docker pull from the CLI everything is fine but from my code it fails: `'unauthorized: authentication required`

Any tips on how to make it work?

**Comment by apocas** [comment]
Dockerode only supports the typical authconfig setup which is what Docker's Remote API uses.
Not sure how credstore could be used in Remote API.

**Comment by kilianc** [comment]
@apocas yep you are right. It looks like it's a CLI conveniency that must be reimplemented.
