### ISSUE TITLE
EACCES error when connecting to docker on Ubuntu

### ISSUE THREAD

**Issue by chrisdias** [apocas/dockerode#308]
I'm running an Ubuntu image in Parallels. Docker runs fine from the terminal.

When i try to connect using this code:

``` javascript
this.endPoint = new Docker({ socketPath: '/var/run/docker.sock' });
``` 

I'm getting an EACCES error:

```
address:"/var/run/docker.sock"
code:"EACCES"
errno:"EACCES"
message:"connect EACCES /var/run/docker.sock"
stack:"Error: connect EACCES /var/run/docker.sock\n    at Object.exports._errnoException (util.js:1026:11)\n    at exports._exceptionWithHostPort (util.js:1049:20)\n    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)"
syscall:"connect"
```

Works find on OSX.

any ideas?

**Comment by chrisdias** [comment]
of course, you figure something out later...  so if i run my app as sudo, everything works.  but, i don't really want to have to run as sudo.  what is the best practice here?

**Comment by chrisdias** [comment]
solution:

https://docs.docker.com/engine/installation/linux/ubuntulinux/#/create-a-docker-group

**Comment by AgnibhaBose** [comment]
What is the solution? I'm getting the same problem.

**Comment by justinmetz** [comment]
The issue is the current user is not part of the "docker" group.  Instructions are at the top of this page -> https://docs.docker.com/engine/installation/linux/linux-postinstall/

**Comment by Nagarc** [comment]
This issues solved when I try to give permission to user as below

sudo chmod 666 /var/run/docker.sock. This is not there in post installation @justinmetz  

I am using chromebook and able to connect to docker from VS code

**Comment by andresjjn** [comment]
> sudo chmod 666 /var/run/docker.sock

That works for me. Thanks a lot!

**Comment by Rosevear** [comment]
Tried the linked post iinstall instructions but it didn't work (on Pop_OS 20.10) system 76 laptop. The chmod solution did, though.

**Comment by lyprono** [comment]
sudo chmod 666 /var/run/docker.sock

This work for me .thank you

**Comment by asit-prakash** [comment]
> This issues solved when I try to give permission to user as below
> 
> sudo chmod 666 /var/run/docker.sock. This is not there in post installation @justinmetz
> 
> I am using chromebook and able to connect to docker from VS code

It worked for me.
