### ISSUE TITLE
Status of Dockerode's equivalent to 'docker exec'?

### ISSUE THREAD

**Issue by moonlitSpider** [apocas/dockerode#309]
Hi,

I can't quite tell from the documentation (or from the description in issue #250) whether or not I can use dockerode to issue (effectively) a 'docker exec' command?

One specific area of uncertainty is whether or not I need to actually create the container before potentially issuing 'docker exec'. That is, can I simply provide the API a container ID and somehow drive 'docker exec' against it?

Thank you; and thank you for dockerode.

Cordially,

Paul

**Comment by apocas** [comment]
That issue was only related with console.log and inspect funcions, nothing affecting exec functionality.

Theres an example and test about exec.
I'm mobile right now, otherwise would link them :)

**Comment by moonlitSpider** [comment]
Thanks much.

I will look at the example.

**Comment by apocas** [comment]
Links:
https://github.com/apocas/dockerode/blob/master/examples/exec_running_container.js
https://github.com/apocas/dockerode/blob/master/test/container.js#L552
