### ISSUE TITLE
Using exec.start()

### ISSUE THREAD

**Issue by moonlitSpider** [apocas/dockerode#310]
Hi again,

So I read the examples you referred me to in issue #309. I've even "sort of" run your [example](https://github.com/apocas/dockerode/blob/master/examples/exec_running_container.js). Specifically, rather than create an instance of an Ubuntu container, I did a 

`docker.getContainer(ID)`

The container in question is running MongoDB and I'd like to be able to present to its shell (bash) several commands and get their responses. But I am uncertain about how to accomplish this. As matters stand, based on your example, I can see the usual console messages from MongoDB as its shell starts. These were raised in response to the original Cmd, 'mongo', presented by 

`container.exec()`

But now I need to present a few more commands to the MongoDB shell & parse the responses. These commands don't reside in a file. They are strings defined in the program itself.

Would you be so kind as to provide an example of how to do this with dockerode's exec facility?

Thanks.

Cordially,

Paul

**Comment by moonlitSpider** [comment]
Hmmm...maybe hold off for a bit on any kind of answer. I may have gotten it working. The "trick" appears to be the use of` 'hijack: true', 'stdin: true'` in the exec.start options as well as `'AttachStdin: true'` in the container.exec options.

**Comment by apocas** [comment]
👍
