### ISSUE TITLE
Problem when getting Events (docker.getEvents())

### ISSUE THREAD

**Issue by mohanprasaths** [apocas/dockerode#313]
function getEvents(res,ress){
	docker.getEvents(function(err,data){
		ress.send(data);
	})
}
Results in "TypeError: Converting circular structure to JSON" 

Using Express framework to provide docker api through dockerode

**Comment by apocas** [comment]
getEvents is a stream, just pipe it.

https://github.com/apocas/dockerode/blob/master/test/docker.js#L108

**Comment by Ashwin501** [comment]
Hi Apocas,

Even i faced same issue, but didn't understand what you told above.
