### ISSUE TITLE
How to set query parameters.

### ISSUE THREAD

**Issue by yabuchan** [apocas/dockerode#318]
In docker API, some parameters are passed as url queries, but it seems there are no way to set queries.
Is there any way to set queries with dockerode?

For example, in [docker commit](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/create-a-new-image-from-a-containers-changes), repository and tag are passed by query:
```
POST /commit?container=44c004db4b17&comment=message&repo=myrepo
```
 
However, looking at [around line 299 of dockerode lib file](https://github.com/apocas/dockerode/blob/master/lib/container.js) 
It seems no way to set query. (However, `path: '/commit?',
"` also seems as if there will be queries after "commit").

Here is a copy of code from lib/container.js which is related to the commit.

```
/**
 * Commit
 * @param  {Object}   opts     Commit options like 'Hostname' (optional)
 * @param  {Function} callback Callback
 */
Container.prototype.commit = function(opts, callback) {
  var args = util.processArgs(opts, callback, this.defaultOptions.commit);

  args.opts.container = this.id;

  var optsf = {
    path: '/commit?',
    method: 'POST',
    statusCodes: {
      200: true, // unofficial, but proxies may return it
      201: true,
      404: 'no such container',
      500: 'server error'
    },
    options: args.opts
  };

  this.modem.dial(optsf, function(err, data) {
    args.callback(err, data);
  });
};
```

**Comment by apocas** [comment]
https://github.com/apocas/dockerode/blob/master/test/container.js#L635

**Comment by yabuchan** [comment]
@apocas Thank you for your quick response! You are completely right, and I confirmed it works as you tested. Thanks again.
