### ISSUE TITLE
How to manage Docker container with dockerode

### ISSUE THREAD

**Issue by JeromeVi** [apocas/dockerode#320]
Ok I know it's not an issue or not really but I need a little help...
I'm trying to do a Meteor app to start/stop my Docker containers. I founded dockerode but I'm facing a problem and I think it's pretty basic.
I open a consol and I start my 2 containers with:

```
docker start 6684787338a7 (it contains a Meteor blog running on localhost:3000)
docker start 513cfc090925 (it contains MongoDB)
```
Then on my computer I start my Meteor app "controlContainers" on localhost:3001 and I this is my JS + HTML.

Am I creating the docker object wrong ? Or someone could help me to figure out what I'm doing wrong ? Because nothing happend when I start or stop I can do docker ps -aand there still has my 2 containers..

```
import { Template } from 'meteor/templating';

import './controlPanel.html';

Template.controlPanel.onCreated(function controlPanelOnCreated() {
    console.log("controlPanel is ready to work for you Mister Wayne");
   Docker = require('dockerode');
   docker = new Docker(); //{host: 'http://localhost', port: 3000}
   meteorCtn = docker.getContainer('6684787338a7');
   mongoCtn = docker.getContainer('513cfc090925');
});

Template.controlPanel.events({
  'click #clickPlease'(event){
      alert("docker:  " + docker);
      alert("meteorCtn: " + meteorCtn);

/* I tested that and my container wasn't running when I checked with docker ps so now I start them in the consol and I try to stop them..*/
     /*meteorCtn.start(function (err, data) {
        console.log(" meteorCtn should be running");
    });*/
    docker.listContainers(function (err, containers) {
      containers.forEach(function (containerInfo) {
        docker.getContainer(containerInfo.Id).stop(cb);
      });
      console.log("all containers should be stopped");
    });
  },
});
```
```
<template name="controlPanel">
  <p>Start, stop and pause containers from this website</p>
  <input type="button" id="clickPlease" value="Click on me please">
</template>
```

**Comment by djedi23** [comment]
Ok, I know it's not a real answer but you can cherrypick some code from:
https://github.com/djedi23/meteor-docker

It's a docker control panel written with MeteorJS and dockerode.

**Comment by JeromeVi** [comment]
@djedi23 Oh thank you Sir I'm sure it's gonna be helpful :

**Comment by djedi23** [comment]
Some raw pointers:

- Docker initialization:
https://github.com/djedi23/meteor-docker/blob/master/server/startup.js#L8

- Docker start call chain:
https://github.com/djedi23/meteor-docker/blob/master/server/methods.js#L461
https://github.com/djedi23/meteor-docker/blob/master/server/methods.js#L282

- Getting the container by Id:
https://github.com/djedi23/meteor-docker/blob/master/server/methods.js#L287

- Generic call to a container method (`fct` is the function name: _start_ for example):
https://github.com/djedi23/meteor-docker/blob/master/server/methods.js#L292
For the start method, `callopts` is an empty object.
