### ISSUE TITLE
Kill exec

### ISSUE THREAD

**Issue by FLYBYME** [apocas/dockerode#322]
How would one kill a running exec?

**Comment by AlexanderCollins** [comment]
```
// stop the container.
instance.stop.bind(instance);

// remove the container.
instance.remove.bind(instance, {force: true});
```

**Comment by FLYBYME** [comment]
No I dont want to stop the container but just the exec instance. https://github.com/apocas/dockerode/blob/master/lib/exec.js#L19

**Comment by AlexanderCollins** [comment]
It seems that the docker API does not yet support this [docker/docker/issues/9098](https://github.com/docker/docker/issues/9098).
