### ISSUE TITLE
Cannot pull image

### ISSUE THREAD

**Issue by fsamir** [apocas/dockerode#328]
Hi there,

I am trying to pull an image from a private repository (Amazon ECR) and I get the error message below. 
Notice the error message doesn't mention the image tag, hence I believe it is removing it before pulling. Since there is not image without a tag in the repository, it can't find it.

**Error message:**
```
On status:
{ status: 'Pulling repository xxxxx.dkr.ecr.us-east-1.amazonaws.com/foo/bar' }
Pull complete:
 [ { status: 'Pulling repository xxxxx.dkr.ecr.us-east-1.amazonaws.com/foo/bar' },
  { errorDetail: { message: 'Error: image foo/bar not found' },
    error: 'Error: image foo/bar not found' } ]
````

**Code:**
```
//Valid ECR credentials
 var auth = {
   username: usernameAndPasswordPair[0],
   password: usernameAndPasswordPair[1],
   serveraddress: 'https://xxxxx.dkr.ecr.us-east-1.amazonaws.com/'
};

var image = 'http://xxxxx.dkr.ecr.us-east-1.amazonaws.com/foo/bar:some-version'; 
dockerode.pull(image, {'authconfig': auth}, function (err, stream) {
...
}|
```

**Comment by apocas** [comment]
Humm I don't believe that's the problem.

I just tested the parser with your image string and it worked correctly.
https://github.com/apocas/dockerode/blob/master/lib/docker.js#L1203

I'm a bit a clueless without more info :/
