### ISSUE TITLE
request for documentation: how to stream / get data from container.stats

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [apocas/dockerode#331]
I can't seem to make the above run. Since the test just looks for .pipe being present, it was of no help either. 

Possibly under circumstances, like a non-running container, the API doesn't return data, but just 200?

**Comment by eljefedelrodeodeljefe** [comment]
In fact that is the case. Maybe you want to consider not returning the stream if it is not readable or does not send data. 

Feel free to close as you please.

**Comment by apocas** [comment]
Docker returned 200 and an "empty" stream?

Could you please provide more details.
