### ISSUE TITLE
Service update not work

### ISSUE THREAD

**Issue by ZigmunD** [apocas/dockerode#333]
Docker 1.13.1
API v1.24-1.26

When I try to update a service, I get:
`{ [Error: (HTTP code 500) server error - Invalid service version '': strconv.ParseUint: parsing "": invalid syntax ]
  reason: 'server error',
  statusCode: 500,
  json: { message: 'Invalid service version \'\': strconv.ParseUint: parsing "": invalid syntax' } }`

Googled a while and found that to update a service we need to set ?vesion=x. Version number we can get from service inspect.

From docker docs:
> version	
> integer Required
> The version number of the service object being updated. This is required to avoid conflicting writes.

From dockerode service update prototype:
`...
path: '/services/' + this.id + '/update?',
...`

Is it bug or missed something?

**Comment by apocas** [comment]
Did you provide the version in the options?

Like so: https://github.com/apocas/dockerode/blob/master/test/swarm.js#L211

**Comment by apocas** [comment]
I had a similar issue myself.

The best way is the query Docker for the current service version and work from that.

Just like this test is doing: https://github.com/apocas/dockerode/blob/master/test/swarm.js#L215

**Comment by coolBoyGym** [comment]
I got the same problem and solved it by what @apocas said. Although it is a little puzzled that the "version" changes so quick. Anyway, thanks a lot @apocas
