### ISSUE TITLE
Error in building image: data.pipe is not a function

### ISSUE THREAD

**Issue by think01** [apocas/dockerode#334]
I'm issuing this call:

    import Dockerode from 'dockerode';
    const dode = new Dockerode();

	dode.buildImage({
	  context: contextPath,
	  src: ['.']
	}, {t: tag}, function (err, response) {
	  callback(err, response);
	});

and I get this error:

    Uncaught TypeError: data.pipe is not a function
    Modem.buildRequest @ modem.js:221
    Modem.dial @ modem.js:163
    Docker.buildImage @ docker.js:199
    [...]

The originating code is in docker-modem, file modem.js:

```
if (typeof data === "string" || Buffer.isBuffer(data)) {
  req.write(data);
} else if (data) {
  data.pipe(req);
}
```
If I understand well, since I'm calling buildImage with an option object, Dockerode builds a tar on the fly (using concat-stream) and passes it to docker-modem, that understands to have something different from the file name (string) or a buffer and expect to be able to call pipe(). This last thing fails.

So is this a bug or am I missing something/doing something wrong that fools the library?

Thx in advance for any help.

**Comment by jkingyens** [comment]
This API is in master but not the published module. You should "npm install" from the repo version to get this feature for now. I ran into the same issue ;)

**Comment by nwalters512** [comment]
@jkingyens are you talking about `dockerode` or one of its dependencies? I just installed from the repo version and I'm still facing this issue.

@apocas is there an official fix for this?

**Comment by apocas** [comment]
@nwalters512 you shouldn't be facing this issue, if running from the repo.

https://github.com/apocas/dockerode/blob/master/test/docker.js#L72
Try to run this test, it will work.

I will lock RAPI v1.36 changes and publish a new version in npm today.

**Comment by apocas** [comment]
v2.3.2, which includes this functionality was published 4 days ago.
