### ISSUE TITLE
Inspect a single service in a swarm from the "id" string

### ISSUE THREAD

**Issue by wdalmut** [apocas/dockerode#335]
Hi, 

I have a service `ID` string, how can i inspect that service without using the `listService`?

Actually i am using something like:

```js
const Service = require('dockerode/lib/Service');

service = new Service(docker.modem, {ID: "abc3598723"});
service.inspect(function(err, data) {

});
```

There is a better way to inspect a service having its identification code?

**Comment by apocas** [comment]
Yes there is :)

https://github.com/apocas/dockerode/blob/master/lib/docker.js#L263
