### ISSUE TITLE
[Question]How to pass parameter to runExec ? No documentation founded

### ISSUE THREAD

**Issue by JeromeVi** [apocas/dockerode#337]
Hi,
I want to send the command `docker exec -it  containerX bash` using `runExec` so how to pass the `-it` ?

```
function runExec(idContainer, from, cmd) {
    if(typeof cmd == 'undefined'){
      var options = {
          Cmd: ['/bin/bash'],
          AttachStdout: true,
          AttachStderr: true,
          AttachStdin: true,
          Detach: false,
          Tty: true
      };
    }else{
      var options = {
          Cmd: cmd.split(' '),
          AttachStdout: true,
          AttachStderr: true,
          AttachStdin: true,
          Detach: false,
          Tty: true
      };
    }

    docker.getContainer(idContainer).exec(options, function(err, exec) {
        if (err){
          console.log("erreur docker.getContainer.exec")
          console.error(err);
          return;
        }

        //run the cmd
        exec.start(function(err, stream) {
            if (err){
              console.log("erreur exec.start")
              console.error(err);
              return;
            }

            //if you read the issue could you tell me what this line do ?
            docker.getContainer(idContainer).modem.demuxStream(stream, process.stdout, process.stderr);

            stream.on('data', function(data) {
              //send the response of the cmd from Docker
              Streamy.emit('result',{result: data.toString()}, from);
            });

            stream.on('error', function(err) {
                console.errore(err)
            });

            stream.on('end', function() {
                console.log('stream END ')
            });
        });
    });
//...
```

**Comment by chepchepcirkus** [comment]
hey,  i think this parameters is managed by the option attachStdin: true and Tty : true.
Because -t parameters is "Allocate a pseudo-TTY" 
and -i "Keep STDIN open even if not attached"

**Comment by JeromeVi** [comment]
@chepchepcirkus  So with my parameters it's as if I did `docker exec -it ` that's right ?

**Comment by JeromeVi** [comment]
Maybe it comes from the fact that every time I receive a command I run the method `runExec`  that I posted yesterday ?

If you can help me I'll appreciate

**Comment by apocas** [comment]
exec.start are very similar to container.attach so hijack should work.

Did you try to use the hijacking functionality?

Just like in this attach test: 
https://github.com/apocas/dockerode/blob/master/test/container.js#L434

**Comment by apocas** [comment]
Even better theres a test exactly for this, exec with stdin:
https://github.com/apocas/dockerode/blob/master/test/container.js#L580

**Comment by JeromeVi** [comment]
Yes with your links I have founded that I had to add ` {hijack: true, stdin: true}` and now it works ! Thank you
