### ISSUE TITLE
API capitalization is inconsistent

### ISSUE THREAD

**Issue by nwalters512** [apocas/dockerode#338]
The dockerode API has very inconsistent capitalization in options object field names. Consider the following snippet from the documentation:

```
docker.createContainer({Image: 'ubuntu', Cmd: ['/bin/bash'], name: 'ubuntu-test'}, function (err, container) {
  container.start(function (err, data) {
    //...
  });
});
```

`Image` and `Cmd` are capitalized, while `name` is not. This makes it very difficult to reason about the API and use it from memory. Is there a reason for this? If not, I'd like this to be standardized in a future version. I'm willing to make a PR for this. I know this would be a breaking change, but I think it would be valuable.

**Comment by apocas** [comment]
Unfortunately this is the wrong place to ask that question :)

https://docs.docker.com/engine/api/v1.26/#operation/ContainerCreate

We are just following Docker's Remote API spec :)

**Comment by nwalters512** [comment]
Fair enough! Wasn't aware the goal was to match that exactly.
