### ISSUE TITLE
Automatic fallback to promises?

### ISSUE THREAD

**Issue by apocas** [apocas/dockerode#339]
Instead of using a specific option to turn on the promise based interface, like so:
https://github.com/apocas/dockerode#promises-yet-to-be-published-to-package-managers 

Could we automatically fallback to promises when a callback was not provided to a function call?

Didn't give it much thought, but I think it may be interesting to openly discuss the pros and cons of doing something like this.

**Comment by sheerun** [comment]
It's a good way to support promises as well. There are no cons if currently you don't expect your users to use the value returned from callback functions (if there's any).

**Comment by sheerun** [comment]
Plus you can always return a promise, even if callback argument is present

**Comment by apocas** [comment]
https://github.com/apocas/dockerode/commit/1d8d33122626dfd5dfd3a05b54fcf944662d016e

Definitely cleaner now :)

**Comment by apocas** [comment]
Published v2.3.3
