### ISSUE TITLE
docker.run(...).then is not a function

### ISSUE THREAD

**Issue by jacksoncharles** [apocas/dockerode#340]
I was attempting to use docker.run with the example on the readme returning a promise.  Using this code, which is a virtual cut and paste of the documentation I simply get the error "docker.run(...).then is not a function". 

docker.run(MyImage, [], process.stdout).then(function(container) {
  console.log(container.output.StatusCode);
  return container.remove();
}).then(function(data) {
  console.log('container removed');
}).catch(function(err) {
  console.log(err);
});

Can you advise? Apologies if I am missing something simple.

**Comment by apocas** [comment]
If you installed from npm, it is expected :)

The version that is in the master branch is yet to be published onto NPM, will probably publish it tonight.

**Comment by apocas** [comment]
Just published v2.3.3 which features the promise interface :)

**Comment by jacksoncharles** [comment]
thanks :-)
