### ISSUE TITLE
How to use `log` api of container?

### ISSUE THREAD

**Issue by kamushin** [apocas/dockerode#342]
Get a 400 error while using `container.log()`
`(HTTP code 400) unexpected - {"message":"Bad parameters: you must choose at least one stream"}`

**Comment by chepchepcirkus** [comment]
You can find available parameters https://docs.docker.com/engine/api/v1.19/#get-container-logs

**Comment by apocas** [comment]
Example:
https://github.com/apocas/dockerode/blob/master/examples/logs.js
