### ISSUE TITLE
Support for DOCKER_* environment variables broken when using Promises

### ISSUE THREAD

**Issue by tanuck** [apocas/dockerode#343]
By doing:
`docker = new Docker({})` or `docker = new Docker({Promise: require("bluebird")})`

When reaching this line `this.modem = new Modem(opts);` on line 23 of `lib/docker.js`, `opts` is a non null object which prevents `defaultOpts()` in the `docker-modem` constructor ever being called. This is now broken for anyone relying on `docker-modem` to read the DOCKER_* env variables for the connection to the docker host.

Cheers

**Comment by apocas** [comment]
Pusblished in v2.3.5.

Not the prettiest fix, we will revisit this one :)

**Comment by tanuck** [comment]
👍
