### ISSUE TITLE
All inspect methods fail to query docker when using promises

### ISSUE THREAD

**Issue by tanuck** [apocas/dockerode#345]
Hi again,

All the `inspect` methods contain the following code block (or similar):

```javascript
if (typeof args.callback !== 'function') {
  return JSON.stringify({
    id: this.id
  });
}
```

Meaning that when you're using the Promise based api, these methods never return the full dataset from the docker host. Can I ask why this was included just for these methods? Can it simply be removed now that we have the Promise interface? If so, I can submit PR with my local changes.

Cheers

**Comment by apocas** [comment]
https://github.com/apocas/dockerode/pull/344

**Comment by tanuck** [comment]
Ah, sorry didn't notice #344

**Comment by apocas** [comment]
Np :)
It is now published.
