### ISSUE TITLE
Promise is undefined in modem object

### ISSUE THREAD

**Issue by chepchepcirkus** [apocas/dockerode#348]
Hi,
release 2.4.1
node version v0.10.29

i want to work with Promise,
the native promise doesn't exists,
i got this error, do i miss something ?

> 
> TypeError: undefined is not a function
>     at Container.inspect (/var/www/html/docktor/node_modules/dockerode/lib/container.js:60:12)

```
docker = new Docker({host: '0.0.0.0', port: 2375});
var container = docker.getContainer(id);
container.inspect().then(function(container) {
        ....
});
```
or even in this way 
`var data = container.inspect();`

**Comment by apocas** [comment]
Node.js only added native promise support in version 0.11.13, you are using 0.10.29 which is old.
