### ISSUE TITLE
Containers are removed with Container ID, where not with Container Name

### ISSUE THREAD

**Issue by ksantoshpink** [apocas/dockerode#350]
HI,

Currently have a problem, like when containers are placed in orchestration and one minion goes down then containers move to other and container ID gets changed and my code fails when i want to remove, Dockerode has not have a container remove with container name?

**Comment by apocas** [comment]
Just supply the name instead of the ID :)

https://docs.docker.com/engine/api/v1.26/#operation/ContainerDelete
