### ISSUE TITLE
Problem with mounting volumes on windows

### ISSUE THREAD

**Issue by GalRoimi** [apocas/dockerode#353]
Hey,
I posted a question on stackoverflow about this topic (using your module):
https://stackoverflow.com/questions/42995473/mount-a-volume-in-docker-using-nodejs-on-windows

Can you please help me?
thanks.

**Comment by jsalonen** [comment]
@GalRoimi Answered you in Stackoverflow: https://stackoverflow.com/questions/42995473/mount-a-volume-in-docker-using-nodejs-on-windows/43704108#43704108

Since this is not likely an issue with dockerode, @apocas please feel free to close.
