### ISSUE TITLE
How to stop getting the logs ?

### ISSUE THREAD

**Issue by JeromeVi** [apocas/dockerode#369]
Hi,
I'm trying to find that since a few hours so how can we stop getting the logs ? I use your method https://github.com/apocas/dockerode/blob/master/examples/logs.js but I can't stop them.

We need to send something in the `stream` ?

**Comment by apocas** [comment]
Just updated the example with what you need :)

https://github.com/apocas/dockerode/blob/master/examples/logs.js

**Comment by JeromeVi** [comment]
Thank you :)
sorry for coming again but correct me if I'm wrong but with your method we can't destroy de stream by ourself.

For example :  `btn_stopStream.onclick(){ logStream.destroy }` would work but we can't access to `stream` itself 

am I right ? Thank you for the inputs
