### ISSUE TITLE
Piping a readable stream as input to a container

### ISSUE THREAD

**Issue by boucher** [apocas/dockerode#371]
I'm trying to read a tar in a stream and pipe that to a container, but when I do, the stream never seems to close. Here's (approximately) the code:

```
    var inputStream = fs.createReadStream(tarballPath);
    var destinationStream = tarFS.extract(tarDestination)

    var container = await docker.createContainer({
        Image: 'node:latest',
        AttachStdin: true,
        AttachStdout: true,
        AttachStderr: true,
        Tty: false,
        OpenStdin: true,
        Cmd: ["/bin/sh", "-c", "tar xzvf - && tar c . | cat"]
    });

    await container.start()

    var containerStream = await container.attach({stream: true, stdin: true, stdout: true, stderr: true});

    containerStream.pipe(destinationStream);
    inputStream.pipe(containerStream);

    await container.wait();
```

I get the output I expect from tar in the container's stdout, but the container never exits, and if I add in some logs, the readable stream never ends. Any suggestions?

**Comment by aafrey** [comment]
not an expert, but this might have something to do with using async/await with streams. this might help https://stackoverflow.com/questions/33599688/how-to-use-es7-async-await-with-streams

**Comment by marcj** [comment]
See https://github.com/apocas/dockerode/issues/455#issuecomment-489436370 for the solution.
