### ISSUE TITLE
Create Container don't take name

### ISSUE THREAD

**Issue by arckosfr** [apocas/dockerode#373]
Hello i use to create container like this 

```js
 docker.createContainer({'name' : 'test', etc etc }, function(err, container)
```
but the name is don't take anymore docker always use random name. i see in API that name now need to be sent with the query and not in the body.
do i miss something ?

Thanks

**Comment by apocas** [comment]
Humm name is also sent in query.
Going to investigate.

**Comment by fluency03** [comment]
@arckosfr I do not think it is because the diff position of `name` between query and body. It is working fine to me.

**Comment by arckosfr** [comment]
@fluency03 do you use last docker api version ?

**Comment by fluency03** [comment]
Not the latest one. 

@arckosfr 

```
$docker version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by rapitable** [comment]
I'm having the same issue on docker.run:

```
docker.run(imageId, 
        [ "node","entry.js" ], 
        process.stdout, 
        { Env: ["NODE_ENV=development"],
          Name: "myname",
        }, 
      async function(err, data, container){
         ...
      }
    )
```

Container starts fine but no name. This is my docker version:

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by arckosfr** [comment]
Maybe i don't understand but docker API say : 
```
Create a container

PARAMETERS

Query Parameters ?
 name	
string /?[a-zA-Z0-9_-]+
Assign the specified name to the container. Must match /?[a-zA-Z0-9_-]+.
```
And name is not listed into body parameter
@fluency03 how do you create new container ?

Thanks

**Comment by fluency03** [comment]
Maybe instead of this `{'name' : 'test', etc etc }`, try this `{name: 'test', etc etc }`?

**Comment by arckosfr** [comment]
Oh i'm dumb, on create it work, but i was testing in with update function (retrieve actual container info, send it in docker.create with user modification) but in docker inspect it was Names no name so it wont work.
So i think there is no bug at all on dockerode side....

My bad

**Comment by rapitable** [comment]
Does anybody know what I'm doing wrong above? Sure I'm misunderstanding something...

**Comment by fluency03** [comment]
@rapitable if you only have problem with giving a new name to the container created, in the `create_options` part, the name key should be in lower case, i.e. `{name: 'myname', ... }`

**Comment by rapitable** [comment]
Thanks a lot, will try this tonight

**Comment by rapitable** [comment]
@fluency03 that worked, help much appreciated

**Comment by WesleyBatista** [comment]
Hey guys, having the same issue here. But for me the solution pointed out didn't worked.

What I noticed is that when running the command on the CLI, `docker create mongo`, I got **Unable to find image 'mongo:latest' locally**. The CLI default behavior is to pull the image, but apparently dockerode doesn't do that for us.

After pulling the image it all runs normally here
