### ISSUE TITLE
How to run a command on the docker host ?

### ISSUE THREAD

**Issue by JeromeVi** [apocas/dockerode#377]
Hi,
I need to run `cat docker-compose.yml | docker run -i funkwerk/compose_plantuml --link-graph | docker run -i think/plantuml > output.svg` via JavaScript to a Docker host.

My app is a Docker container, and I need to send this command to generate a SVG on the **Docker host**.

I can connect my app to the socket of the host like this:
```
docker = new Docker({
        socketPath: '/var/run/docker.sock'
 });
```
because I mounted the volume.

The thing is **how to send a command to the host terminal and not to the container terminal** ?
I tried like this: 
```
exec_tool = require('child_process').exec;    
child = exec_tool('cat docker-compose.yml | docker run -i funkwerk/compose_plantuml --link-graph | docker run -i think/plantuml > output.svg',
            function (error, stdout, stderr) {
                console.log('stdout: ' + stdout);
                console.log('stderr: ' + stderr);
                if (error !== null) {
                     console.log('exec error: ' + error);
                }
            });
```
But the thing is, with this method it send the command to the container terminal, I want to send it to the host terminal.

Maybe I could use:
```
docker.run('ubuntu', ['bash', '-c', 'uname -a'], [process.stdout, process.stderr], {Tty:false}, function (err, data, container) {
  console.log(data.StatusCode);
});
```

but how to run it on the host and not inside a container ?

Thank you for the help

**Comment by Seikho** [comment]
This is because it's not related to `dockerode`, but related to Node.js.
You'll be able to use the `child_process` Node.js API for this. See: https://nodejs.org/dist/latest-v10.x/docs/api/child_process.html

**Comment by Seikho** [comment]
Apologies, I misread the original question.

To answer OP's question, I would generate the SVG inside the container in a mounted volume.
As for a container trying to run something on the host, I simply wouldn't. If you're talking about Docker in Docker, that can be done though.
I have done things like passing on the Docker socket and binary in as volumes to a Jenkins container to allow Jenkins access to Docker on the host.

What kind of problem are you trying to solve? What kinds of commands are you trying to run? There may be another solution that doesn't require the container reaching out to the host.

**Comment by binarymist** [comment]
I need to run a docker-compose from within a container (based on number of different types of docker images specified by the end user at run time). I may be running in AWS Fargate at some point, so volume mounts are out of the question, as only bind mounts are supported by AWS Fargate. I may be able to run a lambda function on the container host, but there is still the question of how to best access that from within the container.
