### ISSUE TITLE
Add support for checkpoints

### ISSUE THREAD

**Issue by apatryda-instapage** [apocas/dockerode#386]
Docker added support for checkpoints as an experimental feature. You can run it using [`docker checkpoint`](https://docs.docker.com/engine/reference/commandline/checkpoint/) CLI command. As Docker CLI is [implemented using API calls](https://github.com/moby/moby/blob/master/client/checkpoint_create.go), it would be nice to have this feature in dockerode. It would be also nice to handle new `docker start` [parameters](https://github.com/moby/moby/blob/master/client/container_start.go).

**Comment by apocas** [comment]
It is in the master branch, but the endpoints aren't tested properly tested yet.
We will

**Comment by apocas** [comment]
Container start already support parameters, you can use any of the start parameters since they are not hardcoded into dockerode. They are just passed to docker.

https://github.com/apocas/dockerode/blob/master/lib/container.js#L374
