### ISSUE TITLE
equivalent of 'docker stats' in dockerode?

### ISSUE THREAD

**Issue by jhiver** [apocas/dockerode#389]
Title says it all I think... couldn't find anything about it in the docs. Thanks

**Comment by jhiver** [comment]
https://github.com/apocas/dockerode/blob/master/lib/container.js#L907 - for search engines?

**Comment by Seikho** [comment]
I have some code [here](https://github.com/paypac/node-concierge/blob/master/src/api/stats/containers.ts#L29) which demonstrates streaming container stats.

**Comment by roccomuso** [comment]
+1 for the stats.
This should be the interested [stats docker engine API](https://docs.docker.com/engine/api/v1.31/#operation/ContainerStats).

**Comment by apocas** [comment]
Stats endpoint is already implemented:
https://github.com/apocas/dockerode/blob/master/test/container.js#L174

Checking `docker stats` cli source code, I see they iterate the containers using the stats endpoint.

**Comment by roccomuso** [comment]
@apocas ok, so it's not documented pheraps?

**Comment by apocas** [comment]
How so?
