### ISSUE TITLE
Equivalent of RUN -p hostPort:containerPort IMAGENAME ?

### ISSUE THREAD

**Issue by hlfshell** [apocas/dockerode#39]
I see no way to add flag options for the docker run command (such as -i, -p, -t, etc) with the docker.run command, nor do I see any way in the tests/examples. Is this possible?

**Comment by ekkis** [comment]
well I tried that and got:

> Unhandled rejection Error: (HTTP code 400) unexpected - starting container with HostConfig was deprecated since v1.10 and removed in v1.12 


how is it done now?
