### ISSUE TITLE
How to start a container ? 

### ISSUE THREAD

**Issue by ajayramesh23** [apocas/dockerode#390]
I am tyring to run this command in  dockerode, I am bit confused on how to run it.
`docker run -d -p 1527:80 ajaycs14/hello-world`

my code
```
docker.run('ajaycs14/hello-world', [], process.stdout, {createOptions:{}}, {start_options:["-p 8888:80", "-d"]}, function (err, data, container) {
 // ....
});

```

Container is not started. I am pretty sure something wrong while invoking `run` , but I couldn't able to figure out. 
thank you

**Comment by Chechuline** [comment]
Try with

docker.run('ajaycs14/hello-world', [], process.stdout, {PortBindings: { "1337/tcp": [{ "HostPort": "5000" }] } }, function (err, data, container) {
 // ....
});

The real options are in [DockerApi](https://docs.docker.com/engine/api/v1.22/#21-containers)

**Comment by apocas** [comment]
Going to close this one, since it was already tackled :)

**Comment by MahmoudMousaHamad** [comment]
This worked for me by adding `ExposedPorts` to the start options object:
```js
docker.run('ajaycs14/hello-world', [], process.stdout, {
PortBindings: { "80/tcp": [{ "HostPort": "8888" }] }, 
ExposedPorts: {"80/tcp": {}}
}, function (err, data, container) {
 // ....
});
```
