### ISSUE TITLE
Rebuilding an Image

### ISSUE THREAD

**Issue by AgnibhaBose** [apocas/dockerode#392]
How to forcefully rebuild an image? I was trying to build image with the same name.. but it is not being able to create a new image with the same name..

**Comment by apocas** [comment]
How so?
Could you please show us a snippet from you code?

**Comment by Seikho** [comment]
I do this quite regularly using dockerode without doing anything special.
The image that _used_ this tag gets 'orphaned' as expected. 
[An example of building an image here in my project](https://github.com/the-concierge/concierge/blob/master/src/api/applications/build.ts#L26)
