### ISSUE TITLE
image operating system "windows" cannot be used on this platform

### ISSUE THREAD

**Issue by davidkhala** [apocas/dockerode#393]
Since I saw the 'no image found' problem in callback after pull image. I turned to use `.modem.followProgress` as in #107 
```
  return docker.pull(imageName).then(stream => {
		return new Promise((resolve, reject) => {
			const onProgress = (event) => {}
			const onFinished = (err, output) => {
				console.log({err,output})
				return err ? reject(err) : resolve(output)
			}
			docker.modem.followProgress(stream, onFinished, onProgress)
		})

	})
```
In `err` i saw string like `image operating system "windows" cannot be used on this platform`, but what I used is just Ubuntu 14 as a VM inside win10
The image I used here is just library/hello-world
docker API version is 1.30

**Comment by apocas** [comment]
Docker is returning that error, nothing we can do on our side :/

Which image you were trying to pull?
