### ISSUE TITLE
running arbitrary docker commands

### ISSUE THREAD

**Issue by grawk** [apocas/dockerode#394]
Based on the Docker API, it seems that running such commands as `docker cp` is not possible via this module. Is that true? If so, has anyone come up with an alternative approach that doesn't require "shelling out" to run the docker CLI?

Thanks.

**Comment by apocas** [comment]
Checking `docker cp` source code you will see that it uses the `archive`endpoint.
https://github.com/moby/moby/blob/master/client/container_copy.go#L46

You have a `dockerode` test using `archive` endpoint exactly with what you want:
https://github.com/apocas/dockerode/blob/master/test/container.js#L81
