### ISSUE TITLE
attach to stdin with http proxy

### ISSUE THREAD

**Issue by VictorLeach96** [apocas/dockerode#395]
I'm attempting to attach to the stdin of a container through a http proxy. I've tested most of the apis which work perfectly apart from writing to an attach stream.

The stdout and stderr works perfectly but when I try to write to the stream the command is not executed. I've narrowed it down to the proxy by connecting directly to the socket and it works.

Let me know if I need to raise an issue with the [http-proxy-middleware](https://github.com/chimurai/http-proxy-middleware) as I'm not sure how this is being handled internally.

```javascript
//Engine
const engine = new Docker({
//	socketPath: '/var/run/docker.sock'
	protocol: 'http',
	host: '192.168.0.4',
	port: 3001
})

//Attach
engine.getContainer('...').attach({
     stream: true,
     stdout: true,
     stdin: true,
     stderr: true,
     logs: true
}, (err, stream) => {
    
     stream.pipe(process.stdout)
    
     setInterval(() => {
          stream.write('uptime\n')
    }, 1000)
})
```

```javascript
//Proxy
const proxy = require('http-proxy-middleware')
app.listen(3001)
app.use('/', proxy({
    ws: true,
    target: { socketPath: '/var/run/docker.sock' }
}))
```

**Comment by apocas** [comment]
Try using hijack.
`hijack: true`

Check this test as example:
https://github.com/apocas/dockerode/blob/master/test/container.js#L436

**Comment by VictorLeach96** [comment]
I've tried hijack. I think it's something to do with the proxy as it works without.
Just wondering if you may have an idea about where I can start with this as I am unsure as to what could be causing it.

**Comment by apocas** [comment]
Weird indeed.

I would take a look into proxy (debug wise) trying to figure out what's happening when stream are used.

**Comment by apocas** [comment]
Closing this one, reopen if needed.
