### ISSUE TITLE
Support restoring from a checkpoint when starting containers

### ISSUE THREAD

**Issue by pronvit** [apocas/dockerode#396]
Currently if you pass checkpoint parameters to `container.start()` call, they will be sent as POST data and you'll get "starting container with non-empty request body was deprecated since v1.10 and removed in v1.12" error. 

These parameters must be passed in url, i.e.
```javascript
path: '/containers/' + this.id + '/start?checkpoint='+encodeURIComponent(checkpoint)+'&checkpoint-dir='+encodeURIComponent(checkpointDir)+'&'
```

**Comment by apocas** [comment]
You can call container.start() using _query option.
Something like: container.start({'_query': {'checkpoint': ...}})

**Comment by pronvit** [comment]
Thanks, didn't know about the _query.

**Comment by apocas** [comment]
Soon I probably will default the `start` options to query/url instead of body, if you don't send `_query`.
This way it won't be a breaking change while eliminating the necessity to use it.

**Comment by mvila** [comment]
I tried this "_query" options, it doesn't work for me, there is still the deprecation error.

@apocas: I really need to pass options to `container.start()`, any progress on this issue?

**Comment by apocas** [comment]
Closing this one (shouldn't be an issue nowadays), reopen if needed.
