### ISSUE TITLE
Support Storage Options

### ISSUE THREAD

**Issue by DerekTBrown** [apocas/dockerode#398]
How do I pass storage options?

https://stackoverflow.com/questions/33013904/how-to-limit-docker-filesystem-space-available-to-containers

**Comment by DerekTBrown** [comment]
It is called `DiskQuota` in the new version of the API:

https://docs.docker.com/engine/api/v1.30/#operation/ContainerCreate

**Comment by DerekTBrown** [comment]
Added to typings:

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/19513

**Comment by apocas** [comment]
👍
