### ISSUE TITLE
Give an example of how to create services

### ISSUE THREAD

**Issue by mhemrg** [apocas/dockerode#399]
Hi,
I want to create a service but I don't know how to use the dockerode's API. Please give an example.

**Comment by timoweiss** [comment]
hi @mhemrg,
maybe you can elaborate what you mean by "creating a service"?
Do you want to run a container image?
Maybe you know the related docker command(s)?

**Comment by mhemrg** [comment]
The related command: `docker service create --name redis --label my_label=value redis:latest`

**Comment by apocas** [comment]
https://github.com/apocas/dockerode/blob/3d0df1bf0160777d2c7bc9efc37aab12fe53b6af/test/swarm.js#L136

**Comment by faraazahmad** [comment]
@apocas createService has the definition
`createService(options: {}, callback: Callback<any>): void;`, if `options` was of a new type `ServiceOpts interface`, it would be really helpful to see it in IntelliSense
