### ISSUE TITLE
Add support for Configs

### ISSUE THREAD

**Issue by zacrahm** [apocas/dockerode#402]
https://docs.docker.com/engine/api/v1.31/#tag/Config

API looks very similar to secrets

**Comment by apocas** [comment]
Done, it's in master :)

**Comment by apocas** [comment]
Will update when published.

**Comment by zacrahm** [comment]
Awesome. Thanks for the quick work!

**Comment by zacrahm** [comment]
Any thoughts on when this will be published?

**Comment by apocas** [comment]
Published in v2.5.1
