### ISSUE TITLE
[deprecation]: privileged start command

### ISSUE THREAD

**Issue by jkuri** [apocas/dockerode#403]
https://github.com/apocas/dockerode/blob/976fe4ca205a4f48cd8628f7daf796af8017c705/examples/build/run.js#L34
this gives me error `Error: (HTTP code 400) unexpected - starting container with non-empty request body was deprecated since v1.10 and removed in v1.12`

**Comment by apocas** [comment]
Fixed https://github.com/apocas/dockerode/commit/8a3e780799cbba3f1af75be2fe9eea4bb4e5246a

**Comment by jkuri** [comment]
thanks.
