### ISSUE TITLE
Add LICENSE information to the repository directly

### ISSUE THREAD

**Issue by rcjsuen** [apocas/dockerode#404]
The license is stated in the README.md file but I think it would be a good idea to also add a LICENSE or LICENSE.md file to the repository. This will give visitors the ability to easily see the project's license at the top of the repository.

![image](https://user-images.githubusercontent.com/15629116/30516386-b4211644-9b78-11e7-99cf-237b214d38a2.png)

**Comment by apocas** [comment]
https://github.com/apocas/dockerode/commit/8e52b3950300340b9ba9af54ef2cf43f9d20eb00
