### ISSUE TITLE
misleading code in the examples

### ISSUE THREAD

**Issue by roccomuso** [apocas/dockerode#405]
Most examples got this code at the beginning:

```javascript
var socket = process.env.DOCKER_SOCKET || '/var/run/docker.sock';
var stats  = fs.statSync(socket);

if (!stats.isSocket()) {
  throw new Error('Are you sure the docker is running?');
}
```
I think that's misleading.
You could have that file but the docker's daemon still off and the `stats.isSocket()` will return `true` in any case. Is that check really necessary?

**Comment by apocas** [comment]
It's an example... :)
The check isn't obligatory.
