### ISSUE TITLE
[Question] Is it possible to pipe data to a docker container without streams ?

### ISSUE THREAD

**Issue by omartrigui** [apocas/dockerode#408]
As the title says, is there any alternative to perform the following command with dockerode ? 

```shellscript
echo 'some data here' | docker run -i --rm docker/image:tag
```

I have used examples/run_stdin.js, but this method doesn't support data more than 4KB. I have tried piping my data with the previous command, and it works fine.

I appreciate any help/hints.

**Comment by apocas** [comment]
Better later than ever :) But it seems you wanted something like container.putArchive
