### ISSUE TITLE
Custom dockerfile path?

### ISSUE THREAD

**Issue by IniZio** [apocas/dockerode#412]
Hello I attempted to build a subdirectory using the directory's dockerfile by doing
```js
docker.buildImage(
  tar.pack(resolve('./', cwd)),
  {
    f: resolve('../docker-images/nodejs/Dockerfile'),
    t: settings.name
  },
  (err, output) => {
    output.pipe(process.stdout)
  }
)
```
However it seems to ignore the `f` property thus reporting error:
```
Error: (HTTP code 500) server error - Cannot locate specified Dockerfile: Dockerfile
```
Or do I have to include the Dockerfile in the tar pack already rather than setting a custom dockerfile in the options?

**Comment by Seikho** [comment]
Looking at my code that uses this, I include the Dockerfile in the tarball and provide the path by adding a `dockerfile` property on the options object.
[See here for an example](https://github.com/the-concierge/concierge/blob/master/src/api/applications/build.ts#L30)

**Comment by IniZio** [comment]
Thanks that a way to do it :+1:

**Comment by ppenelon** [comment]
3 years after....thanks @Seikho !
Here is a quick visual example for future visitors. 🥳

```javascript
await dockerode.buildImage({
    context: __dirname,
    src: ['path/to/Dockerfile', 'dependency1', 'dependency2', '...']
}, {
    t: imageName + ':' + version,
    dockerfile: 'path/to/Dockerfile'
});
```
