### ISSUE TITLE
Getting "Bad parameters and missing X-Registry-Auth: EOF" error

### ISSUE THREAD

**Issue by ManeeshSharma17** [apocas/dockerode#416]
Hi I was trying to push a docker image into an insecure private repository. 
I am getting below error -
`(node:45940) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: (HTTP code 400) unexpected - Bad parameters andmissing X-Registry-Auth: EOF
(node:45940) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
As I am working on insecure repository I was not providing any auth config.
When i tried to push by passing blank object of auth config `{ authconfig: {} }` it works fine.

**Comment by mhemrg** [comment]
Same issue here.

**Comment by apocas** [comment]
Not much we can do here.
It seems your registry returned 400 unless the auth header (X-Registry-Auth) is present.

If you don't have auth the registry shouldn't behave like this, if it does you must send the header even if it goes empty.
