### ISSUE TITLE
Can't bind ports to host machine

### ISSUE THREAD

**Issue by theolampert** [apocas/dockerode#417]
The following example config using `docker.createContainer` does not expose a port on the host machine as expected:
```js
docker.createContainer({
  Image: 'alpine',
  ExposedPorts: { '80/tcp:': {} },
  HostConfig: {
    PortBindings: { '80/tcp': [{ HostPort: '5000' }] },
  },
})
...
```

Using the following API docs https://docs.docker.com/engine/api/v1.32/#operation/ContainerCreate

**Comment by theolampert** [comment]
Update: The following using `docker.run` and `Hostconfig` instead of `HostConfig` works for me but I'm still a little confused by this and wondering why the naming differs to the official documentation.

```js
docker.run('alpine', [], process.stdout, {
  ExposedPorts: {
    '80/tcp': {}
  },
  Hostconfig: {
    PortBindings: {
      '80/tcp': [{
        HostPort: '5000',
      }],
    },
  },
})
...
```

**Comment by disarticulate** [comment]
I can't get it Binding either, with either spelling:
```
		    "Hostconfig": {
		      "AutoRemove": true,
		      "Binds": [],
		      "PortBindings": {
		      	"4222/tcp": [{ "HostPort": "4222" }],
		      	"6222/tcp": [{ "HostPort": "6222" }],
		      	"8222/tcp": [{ "HostPort": "8222" }]
		      }
		    },

```

**Comment by disarticulate** [comment]
I just found this issue upstream:
https://github.com/moby/moby/pull/35429

I have docker api v1.32 and the docker API appears to have been failing on multiple image formats.

I'm trying to upgrade now to v1.33 and see if it's fixed (1.33 is highest)

**Comment by disarticulate** [comment]
upgrade to 1.35 didn't work. Whatever the fix is, it might be problematic elsewhere.

**Comment by mingyuan-xia** [comment]
You can use `docker container inspect` to check if the created container has the right `HostConfig`.
