### ISSUE TITLE
Read service logs without stream using follow: false

### ISSUE THREAD

**Issue by extrail** [apocas/dockerode#421]
is there a way to read logs with `follow: false` without opening a stream?
as far as I know Swarm api has a follow: false that returns the response as a 200 OK with the the log string in the reply body, is there a method available for such a call?

**Comment by sigma67** [comment]
The Docker API makes it sound like it would be possible to simply return a string. Unfortunately, all working examples I've seen using this API use follow: true and streams.

**Comment by sigma67** [comment]
I've found a way to do it:

```javascript
container.logs({
		stdout: true,
		stderr: true,
		since: since
	},
	(err, result) => {
		logs = result.toString('utf8')
	}
)
```

However, you need to split the lines of the log entries yourself as it's just one long string returned by the Docker API, which is passed through by dockerode
