### ISSUE TITLE
Crash when using along with Inquirer.js

### ISSUE THREAD

**Issue by fwouts** [apocas/dockerode#426]
I recently came along a crash that only occurs with a combination of Dockerode and [Inquirer.js](https://github.com/SBoudrias/Inquirer.js).

Here is a simple example that reproduces the bug: https://github.com/fwouts/dockerode-inquirer-bug

It looks like the following code ends up in the compiled `main.js`:
```js
if(!module.parent && process.title !== 'browser') {
  process.stdin
    .pipe(exports.parse(process.argv[2]))
    .pipe(exports.stringify('[', ',\n', ']\n', 2))
    .pipe(process.stdout)
}
```

I think this ultimately comes from the JSONStream 0.10.0 package, imported by docker-modem.

Could this be solved by upgrading JSONStream to a recent version?

**Comment by apocas** [comment]
Humm we had issues after upgading JSONStream in the past.
https://github.com/apocas/dockerode/issues/142#issuecomment-109048277

I will check the current state of things :)

**Comment by apocas** [comment]
Latest version of JSONStream is working without issues.

Let's bump this.
