### ISSUE TITLE
How to add `--health-cmd='mysqladmin ping --silent'` and `--health-interval='1s'` options to createContainer() function?

### ISSUE THREAD

**Issue by githubTTest** [apocas/dockerode#427]
Does any know how to execute

`docker run --health-cmd='mysqladmin ping --silent' --health-interval='1s' --name myContainer --env="MYSQL_ROOT_PASSWORD=mypassword" -d -p 3306:3306 mysql:5.7`

with dockerode?

The following is what I have now

    const Docker = require('dockerode')
    const docker = new Docker({socketPath: '/var/run/docker.sock'})

    docker.createContainer({
      Image: 'mysql:5.7',
      name: 'myContainer',
      env: ['MYSQL_ROOT_PASSWORD=mypassword'],
      'health-cmd': 'mysqladmin ping --silent',
      'health-interval': '1s',
      HostConfig: {
        PortBindings: {
          '3306/tcp': [
            {
              HostPort: '3306'
            }
          ]
        }
      }
    }, (err, container) => {
      if (err) {
        console.error(`create err:${err}`)
      } else {
        container.start((err, data) => {
          if (err) {
            console.error(`start err: ${err}`)
          } else {
            console.log(`data: ${data}`)
          }
        })
      }
    })

`health-cmd` and `health-interval` options doesn't work. All other options work correctly.

**Comment by DenSpirit** [comment]
You are looking for a Healthcheck subobject in parameters. Please refer to [Docker API Reference for createContainer](https://docs.docker.com/engine/api/v1.32/#operation/ContainerCreate) for more options.
Your parameter object should have an additional parameter that looks like the following one:
```
Healthcheck: {
  Test: ['CMD-SHELL', 'mysqladmin ping --silent'] // your command
  Interval: 1000000000 // 1 second, in nanoseconds
}
```
