### ISSUE TITLE
How to pass prune options to pruneImages method

### ISSUE THREAD

**Issue by cmerchant** [apocas/dockerode#429]
I would like to pass the '-a' prune option to pruneImages method. I'm not specifically sure how to build the options object parameter.  Do you have any documentation or example on how to do that?

**Comment by cmerchant** [comment]
Looks like the correct way to remove unused and dangling images is by passing, { 'filters' : { 'dangling' : { 'false' : true } } }

**Comment by kiranpradeep** [comment]
As per Docker API [documentation](https://docs.docker.com/reference/api/engine/version/v1.37/#tag/Image/operation/ImagePrune), golang type is `map[string][]string`, which is equivalent to TS type 
```ts
Record<string, string[]>
```

As per it simpler example below

```ts
filters: {
  dangling: ['false'],
  until: ['24h'],
}
```
