### ISSUE TITLE
Cannot use Dockerfile using scratch image

### ISSUE THREAD

**Issue by guilherme-santos** [apocas/dockerode#433]
When I tried to build a dockerfile that uses:
```
FROM scratch
```

I receive the message `'scratch' is a reserved name`

**Comment by apocas** [comment]
https://github.com/moby/moby/issues/10737#issuecomment-74084238

**Comment by guilherme-santos** [comment]
@apocas I'm not pulling the image I'm building it. For example, to build following Dockerfile I'll get the same error...
```
FROM scratch
VOLUME /data
```

**Comment by guilherme-santos** [comment]
With this test case you can see that will fail:
```
it("should build image from scratch", function(done) {
      this.timeout(60000);

      function handler(err, stream) {
        expect(err).to.be.null;
        expect(stream).to.be.ok;

        stream.pipe(process.stdout, {
          end: true
        });

        stream.on('end', function() {
          done();
        });
      }

      docker.buildImage({
        context: __dirname,
        src: ['Dockerfile.scratch']
      }, {}, handler);
    });
```

**Comment by apocas** [comment]
Nothing we can do, Docker reserved that word :(

It's Docker that's sending that error to dockerode, dockerode is just displaying it to you.
