### ISSUE TITLE
followProgress() does not trigger onProgress() handler

### ISSUE THREAD

**Issue by jerry1100** [apocas/dockerode#439]
With the following code:
```js
const Docker = require('dockerode');
const docker = new Docker();

docker.pull('busybox:latest', (err, stream) => {
  docker.modem.followProgress(stream, onFinished, onProgress);

  function onFinished() {
    console.log('finished');
  }

  function onProgress(event) {
    console.log(event);
  }
});
```
I'd expect to see the `event` object be printed to the console as the pull progresses. However, I don't see any feedback until the pull completes and `onFinished()` is invoked.

Example:
![before](https://user-images.githubusercontent.com/18181641/36942512-a660133c-1f28-11e8-8344-40f934d255e0.gif)

**Comment by jerry1100** [comment]
It seems the issue is that modem.followProgress() is listening for the `root` event from JSON.stream.parse(), which never comes.

After some digging, I found that JSON.stream stopped emitting the `root` event in [this PR](https://github.com/dominictarr/JSONStream/pull/54).

In any case, if we change `root` to `data`, it works. [Here's a PR](https://github.com/apocas/docker-modem/pull/89) for docker-modem that does just that.

**Comment by Seikho** [comment]
the `.pull` function should return `Promise<NodeJS.ReadableStream>` or take a callback whose second parameter is a stream. 
```ts
const stream = await client.pull(`${imageName}:${tag}`, {})
stream.on('data', log.debug)
stream.on('end', () => log.info(`End pulling ${imageName}:${tag}`))
```

**Comment by jerry1100** [comment]
That works, except the `event` argument passed to the handler will be a `Buffer`, meaning I'd have to decode then parse the buffer. If I go through modem.followProgress(), I get an object to work with, which is a little more convenient.

Regardless, it still is a bug with modem.followProgress() and should be fixed. Furthermore, the example I provided is pretty much straight from the README (see [here](https://github.com/apocas/dockerode#helper-functions)).

**Comment by apocas** [comment]
docker-modem v1.0.6 published with this fix.
