### ISSUE TITLE
How to create/run container with params

### ISSUE THREAD

**Issue by SvenUlrich** [apocas/dockerode#444]
Hello,

i tried to create/run a image with the help of this repo.
Normally i would start the image this way:

`docker run --name somename  myimage --database mydbpath --secret somesecret`

My Dockerfile looks like this:
```
FROM node:carbon-slim

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --production

COPY . . 

ENTRYPOINT [ "node", "build/server.js" ]
EXPOSE 8080
CMD [ "", ""]
```

I need the params --database and --secret to be passed to the image to correctly start. With the command it runs fine but if try to use it like this:

```
docker.run(
    'myimage',
    '--database mydbpath --secret somesecret', 
    process.stdout,
    (err, data, container) => {
        if (err) {
            throw err;
        }
    }
);
```

The parameters are not passed down.
Thanks in advance for your help.

**Comment by edeuxk** [comment]
``` javascript
docker.buildImage({
			context: process.cwd(),
			src: ['Dockerfile']
		}, {
			"t": dockerimage,
			buildargs: {
				database: 'dbpath',
				secret: 'somesecret'
			}
		});
```

and inside your Dockerfile please add
ARG database
ARG secret

so you can access it inside the dockerfile with $database
