### ISSUE TITLE
Pull: get ETA

### ISSUE THREAD

**Issue by cvalenzuela** [apocas/dockerode#451]
I know followProgress(#439) allows to follow the installation process. Is there a way to get the amount of time it will take to download the image? Or an estimate?

thanks!

**Comment by cvalenzuela** [comment]
great! thanks

**Comment by DenSpirit** [comment]
Dockerode's `pull` method returns a promise that resolves to a Node stream.

`followProgress` method accepts a number of callbacks that get executed when a specific stage is reached. You can supply a callback in `onProgress` callback and in it check the time it took to download a part.
