### ISSUE TITLE
secret.update fails with "invalid secret version"

### ISSUE THREAD

**Issue by malammar** [apocas/dockerode#454]
According to https://docs.docker.com/engine/api/v1.30/#operation/SecretUpdate, the docker engine API now requires a "version" query parameter in order to update secrets. dockerode currently doesn't provide any direct way of adding query parameters:

https://github.com/apocas/dockerode/blob/9e9adde6fcbc920eedc3c9fdaeead10fcaf16496/lib/secret.js#L51

I looked at the [docker-modem source](https://github.com/apocas/docker-modem/blob/78e793b86ba3bff9dcb49464faba093baac56efc/lib/modem.js#L86
) and found that it's possible to add `_query` object to my options but it doesn't seem to work as intended. 

```javascript
const opts = {
  _query: {
    version: 1
  },
  Name,
  Labels: {},
  Data: new Buffer(`new data ${getRandomString()}`).toString('base64')
}
```

**Comment by apocas** [comment]
Sure it does :)

There's even a test with exactly this use case:
https://github.com/apocas/dockerode/blob/master/test/swarm.js#L109

**Comment by malammar** [comment]
That's perfect. Thanks for clarifying!
