### ISSUE TITLE
attach when container is offline doesnt fail?

### ISSUE THREAD

**Issue by exwizzard** [apocas/dockerode#457]
When I run `container.attach` on a stopped container and try to write to the stream everything appears to work fine without error even though the container is stopped.

If I then run `container.start` the first thing that I see is all of the text I have written into the stream appearing one by one. How exactly does this work and is there any way to prevent it?

When I try to attach from the docker cli I get an error and I would like to mimic this behavior on dockerode:
`You cannot attach to a stopped container, start it first`

I know that I can code around this problem by calling some method to check if the container is online before writing to the stream but the problem seems like a bug to me.

**Comment by apocas** [comment]
We just follow Docker API behaviour.

CLI does what you exactly described, it inspects the container first using Go driver.
https://github.com/docker/cli/blob/master/cli/command/container/attach.go#L34

If you want that behaviour you can implement it using dockerode like the CLI does with Go.
