### ISSUE TITLE
I want to catch the exec error

### ISSUE THREAD

**Issue by nithindj192** [apocas/dockerode#459]
Hi, I was trying out below code.

```
var options = {
    Cmd: ['bash', '-c', 'apt update & apt install -y jq'],
    AttachStdout: true,
    AttachStderr: true
  };

  container.exec(options, function(err, exec) {
    if (err) return;
    exec.start(function(err, stream) {
      if (err) return;

      container.modem.demuxStream(stream, process.stdout, process.stderr);
    });
  });

```
Everything works fine, but I need more control over exec . Say if the command execution goes to error, it just prints the error to console. I need to handle within the code.

Is there any way I can achieve it?

Thanks.

**Comment by DenSpirit** [comment]
If you want to inspect results of calling commands form within the container, you have to supply streams other than `process.stderr` and `process.stdout` to `demuxStream` call.
I think you could create your own Writable streams and pass them to demuxStream call.

**Comment by nithindj192** [comment]
[https://github.com/apocas/dockerode/issues/462](https://github.com/apocas/dockerode/issues/462)
