### ISSUE TITLE
exec stream isn't emitting the end event

### ISSUE THREAD

**Issue by nithindj192** [apocas/dockerode#462]
Here is the code.
```
return new Promise((resolve, reject) => {
		let attach_opts = {
			'Tty': true,
			stream: true,
			stdout: true,
			stderr: true
		};


		let data = '';
		exec.start(attach_opts, (err, stream) => {
			if (err) {
				reject(err);
			}

			stream.on('data', (chunk) => {
				data += decoder.write(chunk);
			});

			stream.on('end', () => {
				resolve(data);
			});

			container.modem.demuxStream(stream, process.stdout, process.stderr);
		});
	});
```

For the first docker exec on the container , the promise will be resolved. After that it will never emit the end event.
Why is it so? Is there anything I am doing wrong?  Have tried making Tty to false. No success.

**Comment by DenSpirit** [comment]
If your Promise resolves, the 'end' event can be considered emitted, because you explicitly resolve it only when 'end' event has happened.

NodeJS streams emit 'end' only once. If you want to capture another 'end' event you have to create another stream.

**Comment by nithindj192** [comment]
Thanks much. That cleared the confusion.
