### ISSUE TITLE
getArchive outputs 'garbage' on the stream?

### ISSUE THREAD

**Issue by jjoselv** [apocas/dockerode#463]
Hi!

I'm using dockerode getArchive method and I can't manage to separate useful data from some kind of 'garbage' the 'stream?' outputs, here is an example:

![image](https://user-images.githubusercontent.com/11363119/41020064-b700aa52-6961-11e8-964a-214d05b477ca.png)

Am I missing something?

Thanks!

**Comment by apocas** [comment]
https://docs.docker.com/engine/api/v1.37/#operation/ContainerArchive

It returns a stream with the **tar** archive of the requested resource.
