### ISSUE TITLE
Pulling from private docker hub

### ISSUE THREAD

**Issue by stridentbean** [apocas/dockerode#467]
I'm trying to pull from a private docker hub, but it is requiring me to login. Is there any way to do this with dockerode? Open to suggestions, thanks!

Error
(HTTP code 404) unexpected - pull access denied for ********/*******, repository does not exist or may require 'docker login'

**Comment by P4sca1** [comment]
Yes, there is:

```
const auth = {
	username: 'yourUsername',
	password: 'yourPassword',
	serveraddress: 'https://index.docker.io/v1'
};

this.controller.pull('yourImage', { authConfig: auth }, (err, stream) => {
	//
});
```

If you are using something like [dotenv](https://github.com/motdotla/dotenv) you could also store your username and passsword in a `.env` file. Your `authConfig` would then look like this:
```
const auth = {
	username: process.env.DOCKER_USERNAME,
	password: process.env.DOCKER_PASSWORD,
	serveraddress: 'https://index.docker.io/v1'
};
```

**Comment by apocas** [comment]
:+1:

**Comment by ghostbuster91** [comment]
It look like the authConfig has to be all lower case:
```
this.controller.pull('yourImage', { authconfig: auth }, (err, stream) => {
	//
});
```
