### ISSUE TITLE
Encoding issues with returned data from muxed service logs

### ISSUE THREAD

**Issue by shawnhwei** [apocas/dockerode#469]
When getting service logs NOT as a stream (e.g. `{ stdout: true, stderr: true, tail: 100}`) it seems like the callback data is fully encoded as utf8 (including frame headers). This makes it annoying to demux it yourself.

When I do an http.get() instead and create a buffer without encoding the data, then I can demux easily with a for loop.

This does NOT work (logs are preceded by gibberish in stdout):
```javascript
  let manager = new Docker({
    host: address,
    port: 2375
  });

  try {
    var service = await manager.getService(serviceName);
  } catch (err) {
    throw err;
  }

  try {
    var logs = await service.logs({
      stdout: true,
      stderr: true,
      tail: 10
    });
  } catch (err) {
    throw err;
  }

  let buffer = Buffer.from(logs, "utf8");

  for(let i = 0; i < logs.length; i) {
    let header = buffer.slice(i, i + 8);
    let size = header.readUInt32BE(4);

    i += 8;

    process.stdout.write(buffer.slice(i, i + size).toString());

    i += size;
  }
```

This does work (clean output):
```javascript
  let url = `http://${address}:2375/services/${serviceName}/logs?stdout=true&stderr=true&tail=10`;

  try {
    var logs = await new Promise((resolve, reject) => {
      http.get(url, (res) => {
        if (res.statusCode !== 200) {
          console.log(JSON.stringify(res));
          reject("blah");
        }

        let data = [];

        res.on("data", (chunk) => {
          data.push(chunk);
        });

        res.on("end", () => {
          resolve(Buffer.concat(data));
        });
      });
    });
  } catch (err) {
    throw err;
  }

  for(let i = 0; i < logs.length; i) {
    let header = logs.slice(i, i + 8);
    let size = header.readUInt32BE(4);

    i += 8;

    process.stdout.write(logs.slice(i, i + size).toString());

    i += size;
  }
```

**Comment by apocas** [comment]
dockerode can demux the stream for you:
https://github.com/apocas/dockerode#helper-functions

If you want to implement a demuxer yourself you can even check the demux function dockerode uses:
https://github.com/apocas/docker-modem/blob/master/lib/modem.js#L289

**Comment by shawnhwei** [comment]
I saw this, my case is a response which is NOT a stream: getting muxed service logs without the follow option.

**Comment by shawnhwei** [comment]
@apocas If you call `service.logs()` without the "follow" option, then `demuxStream()` is useless as the value returned to the callback is a mix of utf-8 encoded string and the binary headers. IMO if stdout and stderr are requested, then maybe a Buffer should be returned.
