### ISSUE TITLE
Current concat-stream version has a security vulnerability

### ISSUE THREAD

**Issue by zachdini** [apocas/dockerode#474]
According to https://www.npmjs.com/advisories/597 versions of concat-stream less than v1.5.2 are vulnerable to memory exposure. We use dockerode on my team and my company does not allow us to push changes that contain vulnerabilities.

Will someone be able to update concat-stream to v1.5.2 or later? Or, will you accept a PR from me which updates it?

Thanks!

**Comment by zachdini** [comment]
Just following up - I realized that package-lock already has v1.5.2. Seems that I preemptively raised this issue. Would it be worth while to bump the version in package.json to ~1.5.2?

**Comment by Junkern** [comment]
Can be closed due to https://github.com/apocas/dockerode/pull/476
