### ISSUE TITLE
demuxed streams do not fire the data event

### ISSUE THREAD

**Issue by P4sca1** [apocas/dockerode#479]
When attaching to a container with `stdin`, `stdout` and `stderr`, it seems to be not possible to demux the stream using the following code:

```
const containerStream = await container.attach({ 
	stream: true, stdin: true, stdout: true, stderr: true
})

const stdout = new stream.PassThrough()
const stderr = new stream.PassThrough()
container.modem.demuxStream(containerStream, stdout, stderr)

stdout.on('data', chunk => {
	// never called
})

stderr.on('data', chunk => {
	// never called
})

this.stream.on('data', chunk => {
	// data gets received
})
```

Removing `stdin: true` does solve the issue.

**Comment by P4sca1** [comment]
Okay, after some more testing this does not seem to be related to `stdin`, like I initially expected.
Is there anything wrong with the code?

**Comment by pkit** [comment]
Oh, that's cool.
Just a hint: it is called once, on the stream end.
Just try to shutdown the container and you will receive the 'data' (all of it in one package).
Good to know that it's a dockerode bug

**Comment by sepehr-laal** [comment]
I just encountered this bug as well. the data event is never fired for demuxed streams. is there a way to get the stream's data event working as the container is writing to its stdout/stderr (without waiting for container to exit) ?

**Comment by pkit** [comment]
Got it working like this. AFAIR tty mangling in the `createContainer()` was the culprit.

	function containerLogs(container) {
		const logStream = new stream.PassThrough();
		logStream.on('data', function(chunk){
			logger.info(chunk.toString('utf8'));
		});

		container.logs({
			follow: true,
			stdout: true,
			stderr: true
		}, function(err, stream){
			if(err) {
			    return logger.err(err.message);
			}
			container.modem.demuxStream(stream, logStream, logStream);
			stream.on('end', function(){
			    logStream.end(logger.info('!stop!'));
			});
		});
	}

	container = await docker.createContainer({
		Image: image,
		AttachStdin: false,
		AttachStdout: true,
		AttachStderr: true,
		Cmd: cmd,
		OpenStdin: false,
		StdinOnce: false,
	});

	await container.start();
	containerLogs(container);

**Comment by P4sca1** [comment]
I don’t know if this is related, but I noticed that when there is no data listener on a stream, the end event is also never fired.
