### ISSUE TITLE
First 8 characters of container log missing

### ISSUE THREAD

**Issue by stalleyj** [apocas/dockerode#482]
Using the container.logs api, I am not getting the full log as the first 8 characters are missing.

**Comment by apocas** [comment]
Are you demuxing the streaming properly?

**Comment by stalleyj** [comment]
I'm following the example code as below:-

function containerLogs(container) {

  // create a single stream for stdin and stdout
  var logStream = new stream.PassThrough();
  logStream.on('data', function(chunk){
    console.log(chunk.toString('utf8'));
  });

  container.logs({
    follow: true,
    stdout: true,
    stderr: true
  }, function(err, stream){
    if(err) {
      return logger.error(err.message);
    }
    container.modem.demuxStream(stream, logStream, logStream);
    stream.on('end', function(){
      logStream.end('!stop!');
    });

    setTimeout(function() {
      stream.destroy();
    }, 2000);
  });
}

**Comment by apocas** [comment]
I can't replicate this.
