### ISSUE TITLE
Container run timeout.

### ISSUE THREAD

**Issue by hifall** [apocas/dockerode#493]
I need to run untrusted code in containers, and some of the code could run infinitely. I'd like to implement a hard run timeout for containers, beyond which they will be stopped and removed, freeing up resources.

Per this discussion, there is no flag in Docker that imposes this limit: [#1905](https://github.com/moby/moby/issues/1905). And I don't see their intention of implementing it. However, we can do this in Dockerode.

I think such an implementation should be simple: in docker.js' runCallback/runPromise, simply pass a timeout; before starting the container, set up a timer to stop and remove the container after timeout.

Does it make sense to you?

**Comment by apocas** [comment]
This should be done in "userland".

Simplest way is doing a setTimeout around run which triggers container.stop and remove.
