### ISSUE TITLE
Unable to create volume with 2.5.4

### ISSUE THREAD

**Issue by ceecko** [apocas/dockerode#495]
Starting with version `2.5.0` creating volume fails:

```
const Docker = require('dockerode')
const docker = new Docker({
  socketPath: '/var/run/docker.sock',
})

docker.createVolume({}, (err, volume) => {
  if(err) {
    console.trace(err);
    return;
  }

  console.log('ok')
})
```

This returns error `Error: (HTTP code 400) unexpected - got EOF while reading request body`

Docker version `18.06.1-ce`
Works ok with `v2.4.3`

**Comment by apocas** [comment]
I can't replicate this.
Tried 18.09.0-ce-beta1

**Comment by ceecko** [comment]
Strangely I ran into the same issue again just now.
Running dockerode `2.5.8` or `3.1.0` with Docker `19.03.8` and `overlay2` storage engine on `CentOS 7` I still get the HTTP 400 error.

This does not happen with dockerode `2.4.x` though

**Comment by ceecko** [comment]
Almost exactly a year later :)
@apocas I replicated this with `3.2.1` and node `14.14.0` on a fresh installed system with CentOS 7.

Would you like any debugging data to figure out what's going on?

**Comment by ceecko** [comment]
And I replicated this with Ubuntu 20.04.1 LTS with kernel `4.19.104-microsoft-standard` and docker `20.10.2`

**Comment by apocas** [comment]
Weird error. I still can't replicate it.
Do you have any more data? :/

**Comment by ceecko** [comment]
I figured what if the API endpoint requires some data? With data, it actually works. Maybe it is the missing `Content-Type` header which breaks it?

Not working example without any arguments:
```
DEBUG=* node test
  modem Sending: {
  path: '/volumes/create',
  method: 'POST',
  headers: {},
  key: undefined,
  cert: undefined,
  ca: undefined,
  socketPath: '/var/run/docker.sock'
} +0ms
  modem Received: {"message":"got EOF while reading request body"}
 +5ms
```

Working example with `{name: 'some-test'}`:
```
DEBUG=* node test.js
  modem Sending: {
  path: '/volumes/create?name=some-test',
  method: 'POST',
  headers: { 'Content-Type': 'application/json', 'Content-Length': 20 },
  key: undefined,
  cert: undefined,
  ca: undefined,
  socketPath: '/var/run/docker.sock'
} +0ms
  modem Received: {"CreatedAt":"2021-04-05T16:50:50Z","Driver":"local","Labels":null,"Mountpoint":"/var/lib/docker/volumes/some-test/_data","Name":"some-test","Options":null,"Scope":"local"}
 +7ms
ok
```

**Comment by apocas** [comment]
Cool, you actually found an old docker-modem bug :D

Yes you are right, headers are missing in that situation.

Culprit: https://github.com/apocas/docker-modem/blob/master/lib/modem.js#L178

Going to check it out.

**Comment by ceecko** [comment]
I'm glad we managed to figure this out :)
Maybe a simple `allowEmpty: true` here would work? https://github.com/apocas/dockerode/blob/master/lib/docker.js#L1018

**Comment by apocas** [comment]
Yes it works :)
Just pushed an improved test and fix.
It will be published in the next version.
