### ISSUE TITLE
Find port numbers for stopped containers

### ISSUE THREAD

**Issue by justweb1** [apocas/dockerode#497]
I'm trying to programatically pull all of the exposed or public ports from the existing containers running or not. Then I will assign available port numbers within a range automatically to new containers. I however have only been able to find port numbers for active containers using the available api. I would like to find the ExposedPorts property as it shows for both started and stopped containers.

**Comment by P4sca1** [comment]
`container.inspect()` works on stopped containers. Maybe something like this could work (not tested):

```
const container = Dockerode.getContainer('id or name here')
const data = await container.inspect()
console.dir(data.Config.ExposedPorts)
```

**Comment by justweb1** [comment]
I was able to find it in `container.inspect` under `data.HostConfig.PortBindings`. Thank you.
