### ISSUE TITLE
Snyk says dockerode has a vulnerability

### ISSUE THREAD

**Issue by nt1m** [apocas/dockerode#499]
See https://snyk.io/test/github/apocas/dockerode

The vulnerability: https://snyk.io/vuln/npm:chownr:20180731

**Comment by lirantal** [comment]
Snyk addressed the vulnerability report and maintainer's comments on the issue.
Upgrading to chownr version >= 1.1.1 should not report any vulnerabilities with chownr.

**Comment by apocas** [comment]
Nothing being reported on snyk atm.
