### ISSUE TITLE
how to mount "-v //var/run/docker.sock://var/run/docker.sock" in dockerode

### ISSUE THREAD

**Issue by chrisEAH** [apocas/dockerode#500]
hey,
i want to start a container that is connectd to the docker.sock. like this:
docker run --name watchtower -v //var/run/docker.sock://var/run/docker.sock v2tec/watchtower

how to do it in node?
` dock.run('v2tec/watchtower', [], process.stdout, {
        'Volumes': {
          '/var/run/docker.sock': {"/var/run/docker.sock":"/var/run/docker.sock"}
        },
        "name":'watchtower'
       
      }, function(err, data, container) {
        if (err){
          return console.error(err);
        }
        console.log(data.StatusCode);
      });`

thank you for your help :)

**Comment by gtl-alex** [comment]
Has anyone figured this out?
