### ISSUE TITLE
how to set a `--network hosts` on docker.run

### ISSUE THREAD

**Issue by salesgu** [apocas/dockerode#501]
Hi,

I was trying to run a container which has a intranet request. Seems run the command --network=host of docker run it will works, but I can't found nothing to set this parameter.

There is a way to set this --network parameter using the lib?

Thanks a lot!

**Comment by tahayk** [comment]
@salesgu : any luck solving this issue ?

**Comment by Cherry** [comment]
Set `HostConfig.NetworkMode` to `host`.

**Comment by tahayk** [comment]
I tried that but it works only on Ubuntu, I'm trying to support windows & Mac too

**Comment by piyusharorawork** [comment]
@tahayk did u find any fix for that ?

**Comment by anselmobattisti** [comment]
api.createContainer({
                    Image: 'frame_processor',
                    Cmd: ["/bin/bash", "start.sh"],
                    HostConfig: {
                        NetworkMode: "api_express-mongo-network-sinae",
                        AutoRemove: true,
                        Binds: [
                            `/usr/uploads:/usr/uploads`
                        ]
                    }

**Comment by salesgu** [comment]
> @salesgu : any luck solving this issue ?

I've tested on Ubuntu, but using "HostConfig" works. 

`
{
    HostConfig: {
        NetworkMode: "host"
    }
 } `

In fact I see the [readme](https://github.com/apocas/dockerode#equivalent-of-docker-run-in-dockerode), and have an example also:

`
docker.run(
	'some-python-image',
	['python', 'main.py', arg],
	process.stdout,
	{
		name: 'my-python-container',
		HostConfig: { AutoRemove: true, NetworkMode: 'my_network' }
	},
	function(err, data, container) {
		// Do stuff
	}
);
`

**Comment by apocas** [comment]
Going to close this one as it seems to be tackled. Reopen if needed.
