### ISSUE TITLE
How to trigger a function when a container exits ?

### ISSUE THREAD

**Issue by tahayk** [apocas/dockerode#503]
I'm trying to trigger a function when a container exits in order to retrieve and upload the logs + do some cleaning,
but I couldn't figure out how to do it.
Thanks.

**Comment by Seikho** [comment]
You can monitor container events using `dockerClient.getEvents(...)`.
Some sample event listening code [here](https://github.com/the-concierge/concierge/blob/master/src/api/stats/hosts.ts#L33).
