### ISSUE TITLE
Docker all container STATS Rest Point without streaming

### ISSUE THREAD

**Issue by superandroid4848** [apocas/dockerode#508]
Hi ,

I would like to implement following docker query : 

**docker stats $(docker ps | awk '{if(NR>1) print $NF}') --no-stream**

Basically I want to do a REST call for fetching docker stats for all containers with container name (without streaming)

Can anyone help me to get this done ? 

P.S. -  I am running my node app in a docker container itself .. so I can't directly access the host machine's CMD ...

Thanks

**Comment by sergiz** [comment]
use "stream: false" option with .stats().
