### ISSUE TITLE
docker.run with empty Cmd

### ISSUE THREAD

**Issue by 3p3r** [apocas/dockerode#510]
most of my containers have a default baked in command (`CMD` command inside Dockerfile). When I use dockerode's `docker.run` method with an empty `cmd` argument, it throws HTTP 400 complaining about the command argument missing. I tried passing `null`, `''`, and `['']` as well and they all fail.

Is it possible to use dockerode's `docker.run` with a container's default baked in command?

Thanks!

**Comment by sepehr-laal** [comment]
I figured I can use `image.inspect` api to extract the default command of a pulled container. I'll leave this open if there's a better way, otherwise it's solved for me.
