### ISSUE TITLE
Docker logs Demuxing

### ISSUE THREAD

**Issue by thelamer** [apocas/dockerode#511]
It looks like in a recent update if "follow" is set to false when grabbing container logs you get back a buffer.
That is fine, but even converted to utf8 I am having trouble figuring out a reliable method of removing just the logstream for parsing, used to use "ansi_up.ansi_to_html" in combination with the demuxed logStream to parse it to a reliable readable output. 

Does anyone have any suggestions or are there any plans to add a function call to demux this buffer?

**Comment by mhemrg** [comment]
Same issue after upgrading to `2.5.8` from `2.5.4`.

**Comment by apocas** [comment]
Update dockerode's dependency docker-modem to v1.0.9 (just published it)

It should fix the problem.

**Comment by thelamer** [comment]
When you say it should fix the problem are you saying we can use the same `container.modem.demuxStream` function call on the return from an unfollowed logset? 
Updated I still get a buffer and if I try to put that through demux I get a no trace crash. 

Sorry I gotta go full pleb status here, do you have a modified example of this without following the output https://github.com/apocas/dockerode/blob/master/examples/logs.js ?

**Comment by larshp** [comment]
Having similar issue, using 2.5.8

**Comment by thelamer** [comment]
closing as it is not the responsibility of the maintainer to give me code examples.
