### ISSUE TITLE
Issue converting docker bash command to dockerode

### ISSUE THREAD

**Issue by albertoxamin** [apocas/dockerode#514]
How can I convert this command to make it fully work with dockerode?

```bash
docker run --name vtiger_${name} -d -e DB_HOSTNAME=${db_host} -e DB_USERNAME=${db_user} -e DB_PASSWORD=${db_pwd} -e DB_NAME=${name} -p ${chosen_port}:80 --net=asgard ldavid/vtiger7
```

i tried this but it doesn't seem to be fully working

```javascript
let chosen_port = {}
chosen_port[`${available_ports[0]}/tcp`] = {}
docker.createContainer({
	Image: 'ldavid/vtiger7',
	Env: [
		'DB_HOSTNAME='+db_host,
		'DB_USERNAME='+db_user,
		'DB_PASSWORD='+db_pwd,
		`DB_NAME=${req.body.name}`
		],
        name: `vtiger_${req.body.name}`,
	ExposedPorts: chosen_port
	}).then(function (container) {
	container.start()
}
```

**Comment by apocas** [comment]
Could you describe the problem in more detail?

**Comment by albertoxamin** [comment]
I don't really remember it clearly right now, I ended up creating a bash script however it was either the container not created or not started

**Comment by francescobianco** [comment]
Seems off-topic but I suggest to see my image for1 a different point of view 
https://github.com/javanile/vtiger use native MYSQL ENV vars is better @albertoxamin @apocas
