### ISSUE TITLE
deploying on heroku with dockerode

### ISSUE THREAD

**Issue by erinakii** [apocas/dockerode#515]
Hi 

Awesome library! I was able to implement docker on the back end of my express router, where I can pass a script to the backend and have it run on an instance of a new container. 

However, when I try to deploy my app on heroku, it doesn't seem to be able to use dockerode. Any tips or ideas? I have the dock hero add-on. 

(Note: I am not deploying my whole app on docker, rather I am creating an instance of a container in a router that spins out a docker container which runs a shell script)

**Comment by apocas** [comment]
Humm never tried to use dockerode on Heroku, but it shouldn't be a problem.

Where is the docker instance you are using while running in heroku?
It could be related with privileged containers while running locally vs heroku.
