### ISSUE TITLE
Is there any mechanism to reduce RAM usage by docker or to release docker memory cache?

### ISSUE THREAD

**Issue by chinju** [apocas/dockerode#517]
Hi,

I have a nodejs application to run an emulator in docker container and found that memory usage is high when the docker container is running and my PC gets hang or job is failing.

I have removed all the unused resources like stopped containers, volumes, etc before running the job. But it doesn't help me.

Is there any mechanism in dockerode to reduce memory usage or release docker memory cache
(I want to keep docker image) or dropping memory cache automatically?

Note: I do not want to remove docker image.

Thanks in advance

**Comment by apocas** [comment]
dockerode simply uses Docker's API to manage it programatically.
Unfortunately there isn't anything we can do about that in dockerode.
