### ISSUE TITLE
Feature request: add support for 'docker cp'

### ISSUE THREAD

**Issue by matsev** [apocas/dockerode#527]
Add support for [docker cp](https://docs.docker.com/engine/reference/commandline/cp/) to tranfer files between the Docker host and a container.

Dockerode has support for transferring file archives between the Docker host and the container (using the `container.getArchive()` and the `container.putArchive()` functions). One drawback for these functions is that they require the files to be transferred to be .tar archives. Admittedly, there are JavaScript libraries that support the packaging and un-packaging of .tar files, e.g. [tar](https://www.npmjs.com/package/tar). That said, there is still some extra complexity added that need to be solved compared to what `docker cp` offers for simple file transfers, such as sure that the file paths in the .tar file will be correct when unpacked, temporary .tar files that needs to be deleted, etc.

**Comment by jakowenko** [comment]
Would love this feature as well, I have two running containers and I’m looking for a way to copy a file from one to another.

**Comment by pachkovska** [comment]
Also would love this feature.

**Comment by dedsec29** [comment]
Commenting to "unstale" this feature request. It would be very beneficial to have "docker cp" support to dockerode.

**Comment by neuropacman** [comment]
Is this feature available yet or will it ever be?

**Comment by Rhahkeem** [comment]
Came here looking for this same feature
