### ISSUE TITLE
Inconsistent promise API for exec.start()

### ISSUE THREAD

**Issue by matsev** [apocas/dockerode#529]
I propose that the `resolve` method of the promise returned by `start.exec()` should be called with a stream so that it is consistent with the stream argument when the function is used with a callback, `stream.exec(callback)`.

The `callback` in the [exec.start(opts, callback)](https://github.com/apocas/dockerode/blob/master/lib/exec.js#L21) function is defined as your typical node `callback` (or `function(err, stream)` as per example in the [Stream goodness](https://github.com/apocas/dockerode#streams-goodness) chapter). When used as a callback, it is indeed a node stream. Typically, you expect the same object to be passed as an argument if you work with promises instead, e.g. one would expect this to be true:

```
const promise = exec.start(opts)
    .then(stream => {
         // do something with the stream
    });
```

However, it turns out that the `stream` object is in fact an `Exec` object where the `stream` has been added as an `output` property. Thus, this snippet reflects the current implementation:

```
const promise = exec.start(opts)
    .then(exec => {
         const stream = exec.output;         // <- why not pass the stream directly?
         // do something with the stream
    });
```

----

Ref: [see the exec.start() implementation](https://github.com/apocas/dockerode/blob/master/lib/exec.js#L49-L50)

dockerode version: 2.5.8

**Comment by apocas** [comment]
This was identified in: https://github.com/apocas/dockerode/issues/486

Will release a new major this weekend improving this.
