### ISSUE TITLE
putArchive processing tar file(exit status 1): unexpected EOF

### ISSUE THREAD

**Issue by andydean565** [apocas/dockerode#535]
have an issue when trying to copy a file from my node server which is created from a string using 'fs' in a tmp dir but keep getting the same error.

> Error processing tar file(exit status 1): unexpected EOF         0, json: null }
[Node]     at  \node_modules\docker-modem\lib\modem.js:257:17

here is the code im using to create the docker container and then create and copy the file into the container.

`fs.writeFile('./tmp/attempt.java', code, (async (err) => {
      console.log(err);
      if (err) {
        return
      }
      let container = await docker.createContainer({
        Image: 'openjdk',
        Tty: true,
        StdinOnce: true
      });
      await container.start();
      try {
        await container.putArchive('./tmp/attempt.java', {
          path: '/'
        });
      } catch (error) {
        console.log(error);
      }
    }));`

**Comment by apocas** [comment]
Docker's putArchive expects a .tar file :)

https://docs.docker.com/engine/api/v1.40/#operation/PutContainerArchive

"The input stream must be a tar archive compressed with one of the following algorithms: identity (no compression), gzip, bzip2, xz."
