### ISSUE TITLE
CreateContainer does not return container id.

### ISSUE THREAD

**Issue by natlibfi-jonollil** [apocas/dockerode#539]
On version 2.5.8 code bellow logs nicely:
`debug: ID of started import container: 8beefd122a0cedee64e59b0c845ac87501ad32c99ebeca992cc372d6b91118ed`

After update to 3.0.2 (even when container has been successfully created & started)
`debug: Creation of import container has failed`

I tried to check any changes, but could not find one to affect this.
Also tied to print variables `info` and `cont` but they were empty.
Any ideas why this is happening?

Thanks!

```
async function dispatchContainer({docker, type, blob, profile, options, template}) {
	const manifest = {
		Image: options.image,
		...clone(template)
	};

	manifest.Labels.blobId = blob;
	manifest.Labels.profile = profile;
	manifest.Env.push(`PROFILE_ID=${profile}`);
	manifest.Env.push(`BLOB_ID=${blob}`);

	getEnv(options.env).forEach(v => manifest.Env.push(v));

	const cont = await docker.createContainer(manifest);

	await attachToNetworks();

	const info = await cont.start();

	if (info.id === undefined) {
		logger.log('debug', `Creation of ${type} container has failed`);
	} else {
		logger.log('debug', `ID of started ${type} container: ${info.id}`);
	}

	function getEnv(env = {}) {
		return Object.keys(env).map(k => `${k}=${env[k]}`);
	}

	async function attachToNetworks() {
		return Promise.all(CONTAINER_NETWORKS.map(async networkName => {
			const network = await docker.getNetwork(networkName);
			await network.connect({
				Container: cont.id
			});
		}));
	}
}
```

**Comment by apocas** [comment]
You please print and check the start error?
If no container id was returned, promise was rejected and there will an error.

**Comment by natlibfi-jonollil** [comment]
I tried to print: cont & info but both were just empty. Also tried to catch an error with no luck.
