### ISSUE TITLE
buildImage with context that honours dockerignore

### ISSUE THREAD

**Issue by zoidbergwill** [apocas/dockerode#545]
Based on the following issue, I'm using a tar from the necessary dir: https://github.com/apocas/dockerode/issues/432

However I wanna honour people's `.dockerignore`.

Is there a way to do this with the library, or would I have to parse the `.dockerignore` myself?

**Comment by zoidbergwill** [comment]
So the two approaches, if you're gonna implement it yourself, are the following:

You could use `tar-fs`'s  `pack`'s `ignore` option, and load the `.dockerignore` patterns and iterate them all there, but since`.dockerignore` supports globbing, I ended up generating the list of entries first instead, and then using the `entries` option for `pack` instead.

```js
#!/usr/bin/env node
const glob = require('fast-glob');
const fs = require('fs-extra');
const path = require('path');
const tar = require('tar-fs');

async function main() {
  let ignorePatterns = await fs.readFile('.dockerignore');
  
  const ignores = [];
  for (const pattern of ignorePatterns.toString().split('\n')) {
    let line = pattern.trim();
    if (line.startsWith('/')) {
      line = line.slice(1)
	}
    if (line.startsWith('#')) {
      continue
    }
    if (line.length == 0) {
		continue
	}
    ignores.push(line);
  }
  
  let entries = await glob('**', {ignore: ignores});
  
  var pack = tar.pack(process.cwd(), {entries})
```

**Comment by JoshWillik** [comment]
It looks like tar-fs supports an `ignore` callback.

@apocas Are you planning to add support for respecting `.dockerignore`?
If not, would you accept a PR that adds support for `docker.buildImage({ignore})`?
Adding my own directory walking code to generate `entries` feels a bit messy.
