### ISSUE TITLE
Pull image promise resolves before image available.

### ISSUE THREAD

**Issue by SkeLLLa** [apocas/dockerode#550]
Hi. Here's an example for reproduce the bug.

```
const Docker = require('dockerode');
const docker = new Docker({socketPath: '/var/run/docker.sock'});

(async () => {
  try {
    await docker.pull('ubuntu:latest', {});
    const data = await docker.run('ubuntu:latest', ['bash', '-c', 'uname -a'], [process.stdout, process.stderr], {Tty:false});
    process.stdout.write('Ok', data);
  } catch(err) {
    console.error('Error', err);
  }
})()
```

Steps to reproduce:
1) Exec `docker system prune -a` to remove all images and perform clean test.
2) Run code above for the first time
```
Error: (HTTP code 404) no such container - No such image: ubuntu:latest 
    at /test-app/node_modules/docker-modem/lib/modem.js:296:17
    at getCause (/test-app/node_modules/docker-modem/lib/modem.js:326:7)
    at Modem.buildPayload (/test-app/node_modules/docker-modem/lib/modem.js:295:5)
    at IncomingMessage.<anonymous> (/test-app/node_modules/docker-modem/lib/modem.js:270:14)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  reason: 'no such container',
  statusCode: 404,
  json: { message: 'No such image: ubuntu:latest' }
}
```
3) Run for the second time - and all will be fine.

I've also check if that's not some local docker issue. If I run `docker pull ubuntu && docker images` and ubuntu image is present in command output. However if I run example code above and stop in a breakpoint just after `await docker.pull('ubuntu:latest', {});` and run `docker images`, then `ubuntu` image appears there after 3-4 seconds.

**Comment by gajus** [comment]
@SkeLLLa What was the solution?

**Comment by gajus** [comment]
Seems like you need to wait until `onFinish`.

https://github.com/apocas/dockerode/issues/357#issuecomment-294511810
