### ISSUE TITLE
buildImage() promises sometimes never resolve

### ISSUE THREAD

**Issue by gautaz** [apocas/dockerode#553]
Hello,

I am currently hitting an issue where some image builds never finish.

While pinning down the issue, I have found that neither the `end` event nor the `error` event are emitted by the stream by instrumenting the dockerode source code, in particular these lines:

https://github.com/apocas/dockerode/blob/15b6ed556c80b654662bfffce524cf96b2c105f7/lib/docker.js#L310-L315

@neophob Looking at the github history, you have already dug into this, do you have any idea why this can happen or how I can diagnose this issue?

I wanted to provide a simple code example for this but the issue seems hard to reproduce depending on where the code is deployed (the original source code itself also runs in a Docker container but the issue can only be reproduced on particular hosts).

Even on hosts where the issue is reproduced, it happens randomly. All I can tell is that multiple successive or parallel builds are needed to reproduce the issue (I was first operating parallel builds but serializing them did not fix the issue).

**Comment by apocas** [comment]
Same as https://github.com/apocas/dockerode/issues/538

**Comment by gautaz** [comment]
@apocas Yes I am using followProgress and the build contexts for the images I'm building are just a few kilobytes so I am not sure this is related to #538.

For now I have found a work-around by adding a transform stream that just forwards the chunks between the tar-fs stream and the gzip stream...

**Comment by apocas** [comment]
Wow thats indeed weird.

**Comment by gautaz** [comment]
Spring cleaning time!
There is no need to keep this issue anymore, feel free to reopen a new one if needed.
