### ISSUE TITLE
container.stats() returns Promise<IncomingMessage>

### ISSUE THREAD

**Issue by srolel** [apocas/dockerode#555]
When calling `container.stats()`, I'm getting a promise of an IncomingMessage, however index.d.ts that comes with the package says it should be `Promise<ContainerStats>`.

**Comment by apocas** [comment]
From where does that index.d.ts comes from?
I don't dive into TypeScript :)

**Comment by Seikho** [comment]
Will need to raise a PR on DefinitelyTyped. My own code that consumes the Container.stats() says it returns a stream that emits a buffer which is raw json which needs to be JSON.parsed which is _then_ `ContainerStats`.

**Comment by Mosho1** [comment]
Ah, I see, thanks. @Seikho where do your type definitions come from?

**Comment by qfdk** [comment]
Hi,
I have checked the Docker officiel documentation, yes, the stream option is `true` by defalut.

If you want to get the simple data,
just do that,

```javascript
const res = await Container.stats({stream:false});
```

**Comment by FilipHarald** [comment]
I bumped in to this problem as well. For anyone else that ends up here, if you want to just use it as an async call you can do like this:
```
const containerStats = await container.stats({stream: false});
```

**Comment by HonmaMeikodesu** [comment]
> I bumped in to this problem as well. For anyone else that ends up here, if you want to just use it as an async call you can do like this:
> 
> ```
> const containerStats = await container.stats({stream: false});
> ```

it works, tks a lot. never had thought type definition would cheat me until debugger told me it really was
