### ISSUE TITLE
docker.run closes the streams when the container stops if Tty: false

### ISSUE THREAD

**Issue by kevinlul** [apocas/dockerode#559]
Following the example in the [README](https://github.com/apocas/dockerode#equivalent-of-docker-run-in-dockerode) to separate stdout and stderr for docker.run, after the promise resolves or the callback is called, the streams are closed. This shuts off the entire process' outputs. A subsequent call to docker.run in the same fashion will eventually crash the process with ERR_STREAM_WRITE_AFTER_END, since stdout and stderr were closed.

**Comment by adamburgess** [comment]
Had this same problem...
easy fix is to use a passthrough so the final stream isn't closed:
```js
const stdout = new stream.PassThrough();
stdout.pipe(process.stdout, { end: false });

docker.run(..., [stdout, stdout], ...);
```
this doesn't really seem to be dockerode's fault fyi, process.stdout/err don't get closed when you pipe to them, only when you explicitly call `end()`. Like, even if you use <pre>stdout.pipe(process.stdout, { end: <b>true</b> })</pre> stdout will still stay open... https://github.com/nodejs/node/issues/7606#issuecomment-231293476

**Comment by kevinlul** [comment]
At least the README should be updated, maybe to match your sample, because if example usage ends up causing bad behaviour then it makes for a poor example.
