### ISSUE TITLE
dockerode minimist moderate severity vulnerability

### ISSUE THREAD

**Issue by zucatti** [apocas/dockerode#562]
found 1 moderate severity vulnerability in dockbrode dependency

Keep up the good work !

**Comment by apocas** [comment]
Yes I'm aware, it is a dependecy of a dockerode's devDependecy (**mocha**).

Currently latest **mocha** version still depends of the affected version of minimist.

**Comment by bwateratmsft** [comment]
Looks like it's also a dependency of tar-fs, so not only a dev dependency.

**Comment by apocas** [comment]
You are right!
Sorry "npm ls" mislead me :/
