### ISSUE TITLE
createContainer hangs if a number is provided in the options.

### ISSUE THREAD

**Issue by babel5405** [apocas/dockerode#563]
If a number is passed without converting it to a string via .toString() the function appears to never fire the callback. I could understand throwing an error if it must be a string but since it fails to do anything it creates issues. (I'm aware Dockerode supports Promises and have chosen intentionally to use the callback versions.)

Below isn example I quickly made and tested in my application.

```
async CreateContainer() {

        return new Promise((resolve, reject) => {
            this.docker.createContainer({
                name: "example",
                Image: "unbuntu",
                Labels: {
                    example: 1
                }
            }, function (err, container) {
                if (err) {
                    reject(err);
                } else {
                    resolve(container);
                }
            });
        });
    }
```

I have this working in my application by converting the number to a string before running the function.

**Comment by alexkli** [comment]
Similar issue here, if I provide any bad input, where I assume the docker daemon responds with an error (which I can only see that there is no container started by looking at `docker ps`), it does not resolve the `createContainer()` promise. I would expect it to reject it.

**Comment by alexkli** [comment]
FWIW, I tried to debug it, but in [modem.js](https://github.com/apocas/docker-modem/blob/master/lib/modem.js) buildRequest() (from the `docker-modem` dependency, where it makes the request to the docker daemon), it neither hits breakpoints I set in `response` or `error` events. Either there is some bug in docker-modem, or it's the normal behaviour of the docker daemon to not respond to invalid requests?

**Comment by jasondalysb** [comment]
Same issue here.  Enclosing the port number in quotes (i.e. "80") avoids the issue and can be used as a workaround, although it would be good if an error was thrown in this scenario (i.e. if an integer value is invalid) as opposed to the API call hanging.
