### ISSUE TITLE
How to use the API of dockenode

### ISSUE THREAD

**Issue by kangerts** [apocas/dockerode#566]
Hello, why do I call your program? When a page is introduced into it, I open this page many times. If I use the method 'docker. Getevents()' at this time, the returned data is the number of times I enter this page multiplied by this data (that is, repeated data display). I have been trying to solve this problem, but I have no idea. I hope you can help me!
![How to use the API of dockenode](https://user-images.githubusercontent.com/61531911/78363581-90c95000-75ee-11ea-8a04-cdd2e007463f.png)

**Comment by apocas** [comment]
Check the examples, best place to start.
https://github.com/apocas/dockerode/tree/master/examples
