### ISSUE TITLE
Could not connect to remote docker server

### ISSUE THREAD

**Issue by davidkhala** [apocas/dockerode#568]
Configured as documented, but the connection fallback to target local host instead of a remote host
No matter how I set host or port (even with those non-exist ones)

**Influenced environment**
dockerode@3.2.0
Docker version 19.03.8,

**Comment by rystaf** [comment]
#540

**Comment by davidkhala** [comment]
I get it fixed by explicitly setting protocol to be 'ssh', but then another question is, why http(s) protocol is default? 
Most google returned search results about `access remote docker host` use DOCKER_HOST env variable starting with `ssh://`.

**Comment by apocas** [comment]
#540 was fixed.

SSH support in the Docker Remote API is way more recent than HTTP, that's why :)
dockerode was created when Docker's Remote API was very very young, few years ago.
