### ISSUE TITLE
Creating a service including private registry credentials

### ISSUE THREAD

**Issue by kartsims** [apocas/dockerode#575]
I am trying to use the `docker.createService` to create a service based on an image located in a private registry. The service tasks will be started on a worker (where root has access to the private registry for that matters).

When I start the service on the CLI, with the `--with-registry-auth` flag it works fine (since the credentials are passed from the manager), but I can't get it working via Dockerode...

There is an `X-Registry-Auth` header that can be passed according to the [Docker docs](https://docs.docker.com/engine/api/v1.37/#operation/ServiceCreate) but I am not even sure if that's what should be done, and if dockerode is able to pass it through. I successfully pulled images via dockerode using the `authConfig` option, but didn't find an equivalent for creating services.

I don't think there's support for this feature on Dockerode but I'd be happy to be proven wrong :)

**Comment by Kais-ben-youssef** [comment]
Same issue here ! could you fix this please ?

**Comment by marcschroeder** [comment]
Some issue here

**Comment by paulo-digital** [comment]
Same issue here, any update?

**Comment by paulo-digital** [comment]
I was checking the `docker.createService` [prototype](https://github.com/apocas/dockerode/blob/master/lib/docker.js) and it is:
```
/**
 * Creates a new service
 * @param {Object}   auth
 * @param {Object}   opts     Create options
 * @param {Function} callback Callback
 */
Docker.prototype.createService = function(auth, opts, callback)
```

So, I'm trying something like this:

```
var auth = {
  username: 'username',
  password: 'dockerhub-token',
};

await docker.createService(auth, {...service-config...});
```

I'll post my results later.

**Comment by marcschroeder** [comment]
Hey @paulo-digital,

great! Cool that you figured that out.
I created a pull request on DefinitelyTyped. Would one of you like to have a look at it?
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50486

I tested it locally and it looks like it actually worked fine.

**Comment by paulo-digital** [comment]
Hey @marcschroeder, glad it works. It works nice for me too in a project that I'm working in. I looked the DefinitelyTyped and is Ok for me.
