### ISSUE TITLE
From 3.x upwards, constructor of Dockerode client is ignoring the ca, cert, and key fields passed through argument

### ISSUE THREAD

**Issue by jorgeclaro** [apocas/dockerode#576]
Up to v2.5.8, Dockerode constructor is consuming cert files properly, but from v3.0.0 upwards it's not working properly anymore. Seems that it's trying to fetch `ca`, `cert` and `key` files from default `.docker` folder instead.

**Comment by apocas** [comment]
This behaviour was not changed.

If you don't specify them, they are fetched from env var "DOCKER_CERT_PATH".
https://github.com/apocas/docker-modem/blob/master/lib/modem.js#L56

But you can manually specify them: https://github.com/apocas/docker-modem/blob/master/lib/modem.js#L84

Could you detail a bit more?

**Comment by jorgeclaro** [comment]
Well, not sure if DOCKER_CERT_PATH is set, but if I am specifying those manually on Dockerode constructor, It should override the ones provided by DOCKER_CERT_PATH, correct?

**Comment by apocas** [comment]
Correct.
Even if DOCKER_CERT_PATH is set, manually passing the properties "key", "cert" and "ca" will override them.

**Comment by jorgeclaro** [comment]
The following snippet works just fine on v2.5.8:
```
function getDockerClient() {
    const [ca, cert, key] = await Promise.all([
        file.read('<path_to_ca>/ca.pem>'),
        file.read('<path_to_cert>/cert.pem'),
        file.read('<path_to_key>/key.pem>'),
    ]);	

    return new Dockerode({
        version: 'v1.39',
        host: <host>,
        port: 2376,
        ca,
        cert,
        key,
    });
}
```

After updating to v3.x.x, the Dockerode constructor started to fail on that snippet, throwing: `ENOENT: no such file or directory, open '<DOCKER_CERT_PATH>/ca.pem'`. So it seems that is still using DOCKER_CERT_PATH even when `ca`, `cert`, and 'key' fields are provided.

**Comment by apocas** [comment]
I can't replicate this.
https://github.com/apocas/dockerode/blob/master/test/docker.js#L27 this test should throw right?

If ca, cert or key is undefined that would happen, are you sure they are defined?

**Comment by jorgeclaro** [comment]
Yes, I am sure those are defined as `strings`. The exact same code is working correctly with v2.5.8, so the cert files are being correctly read from disk.

Seems that the test is inconclusive considering that you did not set DOCKER_CERT_PATH environment variable. Might be an issue of wrong priorities between DOCKER_CERT_PATH and the constructor options.

**Comment by apocas** [comment]
I also tried that locally, still no success replicating it.
Added the env variable to test too.

**Comment by jorgeclaro** [comment]
Seems that I was redefining cert paths with wrong values.
Thanks for the support. I will close the issue.
