### ISSUE TITLE
Unable to connect via SSH with Private key

### ISSUE THREAD

**Issue by srcnix** [apocas/dockerode#581]
Trying to setup Dockerode connection with SSH and private keys.
- I have the host entry supporting the private keys in ~/.ssh/config
- ```docker -H ssh://10.0.2.15:22 service ls``` works as expected
- Any connection with Dockerode raises "Invalid username"

Example config

```javascript
const options = {
  protocol: 'ssh',
  host: `${nodeAddr}`,
  port: 22
}

new Docker(options)
```

Any thoughts?

**Comment by mcary** [comment]
I wanted to connect via privateKey also and found this work-around: https://github.com/apocas/docker-modem/pull/119#issuecomment-703002880
