### ISSUE TITLE
I may be going crazy. No data returned?

### ISSUE THREAD

**Issue by nickdnk** [apocas/dockerode#586]
Hello

I've been trying for hours to get this library to work. I've followed the basic examples and yet no matter what I do, all I can it to do is spit out errors.

I verified that I can navigate to http://localhost:2375 and read some JSON data in accordance with the Docker Engine API. So far so good. List containers for instance works here and gives me valid data.

Yet something as simple as:

``
 let docker = new Docker({protocol: 'http', host: 'localhost', port: 2375, version: 'v1.25'}); 
``

Followed by:
```
docker.info(function(data) {
 console.log(data)
});
``` 

Just spits out `null` ? The same does any basic function I can get it to run, such as straight from the examples:

```
docker.listContainers(function (err, containers) {
  console.log(err);
  console.log(containers);
});
```

Gives me `null` and `[]`.

If I provide invalid data with, say, passing an API version that does not exist; I'll get a 400 error in the callback as expected. But I cannot for the life of me get real data. What am I missing? If I pass an invalid hostname I'll also get a timeout error, as expected, so it does connect.

**Comment by nickdnk** [comment]
Now as if some kind of joke, after I made this post and just clicked the same code I've been clicking for hours, it started working. Out of the blue. I have never been this confused in my life.

**Comment by nickdnk** [comment]
Yeah it still doesn't do anything. Somebody is playing a joke on me, I'm sure.

**Comment by nickdnk** [comment]
So it turns out this was because I passed some invalid data to `createContainer.` In my case it was providing incorrect syntax to the `PortBindings `object. It just caused the entire function to silently fail. Perhaps you could introduce some kind of error pointing people in the right direction. I literally spent hours trying to understand what was wrong.

**Comment by apocas** [comment]
Probably dockerode is also waiting for docker which went silent.
There are a few endpoints that unfortunately fail silently upstream :/

Do you have a copy of the PortBindings you were providing?
