### ISSUE TITLE
tar-fs does not set windows directory permissions correctly

### ISSUE THREAD

**Issue by softwareplumber** [apocas/dockerode#590]
It seems there is a known issue with tar-fs in that it does not set windows directory permissions correctly. Compressing a Windows filesystem and then decompressing on Linux creates directories without search permission, thus rendering them inaccessible.

This might seem like an obscure problem but now we have the WSL backend for Docker, this is exactly what happens whenever we try to create an image with dockerode. It only works if all the files are in the root of the context directory. 

I had a look at the tar-fs issues list but the recommended 'workaround' is to patch up the permissions when decompressing the archive, which is clearly not much good here.

Has anyone else encountered this?

Thanks
Jon

**Comment by HarshadUpadhyay** [comment]
Yes, I am also having the same issue and the error is - 
Error: EPERM: operation not permitted, open 'C:\Users\abc.yaml'
