### ISSUE TITLE
Missing type definition for Container.wait

### ISSUE THREAD

**Issue by lesomnus** [apocas/dockerode#597]
JS signature:
https://github.com/apocas/dockerode/blob/409a08e310645f5a82234bc3a49b40c98fb98cdd/lib/container.js#L745-L753

TS definition:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5454930b2034878b7cf0d749a1272a5e37f41bfa/types/dockerode/index.d.ts#L85-L86

`Container.prototype.wait` accepts `opts` and `callback` but type definition only accept `callback`

**Comment by sergiz** [comment]
You should report this to DefinitelyTyped's repo ;)

**Comment by lesomnus** [comment]
Ah, I thought that d.ts is maintained by the owner, sorry.

**Comment by sergiz** [comment]
Ref https://github.com/apocas/dockerode/issues/217

**Comment by Rush** [comment]
Unfortunately the types are not in a good place right now. Bad types are almost worst than no types. One ought to be able to trust them.
