### ISSUE TITLE
Error: (HTTP code 400) unexpected - json: cannot unmarshal string into Go struct field ExecConfig.Cmd of type []string 

### ISSUE THREAD

**Issue by karimsx** [apocas/dockerode#612]
Hello everonye, 

i have this error when i try to execute a command using string rather than array of stirng

```Error: (HTTP code 400) unexpected - json: cannot unmarshal string into Go struct field ExecConfig.Cmd of type []string ```

```
const executer = await container.exec({
      Cmd: `ls -al`,
      AttachStdout: true,
      AttachStderr: true,
      Privileged: true,
    });

```

**Comment by sergiz** [comment]
Cmd is an array of strings, so
`Cmd: ['ls', '-al'],`
