### ISSUE TITLE
buildImage from image in private registry

### ISSUE THREAD

**Issue by ACosaLinan** [apocas/dockerode#618]
Hi! I can not build an image from an image in a private registry. Here is an example of my code:

Dockerfile:
`FROM <any_image_in_private_registry>` 

index.js
```
var Dockerode = require('dockerode');
dockerClient = new Dockerode();

dockerClient.buildImage({
      context: __dirname,
      src: ['Dockerfile']
}, {
      t: 'imgcwd',          
      registryconfig: {
            username:"xxx@xxx.xx",
            password:"xxxxxx", 
            auth:"",
            serveraddress:"privateregistry.xxxx.com:8443",
            email: '',
      }
}, function(error, output) {
      if (error) {
            return console.error(error);
      }
      output.pipe(process.stdout);
});
```

I get the response of ... "denied .Access forbidden".

It works with public images. Do you have any idea? Thanks!

**Comment by markcellus** [comment]
Having same issue @ACosaLinan. Were you able to figure out a workaround?

**Comment by pipex** [comment]
It looks like the engine `/build` endpoint does not support the `X-Auth-Config` header, but requires a `X-Registry-Config` header. Meaning the `authconfig` option does not have any effect for the `buildImage` method. 

The `registryconfig` option does work with the following format which support authentication to multiple registries (which is something desirable for a build).

`registryconfig: {'https://index.docker.io/v1/': {username: 'myusername', password: '<mypass>'}}`
