### ISSUE TITLE
Service Remove and/or stop is not available in package 

### ISSUE THREAD

**Issue by Daxcor69** [apocas/dockerode#623]
I must be missing something, but I can find a method to remove a created service nor just stop the service.  This service is just one container, so am I just supposed to use the  container methods? The docker api does have  "Delete Service" spec.

```
await containerId.stop();
await containerId.remove({ force: true });
```

Thanks
Brad

**Comment by apocas** [comment]
https://github.com/apocas/dockerode/blob/master/lib/service.js
