### ISSUE TITLE
dockerode.pull function resolves before the image is pulled

### ISSUE THREAD

**Issue by pietrzakacper** [apocas/dockerode#647]
It's quite easy to introduce a bug while using the `dockerode.pull` function.

The most intuitive behavior for me is that this function should resolve when the image is actually pulled, not when the pull command starts, as it works right now.

The fix is to just wait for the ending event on the returned stream such as:

``` ts
const pullStream = await this.dockerode.pull(name);

// Wait for pull to finish
 await new Promise(res => this.dockerode.modem.followProgress(pullStream, res));
```

**Comment by apocas** [comment]
Hi,

That was exactly the idea, it's by design, anyone should be able to follow their pull lifecycle if they need/want :)
If the function resolved only in the end it would be, for example, impossible to follow a pull in real time using the provided stream.

That's why there is the "followProgress" helper function.

Best regards,

**Comment by pietrzakacper** [comment]
Thanks for the quick reply. I gathered that there are some tradeoffs, just wanted to indicate that for some ppl it might be confusing. But yeah possibly the current implementation is the most flexible one

**Comment by dankochetov** [comment]
It is confusing all right, I was pulling (no pun intended) my hair out because of the "no such image" error until I found this issue. Would be good to at least add a heads up message to the pull documentation.

**Comment by qqilihq** [comment]
WOW, here’s another “We were bitten by the same dog”.

This took @danielesser and me approx. 8 man hours to debug why our cache was not working - and just **after** figuring out this behavior I found this ticket :-D

**Comment by nightknighto** [comment]
I would suggest adding an alternative method, for example `pullSync` or something, that would work like how we expect it to work.
