### ISSUE TITLE
Platform is not considered when building

### ISSUE THREAD

**Issue by almottier** [apocas/dockerode#648]
Hello,

I use dockerode on an Apple M1 ARM64 machine, I can't manage to build a simple image for the platform `linux/amd64`:

Here is my `./Dockerfile`:

```
FROM nginx
```

Here is the builder `build_img_files.js` (from the example) with platform `linux/amd64`:

```
var Docker = require('../../lib/docker');
var docker = new Docker({
  socketPath: '/var/run/docker.sock'
});

docker.buildImage({
  context: __dirname,
  src: ['Dockerfile']
}, {
  t: 'test',
  platform: 'linux/amd64'
}, function(error, output) {
  if (error) {
    return console.error(error);
  }
  output.pipe(process.stdout);
});
```

When I build then inspect it, the architecture is wrong:

```
➜ node build_img_files.js        
{"stream":"Step 1/1 : FROM nginx"}
{"stream":"\n"}
{"stream":" ---\u003e 215eb9aea4b0\n"}
{"aux":{"ID":"sha256:215eb9aea4b0cc7f8e12e888b39b18833b5d36a6d736e480a4eff8b4beb4aa0c"}}
{"stream":"Successfully built 215eb9aea4b0\n"}
{"stream":"Successfully tagged test:latest\n"}
➜ docker inspect test | grep Arch
        "Architecture": "arm64",
```

But if I build it with docker CLI, it is working:

```
➜ docker build --platform linux/amd64 . -t test2 
[+] Building 1.5s (5/5) FINISHED                                                                                                                                                                         
...
 => => writing image sha256:23f7854cb92700aeec573f6b98c6bbd701e0c4ed175a01843172ae167d9f25a7
 => => naming to docker.io/library/test2
➜ docker inspect test2 | grep Arch              
        "Architecture": "amd64",
```

**Comment by kentwelcome** [comment]
Based on our experiment, you can pull the base image with specific CPU architecture manually before building it.
Ex:
```JavaScript
var Docker = require('../../lib/docker');
var docker = new Docker({
  socketPath: '/var/run/docker.sock'
});

docker.pull('nginx', {
  platform: 'linux/amd64',
}, function(err, pull_output) {
  if (err) {
      console.error(err);
      return;
  }
  pull_output.pipe(process.stdout);
  docker.buildImage({
      context: __dirname,
      src: ['Dockerfile']
    }, {
      t: 'test',
      platform: 'linux/amd64'
    }, function(error, output) {
      if (error) {
        return console.error(error);
      }
      output.pipe(process.stdout);
    });
});
```

When calling docker-engine API to build an image, the docker-engine will use the existing base image in your host machine. If the base image in your host machine is arm64 architecture, the docker-engine will build the image in `arm64` even though we specific the CPU architecture as `amd64`.

**Comment by almottier** [comment]
This is not optimal. It can be any image in my `Dockerfile`...
It is working with docker CLI : `docker build --platform 'linux/amd64'` , could we consider this as a bug in dockerode ?

**Comment by apocas** [comment]
The platform option is being passed to Docker as specified in https://docs.docker.com/engine/api/v1.41/#tag/Image/operation/ImageBuild

I believe the issue is in Docker and in this case the only workaround is to pull it first, since the pull endpoint respects the platform property.
