### ISSUE TITLE
Can't able to pull from private repo

### ISSUE THREAD

**Issue by premkumar2499** [apocas/dockerode#653]
I am trying to pull the image from a private repo in AWS. 
I am providing the correct auth token in the docker pull API
`docker.pull('image:tag', { authConfig : auth }, function (err,stream) {
}):`
But it throws an error like unable to access repo,
Docker login required.
But i am able to pull the public images using this API (like Ubuntu).
It will be useful if somebody try to pull an image from the private repo using a token

**Comment by MatusBoa** [comment]
Im using it like this, and it works just fine. 

```js
const options = {
  authconfig: {
    username: USERNAME,
    password: PASSWORD,
  }
}

Dockerode.pull("my.registry/nginx:latest", options, (error, stream) => ...)
```

**Comment by kelvinwop** [comment]
I had this error too and it stems from the fact that 

await Dockerode.pull(...) only blocks until the command is issued, not until the image is pulled, so subsequent commands are issued too early before the image is ready. If anyone else is having this issue, simply:

```
export async function pullImage(
  docker: Docker,
  repoTag: string,
  authconfig: AuthConfig
): Promise<void> {
  return new Promise((resolve, reject) => {
    docker.pull(repoTag, { authconfig }, function (err, stream) {
      if (err || stream == null) {
        return reject(err);
      }

      docker.modem.followProgress(
        stream,
        (err: Error | null) => {
          if (err) {
            reject(err);
          } else {
            resolve();
          }
        },
        (event: unknown) => {
          console.log("pull progress", event);
        }
      );
    });
  });
}
```

and now you can

```
const auth = {
  username: "username",
  password: "password",
};

await pullImage(Dockerode, "my-private-repo.com/image:1.0.0", auth);
```

hope this helps someone :)
