### ISSUE TITLE
Stats are undefined

### ISSUE THREAD

**Issue by benjick** [apocas/dockerode#658]
Hello. What do I need to do in order to get cpu and memory stats?

I have this code:
```ts
const container = docker.getContainer(service);
const stats = await container.stats();
console.log('stats', stats.memory_stats, stats.cpu_stats);
```

But the output is just `stats undefined undefined`

Cheers
@benjick

**Comment by doomfalc** [comment]
I just ran into the same issue. The solution can be found here: https://github.com/apocas/dockerode/issues/555#issuecomment-633825030

```js
const containerStats = await container.stats({stream: false});
```

**Comment by benjick** [comment]
Thank you @doomfalc!
