### ISSUE TITLE
Breaking Change in v3.0.0

### ISSUE THREAD

**Issue by pawansingh00** [apocas/dockerode#709]
We are using this version ->     **"dockerode": "^2.4.3",**

and we want to upgrade to latest version.

While going through release comments found this -> 

**Breaking change:**
**_Promises interface was standardized, output property was removed._**

But not exactly what it means, or what will break with this and how to migrate, can somebody please help expalin this?

https://github.com/apocas/dockerode/releases?page=2
![image](https://user-images.githubusercontent.com/27332582/208642840-0a7c079a-ac48-439f-9cab-fba93850c360.png)

Thanks,
Pawan

**Comment by apocas** [comment]
Hi,

Output property was redundant, better than thousand words:
https://github.com/apocas/dockerode/compare/v2.5.8...v3.0.0#diff-f839dd1fbca92f7ee34436cc4b8380aee0793a279c56e1daf9c2f38a8593a3f1L326
