### ISSUE TITLE
Cannot locate Dockerfile because of .dockerignore

### ISSUE THREAD

**Issue by tony-ist** [apocas/dockerode#715]
Firstly, thanks for the great library.

When building an image from a repository that contains a `.dockerignore` file there is an issue. If this `.dockerignore` file contains `Dockerfile` itself, then we get an error `Cannot locate specified Dockerfile: Dockerfile`. I suppose it happens because `Dockerfile` is not sent with the context to the docker daemon.

When you try `docker build` command through the CLI, such repositories are built without any problems. 

Would be great to hear some feedback from you, if it is really a problem and not by design, I can make a PR that fixes it.

**Comment by apocas** [comment]
Inception :)
Yes we don't have any exception for "Dockerfile" it self in https://github.com/apocas/dockerode/blob/master/lib/util.js#L79 so it ignores it self basically :D

Interesting that CLI manages to build this.
