### ISSUE TITLE
`putArchive` should not return a stream ?

### ISSUE THREAD

**Issue by samuel-olivier** [apocas/dockerode#716]
`Container.putArchive` currently returns a readable stream because of the [isStream: true](https://github.com/apocas/dockerode/blob/master/lib/container.js#L980) that has been in the `putArchive` function since it was created.

Though, the [docker api documentation](https://docs.docker.com/engine/api/v1.41/#tag/Container/operation/PutContainerArchive) doesn't mention providing anything in the response body as far as I know. Also if we try to read the content of the stream returned by `Container.putArchive`, it seems empty.

I might be missing something but I think we can just remove the `isStream: true` for this function ? I can do the PR but I'd like your insight on this before.

**Comment by apocas** [comment]
Yes, open a PR removing it :)

**Comment by samuel-olivier** [comment]
@apocas here is the PR: https://github.com/apocas/dockerode/pull/720
