### ISSUE TITLE
Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by ether-wan** [apocas/dockerode#722]
Hello, i'm trying to launch container w/ dockerode on Mac OS

```
const docker = new Docker({host: 'http://0.0.0.0', port: 3000, socketPath: '/var/run/docker.sock'});

    const container = await docker.createContainer({
        Image: 'app-bot',
        HostConfig: {
            PortBindings: {
                [`${3000}/http`]: [{ HostPort: 50000 }]
            }
        }
    });
    await container.start();
```

I'm getting an error : 

`
Error: connect ECONNREFUSED 0.0.0.0:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '0.0.0.0',
  port: 3000
}
`

The docker service run with colima ( https://github.com/abiosoft/colima ) 

The deployment of the image works with  `docker run -p 50000:3000 app-bot` command on the terminal

Thanks !!

**Comment by reptincel-cpu** [comment]
Thans @danisharora099 for your reply. I'm not sure where I should use `ExposedPorts`, can you give me an example please

**Comment by reptincel-cpu** [comment]
> 
it doesn't work for me, I still get the ECONNREFUSED error. Are there any specific permissions to give ? 

```
Error: connect ECONNREFUSED 0.0.0.0:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '0.0.0.0',
  port: 3000
}
```
