### ISSUE TITLE
Missing Changelog

### ISSUE THREAD

**Issue by NGPixel** [apocas/dockerode#746]
@apocas Would it be possible to have some sort of changelog when new releases are published? Right now it's impossible to know what changed. 

Is it safe to upgrade to 4.0.0? Is there any breaking changes? Impossible to tell because there's no information in the releases nor is there a CHANGELOG file....

Thanks

**Comment by nwalters512** [comment]
Here's a link to the diff showing changes from the previous version: https://github.com/apocas/dockerode/compare/v3.3.5...v4.0.0.

According to this, it looks like the only breaking change is that `putArchive` no longer returns a stream. It looks like the package is also no officially tested against Bun, which is neat!

**Comment by NGPixel** [comment]
@nwalters512 I shouldn't have to go through a list of commits and diff to learn what changed in a dependency. Projects can have hundreds of dependencies. This is simply an unrealistic and ridiculous ask for the users.

Providing a basic changelog when publishing a new version of a library is a must. It takes seconds on the part of the author and if you use conventional commits, it can even be generated automatically for you. (e.g. [changelog-action](https://github.com/requarks/changelog-action) which I wrote).

**Comment by apocas** [comment]
Yup totally agree :+1: 
Major bumps (breaking changes) will have descriptions from now on.

**Comment by nwalters512** [comment]
@NGPixel I wasn't trying to suggest that a changelog shouldn't be maintained, I was just trying to provide helpful information to you and others who might stumble across this issue while looking for a description of recent changes (like I did!).

**Comment by kb2ma** [comment]
@apocas  You may remember we posted #695 to fix our use case for `buildImage()`. We look forward to updating our dockerode dependency to the new release. I see a partial [explanation](https://github.com/apocas/dockerode/issues/751#issuecomment-1796514600) in #751 for the major version bump. As a practical matter, it will help scope our testing if you provide a full description for the version update and what may be affected. Of course we'll share any unexpected findings.
