### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Clashsoft** [apocas/dockerode#749]
The v4 Release page does not provide any info. What changed and why is it a breaking change? Can you please provide a changelog?

**Comment by Clovel** [comment]
I would also be interrested in knowing what changed and if there are any breaking changes.

**Comment by Clovel** [comment]
It also seems that docker-modem has the same issue. 

And both `@types/` packages are stuck at v3.X.Y

**Comment by nwalters512** [comment]
Duplicate of #746?

In the interest of crowd-sourcing a changelog, here's a breaking change I found in v4: https://github.com/apocas/dockerode/issues/751

**Comment by apocas** [comment]
It was the only one. And it was wrongly introduced, it was reverted since then.
