### ISSUE TITLE
Undocumented breaking change: container.logs now produces a string

### ISSUE THREAD

**Issue by nwalters512** [apocas/dockerode#751]
In version `3.3.5`, `container.logs({ follow: false })` (or just `container.logs()`) produced a `Buffer`. However, in the latest version, it produces a string. This can be easily replicated with the following test, which one can add to the `#logs` section in `test/container.js`:

```js
    it("should get the logs for a container as a buffer", function(done) {
      this.timeout(30000);

      var container = docker.getContainer(testContainer);
      var logs_opts = {
        follow: false,
        stdout: true,
        stderr: true,
        timestamps: true
      };

      function handler(err, buffer) {
        expect(err).to.be.null;
        expect(buffer).to.be.instanceof(Buffer);
        done();
      }

      container.logs(logs_opts, handler);
    });
```

This test passes on tag `v3.3.5`, but fails on the latest `master`.

If this new behavior is intentional, it should be documented, and an option to use the old behavior should be provided. If it is not intentional, I'd be happy to look into contributing a fix if a maintainer could point me in the right direction.

**Comment by nwalters512** [comment]
Further investigation reveals that this is likely an issue with `docker-modem`, as installing an old version of that package (v3) on the latest master of `dockerode` results in the above test passing.

**Comment by nwalters512** [comment]
AFAICT, this was changed in this commit: https://github.com/apocas/docker-modem/commit/8b415dd0a9876c5e670a3dab3b1fdaa798c611ea

It looks like this commit tried to revert that, but it is incorrectly using `|| result` instead of `|| buffer`: https://github.com/apocas/docker-modem/commit/8e054177ded397b6166159fd723b0e45445d3ae7

@apocas I'd be happy to open a PR fixing this if you can confirm that the above revert was done incorrectly and it should actually return the buffer directly.

**Comment by apocas** [comment]
Hi,

So this was one part of the mess that got us in a major bump.
It was introduced in docker-modem from a PR that I accepted, I miss judged the consequences of that PR (converting it to stream).

Yes we should revert this, buffer is the proper type.

Best regards,

**Comment by nwalters512** [comment]
Thanks for confirming, I'll open a PR shortly!

**Comment by nwalters512** [comment]
https://github.com/apocas/docker-modem/pull/161

**Comment by gallynero** [comment]
Is `|| buffer` or `|| stream.Readable.from(buffer)`?

**Comment by apocas** [comment]
buffer like it was before all this mess, going to publish docker-modem today

**Comment by apocas** [comment]
Fixed.
