### ISSUE TITLE
container.attach writes attachOptions into container's stdin

### ISSUE THREAD

**Issue by NoOneHardy** [apocas/dockerode#777]
When writing into container's stdin sometimes dockerode automatically writes attachOptions infront of the actual input.
Does anybody have the same issue and a possible solution?

## Input

`{"stream":true,"stdin":true,"stdout":true,"stderr":true,"hijack":true,"logs":false}say hello`

## Code

```
const container = docker.getContainer('720736bad7ecc2f1ced7364366a69e240d1a6ad5dea02f9a77f3c2b0bb7990ae')

container.attach({
  stream: true,
  stdin: true,
  stdout: true,
  stderr: true,
  hijack: true,
  logs: false
}, (_, stream) => {
  // Map output to console
  stream.pipe(process.stdout)

  const string = 'say hello\n'
  // Write data to the container's stdin
  stream.write(string)
})```

**Comment by Luluno01** [comment]
Hi! We are also having the same issue. Any updates in the past 4 months? Are you using a Mac by any chance?

**Comment by NoOneHardy** [comment]
@Luluno01 No unfortunately not.
I ended up writing it myself from scratch with the Docker API

Are you trying to connect to a Minecraft Server in a docker container?
I think the problem only occurs in this specific case.

**Comment by NoOneHardy** [comment]
@Luluno01 No unfortunately not.
I ended up writing it myself from scratch with the Docker API

Are you trying to connect to a Minecraft Server in a docker container?
I think the problem only occurs in this specific case.

**Comment by Luluno01** [comment]
> @Luluno01 No unfortunately not. I ended up writing it myself from scratch with the Docker API
> 
> Are you trying to connect to a Minecraft Server in a docker container? I think the problem only occurs in this specific case.

Thanks for the information. No, I'm just spinning up a container running a Node.js application and writing some inputs via `stdin`. I would not call my case as some "specific" case, though.

**Comment by Luluno01** [comment]
Hi, I find this problem might relate to docker version. Would you mind sharing your docker version? Thanks!
