### ISSUE TITLE
Docker API update v1.47

### ISSUE THREAD

**Issue by lilacdev** [apocas/dockerode#780]
Hello there,

Just to let you know a feature was added to mount options  :

```js
Mounts: [
  {
    Type: 'volume',
    Source: 'dev_data',
    Target: '/my-data',
    VolumeOptions: {
      Subpath: 'subpath' <------------------------
    }
  },
],
```

With a `// @ts-ignore`, it works, so I guess you just need to update types somewhere.

See reference here : https://docs.docker.com/reference/api/engine/version/v1.47/#tag/Container/operation/ContainerCreate

And by the way, thanks for amazing work.

**Comment by SelfhostedPro** [comment]
This project doesn't produce types. I'll work on getting a pr into definitely typed though. In the future, if you're wanting to make changes to the types, this is the source: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/dockerode

**Comment by lilacdev** [comment]
I just did a pull request, thanks for redirecting me as well ! I guess I can close this now.
