### ISSUE TITLE
Two way SSL

### ISSUE THREAD

**Issue by ReedD** [apocas/dockerode#81]
Is there a way to use two way SSL with dockerode as described [here](https://docs.docker.com/articles/https/)? 

Currently I'm able to make this work manually with the standard https library built into node:

```
var https = require('https'),
    fs = require('fs');

var options = {
    hostname: 'ec2-54-187-244-245.us-west-2.compute.amazonaws.com',
    port: 2376,
    path: '/info',
    method: 'GET',
    key:  fs.readFileSync('./certs/client-key.pem'),
    cert: fs.readFileSync('./certs/client-cert.pem'),
    ca:   fs.readFileSync('./certs/ca.pem')
};
options.agent = new https.Agent(options);

var req = https.request(options, function(res) {
    console.log("statusCode: ", res.statusCode);
    console.log("headers: ", res.headers);

    res.on('data', function(d) {
        process.stdout.write(d);
    });
});
req.end();

req.on('error', function(e) {
    console.error(e);
});
```

However, the code above is not ideal and I'd much rather use dockerode but I don't see any documentation indicating the ability to use required authentication PEM files.

**Comment by nicholasanthonys** [comment]
@apocas @ReedD do you know how to generate ca.pem, cert.pem and key.pem into separate 3 files ?
