### ISSUE TITLE
Question: Options in createContainer method

### ISSUE THREAD

**Issue by iamspix** [apocas/dockerode#92]
Am I missing some documentation, or the README has it all?

in the example, it only shows some options like `Cmd`, ``Image (FROM in a Dockerfile)`, `name`
Is it possible to use all options that can be used in the docker file? thanks!

**Comment by githubTTest** [comment]
https://docs.docker.com/reference/api/docker_remote_api_v1.14/#create-a-container
link doesn't exist anymore.
